### PR TITLE
fix(docs): Sphinx 4.4.0 has trouble resolving type hinted Tracer class

### PR DESCRIPTION
**Pull request by brettlangdon**
## Commit Message

{{title}}

Fixes:

```
dd-trace-py/ddtrace/span.py:docstring of ddtrace.span.Span::more than one target found for cross-reference 'Tracer': ddtrace.opentracer.Tracer, ddtrace.opentracer.tracer.Tracer, ddtrace.Tracer, ddtrace.tracer.Tracer
```

### CODE REVIEW

**Review by Kyle-Verhoog — APPROVED** [review]

**Review by jd — APPROVED** [review]

**Comment by brettlangdon** [comment]
Closing in favor of #3138

**Comment by brettlangdon** [comment]
nvm, #3138 is unfortunately a difficult change.

**Comment by brettlangdon** [comment]
@Mergifyio backport 0.57

**Comment by jd** [comment]
@Mergifyio backport 0.56

**Pull request merged**
