### PR TITLE
fix(flask-caching): support v2.0

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
## Description

flask-caching released version 2.0 which moves the cache client to a new library
called [`cachelib`](https://github.com/pallets-eco/cachelib).

Diff here: https://github.com/pallets-eco/flask-caching/compare/v1.10.0...v2.0.0

This breaks our logic which collects tags for the redis client.

## Fix

It was noticed that both `_write_client` and `_read_client` use the same connection information
so we don't need to dynamically check for each.

Also [`_read_clients`](https://github.com/pallets-eco/flask-caching/blob/ac13e01baa11d65c68dcba64f99ccaafd9b5419c/src/flask_caching/backends/rediscache.py#L62) was moved to [`_read_client`](https://github.com/pallets-eco/cachelib/blob/13c8bf8db156dd06154f5e08e23bdd9e73480a5b/src/cachelib/redis.py#L29) when the logic was moved to `cachelib`.

## Checklist
- [ ] Title must conform to [conventional commit](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] Ensure tests are passing for affected code.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Reviewer Checklist
- [x] Title is accurate.
- [x] Description motivates each change.
- [x] No unnecessary changes were introduced in this PR.
- [x] PR cannot be broken up into smaller PRs.
- [x] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Tests provided or description of manual testing performed is included in the code or PR.
- [x] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.
- [ ] Add to milestone.

### CODE REVIEW

**Review by mabdinur — DISMISSED** [review]
should this pr be a `fix` instead of a `chore`? If so we should update the PR title and add a release note

**Comment by Kyle-Verhoog** [comment]
yeah idk. It's a "fix" I suppose since we technically support the latest version of `flask_caching`... 🤷‍♂️ i'll add a release note and update the title

**Review by mabdinur — APPROVED** [review]

**Comment by Kyle-Verhoog** [comment]
@mergifyio backport 1.2 1.1 1.0 0.x

**Comment by mabdinur** [comment]
@Mergifyio backport 0.61

**Pull request merged**
