### PR TITLE
fix(ci_visibility): don't enable CIVisibility on API 403

### PR DESCRIPTION
**Pull request by romainkomorndatadog**
This changes the `CIVisibility` service to no longer succesfully `.enable()` if we encounter a `403` status code during API requests.

This change can be made due to the fact that we now call our settings API early on in the enabling process, and can make the decision not to continue enabling. Prior to this, sending data was best effort, but getting a 403 from the API means that subsequent queries (and span submissions) likely won't succeed, so there's no point in enabling the service.

Instead, we just supply an error message:
```
[Datadog CI Visibility] WARNING  ddtrace.internal.ci_visibility.recorder:recorder.py:510 Authentication error, disabling CI Visibility, please check Datadog API key
```

This isn't considered a breaking change because the end result (data not being submitted successfully) is the same.

This has been tested both using `DD_CIVISIBILITY_AGENTLESS_ENABLED=1` and an invalid API key, as well as with it set to `0`, relying on EVP proxy mode to a Datadog agent with an invalid API key.

This PR also updates a bunch of tests to properly mock the function that talks to our production settings API, since these would generate 403s, which in the past was invisible, but now would cause CI Visibility to be disabled.

This change also introduces a set of CI Visibility-specific integration environments which gives a little bit better visibility at the cost some delicious, though unfortunate, copy/pasta which.

Other note: this is labeled as a "fix" in the PR title because our PR title check script doesn't allow for it to start with `upgrade`.

## Checklist

- [x] Change(s) are motivated and described in the PR description
- [x] Testing strategy is described if automated tests are not included in the PR
- [x] Risks are described (performance impact, potential for breakage, maintainability)
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed or label `changelog/no-changelog` is set
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/))
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))
- [x] If this PR changes the public interface, I've notified `@DataDog/apm-tees`.
- [x] If change touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.

## Reviewer Checklist

- [x] Title is accurate
- [x] All changes are related to the pull request's stated goal
- [x] Description motivates each change
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- [x] Testing strategy adequately addresses listed risks
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] Release note makes sense to a user of the library
- [x] Author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Comment by romainkomorndatadog** [comment]
I convinced myself this was gonna be a small change and here we are...

I don't think this should be backported, but I also don't think it's a "feature"... but since it has some impact, it's also not a "chore", so release-note-wise, I'm not sure.

**Review by juan-fernandez — APPROVED** [review]

**Comment by ZStriker19** [comment]
At first, I was worried this relied on hitting the agent, in which case the tracer might start up and query before the agent was ready, but since it relies on the site, which should be ever present as long as networking is setup beforehand (which should be always), this change seems good to me.

**Review by ZStriker19 — APPROVED** [review]

**Comment by romainkomorndatadog** [comment]
> At first, I was worried this relied on hitting the agent

Actually, that's a pretty good point, @ZStriker19 . We do rely on the agent in EVP proxy mode, but since this is specifically about a `403` status code specifically, we wouldn't get that unless the agent was up and able to proxy requests to our API, so it's essentially "the same".

**Comment by romainkomorndatadog** [comment]
Checked off the checklist myself since it's been a few days and I've got two approvals.

**Pull request merged**
