### PR TITLE
If trace disabled dont trace

### PR DESCRIPTION
**Pull request by JBKahn**
We're seeing for environments where the tracer is disabled, the memory used by ddtrace is non-negligible for larger jobs.

We're testing to see if this change is enough to stop it from using the additional memory and to see what tests fail with these changes.

This is a work in progress.

### CODE REVIEW

**Comment by brettlangdon** [comment]
hey @JBKahn thanks for opening this!!

this is something we have been thinking about for a bit but haven't had a chance to get around to working on yet.

I think there are a few tricky parts to try and get right:

1. What about metrics?
  a. If you noop/disable the tracer, do you still want to receive metrics? You just won't see any traces (effectively a sample rate of 0)?
2. What happens when integrations or custom instrumentation runs that expects an active span?
  a. e.g.

```python
@app.middleware
def add_tags_middleware(request):
    span = tracer.current_[root_]span()
    span.set_tag('user.id', request.user_id)
```

While for the above, it is easy, you just add an `if span: span.set_tag()`, just thinking through the scenarios when disabling might be a "breaking" change.

3. What happens when a service "middle" service in a distributed trace is disabled?
  a. e.g. for services A -> B -> C, if you disable B, do you still want to see a trace connecting A -> C?


Not saying your approach is wrong BTW, just wanted to outline the current "edge cases" I have been thinking about when thinking about disabling or no-oping the tracer.

The approach we have been thinking about is actually have a "NoopSpan", when the tracer is disabled you keep minimal context about the current trace, things like the trace id, parent span id, service name, and etc so that you can still generate stats based on that data and distribute the context through other requests while keeping the overhead of the tracer very minimal.

**Comment by brettlangdon** [comment]
Also, out of curiosity, what integrations are you using besides Django?

I know some of the our newer integrations actually check to see if the tracer is enabled before trying to create a span, but not all of our integrations do this.

**Comment by majorgreys** [comment]
We are going to investigate this issue further. @JBKahn did you have anything in mind on the solution that you've proposed here?

**Comment by majorgreys** [comment]
Being that using the enabled flag is specified in #1575 as still producing spans, we will need to address this requirement in another way.

> DD_TRACE_ENABLED: used to disable the sending of spans to the agent, spans are still produced. The variable was previously used only in ddtrace-run where it also disabled patching. This functionality is maintained for backwards compatibility while the new functionality is added to the core library.

**Pull request closed without merging**
