### PR TITLE
refactor trace agent writer

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
## Description
This is a refactor of the back-end writing portion of the tracing client.

Formerly the logic for submitting traces to the agent was divided amongst
several classes:

- `Tracer`: writes the traces to an AgentWriter instance
- `AgentWriter`: submits traces to a bounded `TraceQueue` instance and asychronously
  periodically reads the queue, applies filters and submits traces using an
  `API` instance.
- `API` has a `Payload` instance which encodes the traces which are finally
  sent to the trace agent.

There were numerous problems with this approach:

**Problem 1:** The limit on the trace queue was fixed to be a _number of
traces_ which is not a good measure of the size of a payload and resulted in
many acceptable payloads being dropped.

**Solution:** Use the encoded byte size of a trace instead of trace count for
limits.

**Problem 2:** Unnecessary abstraction. There is no good reason for the `API`
and `Payload` classes to exist.

**Solution:** Move the functionality to `AgentWriter`.

**Problem 3:** Filters were applied _after_ the trace queue. Traces that were
filtered out would still remain in memory and be queued (counting toward that
trace limit) because the filter logic was in the `AgentWriter`.

**Solution:** Move the filtering logic to the ``Tracer`` class.

**Problem 4:** Only flushing periodically.
**Solution:** Flush when a threshold has been met in addition to flushing periodically.

**Problem 5:** Encoding occurred in the ``AgentWriter`` thread. It might have
been thought of that encoding in the thread would increase the performance of
the trace client. However, this is not how Python works and instead this would
result in non-deterministic (every second or so) hogging of the CPU as the
trace client popped all the traces and encoded them at once.

**Solution:** Encode the traces as they complete before buffering them to be sent.

Futher improvements (outside the scope of this PR):

- Use tenacity for retrying requests
- Reintroduce health metrics

## Checklist
- [ ] Entry added to release notes using [reno](https://docs.openstack.org/reno/latest/user/usage.html)
- [ ] Tests provided; and/or
- [ ] Description of manual testing performed and explanation is included in the code and/or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Comment by brettlangdon** [comment]
probably better for each of those problem/solutions to be in their own PR

**Comment by brettlangdon** [comment]
> Problem 3: Filters were applied after the trace queue. Traces that were
filtered out would still remain in memory and be queued (counting toward that
trace limit) because the filter logic was in the AgentWriter.

I'd like to approach this one from a different angle.

I actually kind of like the OTel SpanProcessor approach. Essentially hooks that you can add around span creation.

https://github.com/open-telemetry/opentelemetry-python/blob/5fc08ad642dc7b9acd557536647e789b540bc2ff/opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py#L62-L105

A lot of times it seems much more useful for someone to modify a span once it is started or immediately as it finishes than after the fact.

For example, in Flask, what if you want to add additional metadata from the current request, doing in background progress you no longer have that context.

What if you want to reject healthcheck traces, you could reject the trace (maybe turn it into a no-op) from the start of the trace rather that after it has already been created?

**Comment by brettlangdon** [comment]
> Problem 5: Encoding occurred in the AgentWriter thread. It might have
been thought of that encoding in the thread would increase the performance of
the trace client. However, this is not how Python works and instead this would
result in non-deterministic (every second or so) hogging of the CPU as the
trace client popped all the traces and encoded them at once.
> 
> Solution: Encode the traces as they complete before buffering them to be sent.

Other than encoding, do we have a way to move the data out of the VM (out of the realm of the GIL)?

For your proposed change we are just reorganizing the structure of the code since it doesn't make a difference because of the GIL. But, is there a change we can make to reduce the impact of the GIL on our background worker?

Not arguing against the organizational change, if it cleans up the code and doesn't make a difference, then it is a win. Just thinking, can we do anything else to re-think about how our encoding interacts with the GIL to reduce the overall impact of us locking the GIL?

**Comment by Kyle-Verhoog** [comment]
> probably better for each of those problem/solutions to be in their own PR

Yep in hindsight it should be doable to split out a couple of the bigger changes. This PR will serve as the tracking PR.

As for filters they need a rework/redesign but that's a 1.0 conversation. Right now I just want to clean up how they presently exist. I like and agree with the ideas, just not the place for it right now 🙂 

> Other than encoding, do we have a way to move the data out of the VM (out of the realm of the GIL)?

In order to get out of the VM we need to cross the process boundary which will incur heavy costs for serializing data for transport between processes. We could explore [Cython's parallelism](https://cython.readthedocs.io/en/latest/src/userguide/parallelism.html) which releases the GIL and uses openMP but this is a bigger change. The focus now is to just make the performance more deterministic.

**Comment by brettlangdon** [comment]
> As for filters they need a rework/redesign but that's a 1.0 conversation. Right now I just want to clean up how they presently exist. I like and agree with the ideas, just not the place for it right now 🙂

Do our filters also lock the GIL in a way where we are not gaining benefits from being in a background thread?


> In order to get out of the VM we need to cross the process boundary which will incur heavy costs for serializing data for transport between processes. We could explore Cython's parallelism which releases the GIL and uses openMP but this is a bigger change. The focus now is to just make the performance more deterministic.

Agreed, just figured worth bringing up, making sure this is something we are thinking about as well.

**Comment by Kyle-Verhoog** [comment]
> Do our filters also lock the GIL in a way where we are not gaining benefits from being in a background thread?

The only benefit we get from the background thread is for making the http request (I/O operation, GIL released). All other cases Python code is running and so the GIL is held. So no benefit whatsoever to having the filters/encoding run in the background thread.

> Agreed, just figured worth bringing up, making sure this is something we are thinking about as well.

Definitely worth bringing up just a bigger change (also introduces a dependency on openMP).

**Comment by Kyle-Verhoog** [comment]
closing since this work is being split and merged into the `writer-refactor` branch.

**Pull request closed without merging**
