### PR TITLE
chore(ci/profiling): bump number of runners

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
[27m45s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/23931/workflows/da46d188-8b20-4765-8912-40035b77710f/jobs/1625550/parallel-runs/0?filterBy=ALL) -> [12m13s](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/23936/workflows/da820b94-3ca3-43f9-9a74-670946616554/jobs/1625757/parallel-runs/6?filterBy=ALL).

## Reviewer Checklist
- [x] Title is accurate.
- [ ] Description motivates each change.
- [x] No unnecessary changes were introduced in this PR.
- [x] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Tests provided or description of manual testing performed is included in the code or PR.
- [x] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [x] All relevant GitHub issues are correctly linked.
- [x] Backports are identified and tagged with Mergifyio.

### CODE REVIEW

**Review by brettlangdon — COMMENTED** [review]
should we do this for the other profiling jobs? the windows ones which take up to 42m?

**Comment by majorgreys** [comment]
Do we know if this change affects the total credits used in CircleCI?

**Comment by Kyle-Verhoog** [comment]
> should we do this for the other profiling jobs? the windows ones which take up to 42m?

@brettlangdon is this a blocker for this PR?

> Do we know if this change affects the total credits used in CircleCI?

@majorgreys if this is a concern we can likely merge some of our existing jobs (eg. all the stdlib jobs) into one

**Review by brettlangdon — APPROVED** [review]

**Review by Yun-Kim — APPROVED** [review]

**Review by mabdinur — APPROVED** [review]

**Comment by Kyle-Verhoog** [comment]
@majorgreys I'm going to follow up this PR with merging sqlite3, asyncio, dbapi and futures into one suite to cut down on the number of runners. Also going to look at any other suites where maybe we could do away with unnecessary parallelism.

**Pull request merged**
