### PR TITLE
fix(profiling): restart the profiler on uwsgi fork

### PR DESCRIPTION
**Pull request by jd**
In uWSGI, the current code starts in the forked process the ProfilerInstance
that has been created in the master process. That actually works fine, except
all Events are discarded by the Recorder because its `pid` attribute is not
updated: it is still the pid of the master process.

Using the `_restart_on_fork` method makes sure that the `ProfilerInstance` gets
a new `Recorder` object with the correct PID.

The test is updated to not test only for file presence, but making sure that
there is at least one sample included.

### CODE REVIEW

**Comment by jd** [comment]
It'd be nice to backport this to 0.47 and 0.48.

**Review by P403n1x87 — DISMISSED** [review]

**Review by P403n1x87 — DISMISSED** [review]

**Comment by jd** [comment]
@mergifyio backport 0.48

**Comment by jd** [comment]
@mergifyio backport 0.47

**Comment by majorgreys** [comment]
I'm not clear on why this would be necessary if `_ProfilerInstance` was not being initialized and started in the uwsgi master process, which is when the recorder would have been initialized. Are we not correctly detecting the condition when we are in the master process? I had this problem with `ddtrace-run` since the `uwsgi` module was not loaded when we initialized the runtime metrics worker.

**Comment by jd** [comment]
> I'm not clear on why this would be necessary if _ProfilerInstance was not being initialized and started in the uwsgi master process, which is when the recorder would have been initialized. Are we not correctly detecting the condition when we are in the master process? I had this problem with ddtrace-run since the uwsgi module was not loaded when we initialized the runtime metrics worker.


It is initialized (not started) in the uwsgi master: a `_ProfilerInstance` is always created and the code at https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/profiling/profiler.py#L234-L248 create the `Recorder` which stores the current PID (= the master uwsgi pid). Which is why later all the events pushed to the `Recorder` are being ignored.

**Review by P403n1x87 — APPROVED** [review]

**Review by Yun-Kim — APPROVED** [review]

**Pull request merged**
