### PR TITLE
chore(test): fix to precommit hook slotscheck

### PR DESCRIPTION
**Pull request by christophe-papazian**
## Description

Adds a python script to set PYTHONPATH correctly for any file checked by the pre-commit hook slotscheck. It will prevent  ModuleNotFoundError on the file tested (but you still need to install any required external dependencies).

## Checklist
- [ ] Followed the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) when writing a release note.
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added and follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines), or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Change contains telemetry where appropriate (logs, metrics, etc.).
- [ ] Telemetry is meaningful, actionable and does not have the potential to leak sensitive data.

### CODE REVIEW

**Review by gnufede — APPROVED** [review]

**Review by brettlangdon — COMMENTED** [review]
can you add an example of the failure that this fixes?

**Comment by brettlangdon** [comment]
Should the slots check just be removed entirely? cc @majorgreys

**Comment by emmettbutler** [comment]
I think this change might be superseded by https://github.com/DataDog/dd-trace-py/pull/4989.

**Comment by brettlangdon** [comment]
Closing for now since #4989 should have fixed this, if not @christophe-papazian please re-open!!!!

**Pull request closed without merging**
