### PR TITLE
refactor(telemetry): combine telemetry metrics and lifecycle writers

### PR DESCRIPTION
**Pull request by mabdinur**
## Backrgound

The goal of this PR is to improve the performance and readability of telemetry writers. When the telemetry metrics writer was first introduced there were concerns about the memory usage and stability of this feature. To mitigate this, two telemetry writers were created that could be enabled and disabled independently of each other. The metrics telemetry writer was given a periodic interval of 1 second while the original telemetry writer maintained a periodic interval of 1. However this concern was overblown. 

This PR combines both writers and significantly simplifies the logic and tests. I think this is a step in the right direction.

## Description

Combines the telemetry metrics writer and telemetry lifecycle writer. 

## Changes

- Moves all methods in TelemetryBase and TelemetryLogsMetricsWriter to the TelemetryWriter class. 
- This refactor all combines all overridden methods into one "super" method
   - ex: All the logic in TelemetryBase.periodic() and TelemetryLogsMetricsWriter.periodic() were moved to TelemetryWriter.periodic()
- Replaces all invocations of telemetry_lifecycle_writer, and telemetry_metrics_writer with telemetry_writer.
- Updates benchmarks to mock the new `telemetry_writer` singleton. 
   - Note - the benchmark scenarios are run using the dd-trace-py/benchmarks directory defined in the 1.x branch. All changes to benchmarks will only take effect after this PR is merged.
- Removes all usages of telemetry_lifecycle_writer, and telemetry_metrics_writer in tests.
- Updates telemetry metrics tests to ignore telemetry lifecycle events or updates assertions to validate the new events
- Updates span aggregator to only call telemetry_writer.periodic if span count metrics have been queued. This is required to fix failing tests.
- Removes `DD_TELEMETRY_METRICS_ENABLED` configuration. This adds unnecessary complexity. All telemetry events should be sent or none should be sent. There is no need to single out metrics and logs. 

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if [applicable](../docs/contributing.rst#release-branch-maintenance))

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](../docs/contributing.rst#release-branch-maintenance)

### CODE REVIEW

**Comment by mabdinur** [comment]
Closing for now. This is a low priority task

**Comment by P403n1x87** [comment]
What is the motivation behind this change? Is this a performance improvement?

**Comment by mabdinur** [comment]
> What is the motivation behind this change? Is this a performance improvement?

Performance and readability. There were concerns about the memory usage associated with sending metrics and logs every 60 seconds. To mitigate this the telemetry metrics writer was created with an interval of 1.  However this concern was overblown. 

This PR combines both writers and significantly simplifies the logic and tests. I think this is a step in the right direction.

I will update the PR description.

**Comment by mabdinur** [comment]
> ## Benchmarks
> 
> Comparing candidate commit aad3fd2957be2a366e250fd86446b4fdb582e778 in PR branch `munir/combine-telemetry-writers` with baseline commit 09956e4ba175d53c1d81a41a41ea600dde171cc0 in branch `1.x`.
> 
> Found 0 performance improvements and 2 performance regressions! Performance is the same for 92 cases.
> 
> #### scenario:flasksimple-appsec-get
> 
> - 🟥 `execution_time` [+0.419ms; +0.452ms] or [+6.967%; +7.512%]
> 
> #### scenario:flasksimple-appsec-telemetry
> 
> - 🟥 `execution_time` [+0.432ms; +0.459ms] or [+7.189%; +7.646%]
> 
> 
> 
> 


The benchmarks appear to be noisy. This change should not negatively impact performance.

**Comment by mabdinur** [comment]
> Nice work! I think some more details in the description about why each type of change is made would make this pull request more approachable to review. The large diff can be a deterrent to quick reviews, and a little roadmap of the changes can help with that.

I updated the PR description. Sorry about that and thanks for the quick review 😄

**Review by avara1986 — APPROVED** [review]

**Pull request merged**
