### PR TITLE
Elasticsearch body value scrub setting for compliance

### PR DESCRIPTION
**Pull request by jheld**
I do expect that there will need to be fine-tuning and code added for config logic, but I wanted to get feedback on the core approach first. And of course, adding docs & tests.

We do need this for compliance reasons, but we understand some projects may not want their query bodies scrubbed, so I'm opting to make this a flag, instead.

### CODE REVIEW

**Comment by brettlangdon** [comment]
hey @jheld thanks for opening this PR!

There is actually Elasticsearch query obfuscation that happens in the trace agent:

Any span with type "elasticsearch", the `elasticsearch.body` JSON will get obfuscated.
https://github.com/DataDog/datadog-agent/blob/02b7ac3c2aeb73fe863179eacbb74c93342c4038/pkg/trace/obfuscate/obfuscate.go#L85-L107

This is the code that does the obfuscation:
https://github.com/DataDog/datadog-agent/blob/02b7ac3c2aeb73fe863179eacbb74c93342c4038/pkg/trace/obfuscate/json.go


Is something not working properly there?

**Comment by jheld** [comment]
Hi @brettlangdon oh yeah (at least for python) it's definitely not working. We actually put code very similar to this in our project first just to make sure that it was obfuscated.

**Comment by brettlangdon** [comment]
@jheld would you mind reaching out to support@datadoghq.com so we can investigate your account/the queries that are not being obfuscated.

I'd prefer to fix in our trace agent if we can since it will likely be easier to fix for more customers there.

Happy to keep this PR open for now though until we determine what the best approach to resolve is.

**Comment by jheld** [comment]
Hi @brettlangdon thank you so much for the link & insight.

Totally agree regarding the agent being the common ground for these where possible.

We'll be in touch with the support folks, and I appreciate you keeping the PR open for now.

At some point I will make sure CI is passing, should we need to merge this.

**Pull request closed without merging**
