### PR TITLE
feat(django): Add config for defining top-level resource name format (from PR 1415)

### PR DESCRIPTION
**Pull request by jheld**
This is for PR #1415  but with the commits rebased against master HEAD.

### CODE REVIEW

**Comment by Kyle-Verhoog** [comment]
thanks @jheld and @tredzko!

> @Kyle-Verhoog is the only blocker that this needs a rebase (or a fork of the change which does a rebase)? Tyler has since left our project, so although he may be able to update the code, there is no expectation of it and at the time we thought this was going to be merged in the short term. I'll be happy to update the code if it's just an out of date issue.

Yeah we want to get this in for the 0.40.0 release 🙂. We're going to look at it again very soon.

**Comment by jheld** [comment]
Seems we've missed another release. I don't know what the release cadence is but it would be helpful if that could be communicated because at this point I'm mostly just rebasing/keeping a clean tree.

**Comment by Kyle-Verhoog** [comment]
@jheld sorry for not posting an update sooner and thanks for staying on the ball with this! Unfortunately it didn't make it into 0.40. @majorgreys and I discussed the change a bit more and are leaning towards #1551 (based off of these changes), would love it if you could take a look and provide us your thoughts on that approach.

We're hesitant to pursue the approach here as it's really just a work around for poor defaults from the integration. Longer term we're planning on changing the resource name over to be consistent with the other web framework integrations where the resource is `<METHOD> <PATH>`.

**Comment by jheld** [comment]
Hi @Kyle-Verhoog I totally understand. Tyler and I had debated making an even more configurable solution (e.g. path to a user defined function to resolve the name). I think that would be a better approach in that the library, since it's allowed to change things, should allow the user application to have it's own implementation, should it wish to hook into that interface.

**Comment by Kyle-Verhoog** [comment]
@jheld we went ahead with #1551 which is based off the changes you and @tredzko made. Since we don't offer this level of configuration in other places we're going to hold off for now until we're more confident that there's a need for it. I've opened up a follow-up issue (#1596) so we don't lose this proposal.

**Pull request closed without merging**
