### PR TITLE
chore(trace_writer): removes _DD_TRACE_WRITER_ADDITIONAL_HEADERS

### PR DESCRIPTION
**Pull request by mabdinur**
## Description

_DD_TRACE_WRITER_ADDITIONAL_HEADERS is primarily used to correlate traces generated by a test to a "snapshot file". This is done by using the environment variable to set  `X-Datadog-Test-Session-Token` header to all trace chunks sent to the testagent. Snapshot tests already use [/test/session/clear?test_session_token](https://github.com/DataDog/dd-trace-py/blob/v2.4.0/tests/utils.py#L963) and [/test/session/start?test_session_token=....](https://github.com/DataDog/dd-trace-py/blob/v2.4.0/tests/utils.py#L1017) to manage test sessions.Since this configuration is NOT required and adds unnecessary complexity/overhead to submitting traces I think it is safe remove it.

## Motivation

This will significantly simplify our testagent configurations and make it easier to understand/debug/maintain. The tradeoff here is that snapshot tests can not be run in parallel. I think this is a reasonable tradeoff. 

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)
- [x] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [x] This PR doesn't touch any of that.

### CODE REVIEW

**Review by emmettbutler — APPROVED** [review]

**Review by majorgreys — COMMENTED** [review]
Why the content type and count changes?

**Comment by mabdinur** [comment]
> Why the content type and count changes?

It's a clean up. With the removal of _dd_trace_writer_additional_headers we don't need to define `_get_finalized_headers`

**Review by Yun-Kim — APPROVED** [review]
Looks good from MLObs!

**Comment by mabdinur** [comment]
Out of scope

**Pull request closed without merging**
