### PR TITLE
aiopg changes from #394

### PR DESCRIPTION
**Pull request by thehesiod**

### CODE REVIEW

**Comment by thehesiod** [comment]
`profile` failed which is unrelated to my changes

**Comment by thehesiod** [comment]
seems like this failure isn't my fault either

**Comment by brunobord** [comment]
too bad this PR is in conflict... is there anybody available here to help? the root cause is still here and it forces us to downgrade aiopg to a quite old version.

**Comment by thehesiod** [comment]
I'll try to take a look today

**Comment by brunobord** [comment]
mmmm... there's a failing check for the changelog step :(

**Pull request closed without merging**
