### PR TITLE
fix(profiling): fix potential deadlock after fork()

### PR DESCRIPTION
**Pull request by jd**
When a process fork, its threading.Lock (and anything based on it) must be
considered unusable since there's no way to know in which state they are.

The workflow after fork()ing is to stop the old-parent-profiler, and start a
new one in the child.

The problem is that stopping the old profiler in the child would use at least
two locks:

1. one from the Event in the Scheduler that is used to stop the thread. This is
   fixed by checking if the thread actually needs to be stopped — which isn't the
   case in the child.
2. if a child process would try to release a Lock before before the fork, it
   could hit a deadlock from the Recorder's lock:
   When theading.Lock is wrapped by the Lock profiler, there's a small chance
   that it'll write an Event in the old-parent-Recorder. If the process forked
   while this Recorder lock was held by another thread, then trying to release
   a lock locked before the fork would dead lock:

     Traceback (most recent call first):
     Waiting for the GIL
     File "/src/ddtrace/profiling/recorder.py", line 56, in push_events
       with self._events_lock:
     File "/src/ddtrace/profiling/recorder.py", line 44, in push_event
       return self.push_events([event])
     File "/src/ddtrace/profiling/collector/threading.py", line 126, in release
       sampling_pct=self._self_capture_sampler.capture_pct,
     File "tests/profiling/simple_program_fork.py", line 33, in <module>
       lock_acquired_in_the_parent.release()

### CODE REVIEW

**Review by Kyle-Verhoog — APPROVED** [review]

**Comment by jd** [comment]
Feel free to run it 10 times to check. So far locally I was not able to reproduce the bug 🥳

**Comment by Kyle-Verhoog** [comment]
@jd seems like a different test failed 😕

ERROR:   py37-profile-gevent: commands failed

```
_________________ test_memory_collector_ignore_profiler[False] _________________

ignore_profiler = False

    @pytest.mark.parametrize(
        "ignore_profiler", (True, False),
    )
    def test_memory_collector_ignore_profiler(ignore_profiler):
        r = recorder.Recorder()
        mc = memalloc.MemoryCollector(r, ignore_profiler=ignore_profiler)
        with mc:
            _allocate_1k()
            # Make sure we collect at least once
            mc.periodic()
    
        ok = False
        for event in r.events[memalloc.MemoryAllocSampleEvent]:
            for frame in event.frames:
                if ignore_profiler:
                    assert frame[0] != _periodic.__file__
                elif frame[0] == _periodic.__file__:
                    ok = True
    
        if not ignore_profiler:
>           assert ok
E           assert False

tests/profiling/collector/test_memalloc.py:185: AssertionError
```

**Comment by Kyle-Verhoog** [comment]
Re-running had it fail the same test for py38-profile-minreqs. Seems to be flaky from #1673

**Comment by jd** [comment]
Thanks @Kyle-Verhoog I'll take a look!

**Comment by Kyle-Verhoog** [comment]
Included in #1698

**Pull request closed without merging**
