### PR TITLE
grpc: drop support for versions before 1.17

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
## Description

Versions prior to 1.17 have known threading issues like
https://github.com/grpc/grpc/issues/18994 and are quite old. It's
becoming a pain to maintain them as they result in CI flakiness:

- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/5136/workflows/48189520-92fb-46c7-b1a4-26fb465dae58/jobs/482992
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/5160/workflows/925b4728-571c-44ab-b14b-f2f5d98f49d7/jobs/484844
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/5129/workflows/3383b1e1-ed00-43be-b28c-64406c1e2718/jobs/482435

## Checklist
- [x] Added to the correct milestone.
- [x] ~Tests provided or description of manual testing performed is included in the code or PR.~
- [x] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Comment by majorgreys** [comment]
It wasn't clear to me why 1.17 should be the cut-off from the linked grpc. Is there a specific changelog entry or is it just that the reported issue was with a version older than 1.17?

**Comment by Kyle-Verhoog** [comment]
Yes fair point. The reasoning for 1.17 is that it's old but not too old. It is an arbitrary choice though. We for sure know that 1.14 and 1.15 are troublesome so we could maybe start at 1.16.

**Comment by Kyle-Verhoog** [comment]
As we were discussing looks like 1.18 is offending too. https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/5211/workflows/0cf9930b-8626-4248-906c-34b5242c7311/jobs/488753

These do all seem to be in Python 2.7 however, so maybe worth dropping support for Python 2.7 and those versions

**Review by jd — APPROVED** [review]

**Comment by jd** [comment]
Agreed. If we can't test properly, we can't support properly so let's just make the matrix as it makes sense.

**Pull request closed without merging**
