### PR TITLE
chore(internal): replace ddtracerun fixture with subprocess decorator in integration tests

### PR DESCRIPTION
**Pull request by emmettbutler**
This updates some integration tests to use pytest's subprocess-based test harness rather than the homegrown `ddtrace_run_python_code_in_subprocess`. This reduces the cognitive load required to understand these tests and makes them easier to maintain.

These changes were pulled out from #4863 based on [this discussion](https://github.com/DataDog/dd-trace-py/pull/4863#discussion_r1094742095).

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) are followed.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.

### CODE REVIEW

**Comment by brettlangdon** [comment]
> use pytest.mark.subprocess instead of homegrown method

fun fact: `pytest.mark.subprocess` is also homegrown :)

https://github.com/DataDog/dd-trace-py/blob/15d77a35826ccf3817e4a89f7f6a2f405983284d/tests/conftest.py#L242

**Review by Yun-Kim — APPROVED** [review]
Love this change. I wonder if we really need `ddtrace_run_python_code_in_subprocess`, it seems quite complicated to understand and unnecessary considering we can just use `@pytest.mark.subprocess()`. As a future step, I'd be in favor of removing all instances of `ddtrace_run_python_code_in_subprocess` with this. 💪

**Comment by emmettbutler** [comment]
The changed tests are failing. @P403n1x87 I could use your input on why that might be before I dig in too deeply, since you're the actual author of this change.

**Comment by Yun-Kim** [comment]
Looks like the PR name is too long (for our pr-name checking job).

**Review by P403n1x87 — APPROVED** [review]

**Comment by P403n1x87** [comment]
> The changed tests are failing. @P403n1x87 I could use your input on why that might be before I dig in too deeply, since you're the actual author of this change.

Ah! I completely missed this message, but it looks like everything is sorted now? Thanks for taking care of this! 🙏

**Pull request merged**
