### PR TITLE
Use DEBUG log level for RateSampler initialization

### PR DESCRIPTION
**Pull request by bmurphey**
In reference to [this issue](https://github.com/DataDog/dd-trace-py/issues/860).

This way these logs can be seen when debugging is turned on, but otherwise left out.

### CODE REVIEW

**Comment by bmurphey** [comment]
I've never used tox before, but the `celery` test that's failing appears to be when trying to test Celery 4.2 with Kombu 4.4.  However, Celery 4.2 [appears to limit Kombu](https://github.com/celery/celery/blob/4.2/requirements/default.txt) to `>=4.2.0,<4.4`.  I ran the test locally and got the same issue; then I ran virtually the same test but with Kombu 4.3:

```
tox -e 'celery_contrib-py27-celery42-redis320-kombu43'
```

That fails the `tests/contrib/celery/test_autopatch.py` test.  So, I'm not sure what I should do at this point.

**Comment by jd** [comment]
@bmurphey This has been fixed with https://github.com/DataDog/dd-trace-py/pull/858 but it's only in 0.24-dev branch. You should rebase and target this branch AFAIU.

**Comment by bmurphey** [comment]
Now it's got a `tornado` test failure in CI, but it works locally (in Docker) with:

`tox -e 'tornado_contrib-py34-tornado45'`.  Unfortunately I don't have permissions (understandably) to try to re-run the test to see if it's just flaky.

**Comment by jd** [comment]
There's a `sleep` call in the test that fails, so you can bet it's a flaky test. I've re-ran it.

**Comment by bmurphey** [comment]
@jd It looks like the test failed again; not sure what I should do here?

**Comment by jd** [comment]
I've switched the target branch to `0.24-dev` and updated this PR with the latest commits, let's see.

**Comment by jd** [comment]
Yes that's https://github.com/DataDog/dd-trace-py/issues/859 — I've reran the failed job.

**Comment by brettlangdon** [comment]
Fixes #860

**Pull request merged**
