### PR TITLE
feat(pytest): add option to disable ddtrace plugin

### PR DESCRIPTION
**Pull request by gnufede**
Pytest: Add option to disable the ddtrace plugin, to override the setup.cfg file setting if present.

## Checklist
- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by romainkomorndatadog — APPROVED** [review]
Makes sense to me but I think maybe we should update the contributing docs on running tests for non-employees because not having a `DD_API_KEY` set is fatal in agentless mode.
```
INTERNALERROR> OSError: DD_CIVISIBILITY_AGENTLESS_ENABLED is set, but DD_API_KEY is not set, so ddtrace cannot be initialized.
```
Although I'm not sure if they'd be running tests with a local agent running.

**Review by emmettbutler — DISMISSED** [review]

**Comment by gnufede** [comment]
> Makes sense to me but I think maybe we should update the contributing docs on running tests for non-employees because not having a `DD_API_KEY` set is fatal in agentless mode.
> 
> ```
> INTERNALERROR> OSError: DD_CIVISIBILITY_AGENTLESS_ENABLED is set, but DD_API_KEY is not set, so ddtrace cannot be initialized.
> ```
> 
> Although I'm not sure if they'd be running tests with a local agent running.

In my opinion this would be needed if the `--ddtrace` option was added to the `setup.cfg` in our project, but that is not the current approach.

**Comment by romainkomorndatadog** [comment]
> In my opinion this would be needed if the `--ddtrace` option was added to the `setup.cfg` in our project, but that is not the current approach.

Sorry, I thought we were adding it to `riot`, but maybe that's changed since I last saw that code. :)

**Comment by gnufede** [comment]
> Sorry, I thought we were adding it to riot, but maybe that's changed since I last saw that code. :)

No problem! The approach now is to add `--ddtrace` only in the CI, and add `--no-ddtrace` in the riotfile to override for the test suites that interfere with the `--ddtrace` option

**Review by romainkomorndatadog — APPROVED** [review]

**Pull request merged**
