### PR TITLE
Add uds_path to ddtrace.opentracer.Tracer

### LINKED ISSUE #1274: Add uds_path to ddtrace.opentracer.Tracer
### Which version of dd-trace-py are you using?
0.33.0 ?

### Which version of the libraries are you using?
0.33.0

### How can we reproduce your problem?
Try setting `uds_path` when creating a `ddtrace.opentracer.Tracer`. Oh wait.

### What is the result that you get?
This nastiness:
```
ddtracer = Tracer('appname', config={'agent_hostname': None, 'agent_port': None})
set_global_tracer(ddtracer)
tracer.configure(uds_path='/path/to/datadog.sock')
```

### What is result that you expected?
This beauty:
```
ddtracer = Tracer('appname', config={'agent_hostname': None, 'agent_port': None, 'uds_path': '/path/to/datadog.sock'})
set_global_tracer(ddtracer)
```
It is not clear from the documentation how to set up the tracer here, if using unix domain sockets but not using `ddtrace-run`.

I'm only filing to set up a PR real quick. Feel free to decline both if these are irrelevant.

### PR DESCRIPTION
**Pull request by worldwise001**
Fixes #1274

### CODE REVIEW

**Comment by brettlangdon** [comment]
also need to add the key here: https://github.com/DataDog/dd-trace-py/blob/3f8970e17e62fd81e916c14a0b5f5f70c2107036/ddtrace/opentracer/settings.py#L4

**Comment by worldwise001** [comment]
ok, updated!

**Comment by worldwise001** [comment]
ugh, there's a bad commit in this list, one sec.

**Comment by worldwise001** [comment]
Fixed.

**Comment by worldwise001** [comment]
Looks like one of you will need to merge. :)

**Comment by Kyle-Verhoog** [comment]
Ah yes, the CI job was stalled for quite a bit. 🙂

**Pull request merged**
