### PR TITLE
fix: avoid importing asyncio (#6037) [backport 1.13]

### PR DESCRIPTION
**Pull request by emmettbutler**
Whilst the library has many integrations and features relying on asyncio, the actual products don't make use of it. The interaction is only aimed at providing observability into Python's native async support. We then avoid importing from asyncio and rely only on import hooks to achieve our goals. This prevents the asyncio module from being loaded, which also means that we no longer need to unload it as part of the better support for frameworks such as gevent.

(cherry picked from commit 6a23f3c8f6e1f8fd8050853f3d908f033bc1fa40)

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) are followed.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if [applicable](../docs/contributing.rst#release-branch-maintenance))

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](../docs/contributing.rst#release-branch-maintenance)

### CODE REVIEW

**Comment by emmettbutler** [comment]
https://github.com/DataDog/dd-trace-py/pull/6142

**Review by mabdinur — DISMISSED** [review]

**Comment by mabdinur** [comment]
This backport builds on a change that does not exit on the 1.13 branch (https://github.com/DataDog/dd-trace-py/pull/5732). I reordered the commits to include this change.

**Review by mabdinur — DISMISSED** [review]

**Review by mabdinur — APPROVED** [review]
`test_multiprocessing[forkserver]` is extremely flaky: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/38701/workflows/f5713936-6594-4d16-8a3d-7cff3c1c0c15/jobs/2606963. 

This test is also failing on the 1.13, 1.14, and 1.15 backports

**Review by mabdinur — APPROVED** [review]

**Review by majorgreys — APPROVED** [review]

**Comment by majorgreys** [comment]
1.13 is no longer maintained.

**Pull request closed without merging**
