### PR TITLE
chore(asm): add a ctypes based ddprof module

### PR DESCRIPTION
**Pull request by juanjux**
Add a small and private ctypes-based `_ddprof` module and a script to download the `.so` binary (including it is not an option since it's 17mb) to ease using ddprof start and stop functions to profile specific parts of the tracer. 

Signed-off-by: Juanjo Alvarez <juanjo.alvarezmartinez@datadoghq.com>## Checklist
- [X] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by gnufede — APPROVED** [review]
Looks good, maybe you can add some example script that calls `start_profiling` and `stop_profiling` to showcase the usage

**Comment by taegyunkim** [comment]
Should it be used as the following?

```
from ddtrace.appsec._ddprof import ddprof

ddprof.ddprof_start_profiling()
# run something interesting to be profiled here
# probably using native extensions
ddprof.ddprof_top_profiling()
```

**Comment by juanjux** [comment]
> Should it be used as the following?
> 
> ```
> from ddtrace.appsec._ddprof import ddprof
> 
> ddprof.ddprof_start_profiling()
> # run something interesting to be profiled here
> # probably using native extensions
> ddprof.ddprof_stop_profiling()
> ```

That's right (stop profiling has a parameter for the timeout to wait in milliseconds). There is not much complication on it.

**Review by sanchda — APPROVED** [review]
This is exactly why we build libdd_profiling.so and it's really exciting to see it used!

**Review by avara1986 — APPROVED** [review]

**Review by emmettbutler — APPROVED** [review]

**Pull request closed without merging**
