### PR TITLE
ci: add azure and chrome to testrunner image

### PR DESCRIPTION
**Pull request by duncanpharvey**
This updates the `testrunner` image to:
- Install `azure-functions-core-tools-4` for serverless use
- Install `google-chrome` to support the Selenium integration's tests

Additionally, it fixes the install process for MariaDB which was breaking `apt` usage due to outdated behavior from `mariadb_repo_setup`:

```
...
   && ./mariadb_repo_setup   && apt-get install -y --no-install-recommends libmariadb-dev libmariadb-dev-compat   && rm mariadb_repo_setup   && rm -rf /var/lib/apt/lists/*:
#10 108.7 Err:1 https://dlm.mariadb.com/repo/mariadb-server/11.rolling/repo/debian buster/main amd64 mysql-common all 1:11.5.2+maria~deb10
#10 108.7   404  Not Found [IP: 104.17.191.14 443]
#10 108.9 Err:2 https://dlm.mariadb.com/repo/mariadb-server/11.rolling/repo/debian buster/main amd64 mariadb-common all 1:11.5.2+maria~deb10
#10 108.9   404  Not Found [IP: 104.17.191.14 443]
#10 108.9 E: Failed to fetch https://dlm.mariadb.com/repo/mariadb-server/11.rolling/repo/debian/pool/main/m/mariadb/mysql-common_11.5.2+maria~deb10_all.deb  404  Not Found [IP: 104.17.191.14 443]
...
```

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by romainkomorndatadog — APPROVED** [review]

**Comment by romainkomorndatadog** [comment]
You'll also want to update the GitLab images (eg: something similar to https://github.com/DataDog/dd-trace-py/commit/75fb5134edd671bff3de0852616b0d2f6d1599c7) and then we'll need to get the image published in our images repo (like https://github.com/DataDog/images/pull/5746 ).

@brettlangdon , I know you said it'd be good to do this in a separate PR, but now I've got https://github.com/DataDog/dd-trace-py/pull/11610 coming up and making updates in multiple places, plus rebasing, adds a lot of overhead.

**Comment by romainkomorndatadog** [comment]
Running a test build: https://github.com/DataDog/dd-trace-py/actions/runs/12142201068 .

**Comment by romainkomorndatadog** [comment]
Running some tests with `ghcr.io/datadog/dd-trace-py/testrunner:0c2f350d1526294eb6a7b782967698dbcbfb2548` .

Looks like things are installed properly:
```
azure-functions-core-tools-4/now 4.0.6280-1 amd64 [installed,local]
...
google-chrome-stable/now 131.0.6778.85-1 amd64 [installed,local]
...
libmariadb-dev-compat/now 1:11.5.2+maria~deb10 amd64 [installed,local]
libmariadb-dev/now 1:11.5.2+maria~deb10 amd64 [installed,local]
libmariadb3/now 1:11.5.2+maria~deb10 amd64 [installed,local]
mariadb-common/now 1:11.5.2+maria~deb10 all [installed,local]
mysql-common/now 1:11.5.2+maria~deb10 all [installed,local]
```
My tests from #11610 also pass locally, so from my perspective we should be able to merge this.

@duncanpharvey , it'd be great if you could verify the image looks good to you as well. :)

**Comment by romainkomorndatadog** [comment]
I guess it's worth noting that the image size has increased quite a bit as a result:
```
➜  dd-trace-py git:(romain.komorn/SDTEST-142/support_selenium_in_test_visibility) ✗ docker images
REPOSITORY                                           TAG                                        IMAGE ID       CREATED        SIZE
ghcr.io/datadog/dd-trace-py/testrunner               0c2f350d1526294eb6a7b782967698dbcbfb2548   f7d6bec7f5d7   21 hours ago   5.11GB
ghcr.io/datadog/dd-trace-py/testrunner               <none>                                     69975d4fbe78   43 hours ago   4.55GB
ghcr.io/datadog/dd-trace-py/testrunner               <none>                                     7c152587ef6a   2 months ago   3.96GB
```
I'm not sure how we'd get around that given that `google-chrome-stable` just has ✨ dependencies ✨.

**Review by romainkomorndatadog — APPROVED** [review]

**Review by brettlangdon — APPROVED** [review]

**Pull request merged**
