### PR TITLE
fix(tracing): fix traceback max size for exceptions

### PR DESCRIPTION
**Pull request by quiqueg**
https://github.com/DataDog/dd-trace-py/pull/7558 made the traceback size configurable via `DD_TRACE_SPAN_TRACEBACK_MAX_SIZE`, but tracebacks for exceptions were still hardcoded with a limit of 30.

The fix is modeled after `Span#set_traceback`'s existing logic, and tests were modeled after both `test_traceback_with_error` and `test_custom_traceback_size`. Not much new logic, just an edge case.

## Checklist

- [x] Change(s) are motivated and described in the PR description
- [x] Testing strategy is described if automated tests are not included in the PR
- [x] Risks are described (performance impact, potential for breakage, maintainability)
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed or label `changelog/no-changelog` is set
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/))
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))
- [x] If this PR changes the public interface, I've notified `@DataDog/apm-tees`.

## Reviewer Checklist

- [x] Title is accurate
- [x] All changes are related to the pull request's stated goal
- [x] Description motivates each change
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- [x] Testing strategy adequately addresses listed risks
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] Release note makes sense to a user of the library
- [x] Author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by erikayasuda — APPROVED** [review]

**Comment by quiqueg** [comment]
@erikayasuda Did you have any comments on the release note? I noticed that you left `Release note makes sense to a user of the library` unchecked in the reviewer checklist.

**Comment by quiqueg** [comment]
@erikayasuda This PR should be good to go. It looks like just the `Library Injection / build-and-publish-test-image / build_push / build_push` CI job is failing with a docker push 403 Unauthorized error. I'm not familiar with this project's CI setup, but it might be because my fork (as an outside contributor) doesn't have access to the `secrets.GITHUB_TOKEN`?

I don't have merge permissions in this repo, so please feel free to take over and merge when you have a chance to do so. Thank you!

**Comment by erikayasuda** [comment]
Hi @quiqueg , sorry for the slow cycles here. I just updated the branch, and enabled auto-merge, so that should merge today assuming the tests all go well. Thanks for the patience!

**Comment by quiqueg** [comment]
@erikayasuda Looks like the `Library Injection / build-and-publish-test-image / build_push / build_push` test is still failing with the same 403 Unauthorized error that I mentioned above. Could you please take a look?

**Pull request merged**
