### PR TITLE
perf(settings): Avoid get_env when copying IntegrationConfig

### PR DESCRIPTION
**Pull request by P403n1x87**
## Description

Avoid unnecessary work when creating a copy of an `IntegrationConfig` object. This avoids calls to `get_env` on hot paths. Relates to #2080 and #2093.

⚠️  **This PR will likely change to a removal of the `copy` and `deepcopy` methods for clean-up.**

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Comment by majorgreys** [comment]
While we use this only internally, I wonder if the better interface here is one that allows us to override the atttributes:

```python
    def __deepcopy__(self, memodict=None):
        return IntegrationConfig(
            self.global_config,
            self.integration_name,
            deepcopy(dict(self), memodict),
            hooks=deepcopy(self.hooks, memodict),
            http=deepcopy(self.http, memodict),
        )
```

**Comment by P403n1x87** [comment]
Should this PR be closed in favour of either of the linked PRs?

**Comment by majorgreys** [comment]
I think this PR is still relevant as we don't want `deepcopy/copy` to incur this unnecessary cost.  However it does not appear that other than the case of `dbapi` do we end up calling `copy()`. Can we safely remove them once #2093 is merged?

**Comment by P403n1x87** [comment]
> We don't want `deepcopy/copy` to incur this unnecessary cost. However it does not appear that other than the case of `dbapi` do we end up calling `copy()`. Can we safely remove them once #2093 is merged?

I think once #2093 is merged, `copy()` won't be on a hot path anymore. This PR would still improve things, but the performance gain would only be marginal.

**Comment by majorgreys** [comment]
Do we still need these functions?

**Comment by P403n1x87** [comment]
> Do we still need these functions?

Sorry I didn't actually answer your original question 😊 . I think the methods won't be needed as I understand they were added just to address the problem that is being resolved by #2093.

**Comment by P403n1x87** [comment]
The actual performance issue has been resolved by #2358.

**Pull request closed without merging**
