### PR TITLE
[Tracking] asyncio enhancements

### PR DESCRIPTION
**Pull request by thehesiod**
a variety of features and enhancements to ddtrace.  I'm keeping this open until all the other PRs are resolved.

- asyncpg contrib module: https://github.com/DataDog/dd-trace-py/pull/394
- aiohttp client tracing support and bugfixes: https://github.com/DataDog/dd-trace-py/pull/294
~~- fix service papagation: https://github.com/DataDog/dd-trace-py/pull/400~~
- aiohttp client + aiopg/asyncpg service name tweaks
- aiohttp `enable_distributed` override support
- swap from msgpack fix to https://github.com/DataDog/dd-trace-py/pull/1638

### CODE REVIEW

**Comment by thehesiod** [comment]
the integration failure doesn't seem to be my issue

**Comment by thehesiod** [comment]
this last failure: https://circleci.com/workflow-run/867c9047-0a00-4c1e-8548-2cae75263931 doesn't seem to be my fault, integration failed and I didn't change anything related to it

**Comment by labbati** [comment]
Hi @thehesiod, 'integrations' job is flaky and we are aware of it, we will address it as soon as we can. In the meantime I re-run the job which is green now: https://circleci.com/workflow-run/1b0634e6-5119-4651-941f-eba165c50673

**Comment by jd** [comment]
Could this be split in smaller pull requests? It's getting extremely hard to review at this point.

**Comment by thehesiod** [comment]
this PR is not meant to be reviewed, it's just all my PRs in one, here so I know when all the other PRs have been merged so nothing gets lost.  If it's too noisy I can close.

**Comment by thehesiod** [comment]
I've merged in v0.34.0, however it seems the psycopg tracing has changed quite a bit so that's probably not working right, I'll go over that bit tomorrow

**Comment by Kyle-Verhoog** [comment]
Hi @thehesiod!

Thank you so much for bearing with us and for your work. Traction is finally here! We've got some more people power on the project and we want to work with you to get your contributions (I think pretty much everything you've referenced in #398) in. 

I'm pushing your work to develop branches in the repo that we can work together on. I'm going to get the branches back up to date in the process. Then we can PR into the develop branches together. Let me know how this sounds. 🙂

I've got some ramping up to do with the PRs as well as all this async stuff, so bear with me along the way. I'm also happy to synchronize/coordinate in our public slack too, if that works with you. We could get an async python channel up and running over there.

**Comment by thehesiod** [comment]
@Kyle-Verhoog sounds good.  Hopefully soon I can get back to these to get them all passing again

**Comment by zhammer** [comment]
glad to see progress on the aiohttp work continuing! does anyone know off hand if aiohttp client tracing (#294) will automatically set up tracing for aioredis? it seems from the aiohttp docs that [aioredis is built on top of aiohttp](https://docs.aiohttp.org/en/stable/third_party.html#database-drivers)

i'm guessing not. if that's the case, i'm curious if this aiohttp work would pave the way for a fairly straightforward aioredis patch

**Comment by Kyle-Verhoog** [comment]
all the referenced PRs have been resolved so I think we can close this tracking PR. The one remaining is aiopg but there is #973 for that

**Pull request closed without merging**
