### PR TITLE
ci: remove tox/riot from docker image

### PR DESCRIPTION
**Pull request by majorgreys**
## Description

In light of issues with maintaining the ci image we use for running tests in a Docker container, this PR removes riot and tox from our Dockerfile. This avoids the problem of pinning or upgrading these packages as they are updated. Also, if we down the line want to pin, we pin them in the setup ci jobs rather than having to first push a change with the updated pinned version in the Dockerfile. The `scripts/ddtest` has already been updated in #1828 to silently install these packages before executing a command.

## Checklist
- [ ] Entry added to release notes using [reno](https://docs.openstack.org/reno/latest/user/usage.html)
- [ ] Tests provided; and/or
- [ ] Description of manual testing performed and explanation is included in the code and/or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Comment by brettlangdon** [comment]
Anything wrong with keeping this?

Or having it pin a lower bound based on compatibility with the `riotfile.py` syntax?

e.g. `pip install riot>=0.3.0`, and then if we want to explicitly upgrade/reinstall in CI that is cool too?

Just thinking of a case where we use this image locally (does anyone else do that?) then we have to remember to install `riot`. Better to have an older version that supports the right `riotfile.py` syntax vs not having it at all?

**Review by jd — APPROVED** [review]
I think this is the safer bet so we don't run into other issue of stalled packages.

The alternative is to build+push with CircleCI the Docker image when this file changes and use it in the CI (otherwise relying on the existing long-term cached image). Not sure it's worth the trouble?

**Comment by brettlangdon** [comment]
> The alternative is to build+push with CircleCI the Docker image when this file changes and use it in the CI (otherwise relying on the existing long-term cached image). Not sure it's worth the trouble?

Yeah, not sure. Not a bad idea, but given the frequency of issues, maybe not worth it?

**Comment by majorgreys** [comment]
> Just thinking of a case where we use this image locally (does anyone else do that?) then we have to remember to install `riot`. Better to have an older version that supports the right `riotfile.py` syntax vs not having it at all?

@brettlangdon  The `scripts/ddtest` will install these packages before running a command. While this adds time to the local dev use case, it saves us having to maintain it in CI.

> The alternative is to build+push with CircleCI the Docker image when this file changes and use it in the CI (otherwise relying on the existing long-term cached image). Not sure it's worth the trouble?

I think this point by @jd makes the strongest case for why having this in the image is more trouble than it might be worth. In the scenario where we are upgrading to riot 0.3.0 with a breaking change, we are having to upgrade the version of riot installed in the Docker image that is current. It's not that we couldn't make this work but it would require more changes to CI. As it is, we can just make sure to install tox/riot in CI jobs.

> Or having it pin a lower bound based on compatibility with the riotfile.py syntax?

@brettlangdon I think adding a pin, whether in the CI jobs or the Dockerfile if we wanted to stick to that, might make sense down the road. The benefit to keeping up to date, at least for riot, is that we'll have to act faster to make fixes to riot as needed. Though we'd have the option to pin if there is a breaking change that we can't easily resolve.

**Review by brettlangdon — APPROVED** [review]

**Pull request merged**
