### PR TITLE
core: move filters from writers to tracer

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
## Description
This cleans up the design and prevents potentially filtered traces from
being counted towards the trace queue limit.

Filtering being done in the writers was probably done as an attempt at
optimization given that they'd run in the thread (presumably in parallel
to the main application code) however due to the GIL python code is only
ever run once.

## Checklist
- [x] ~~Entry added to release notes using [reno](https://docs.openstack.org/reno/latest/user/usage.html)~~
- [x] Tests provided; and/or
- [x] Description of manual testing performed and explanation is included in the code and/or PR.
- [x] ~~Library documentation is updated.~~
- [x] ~~[Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).~~

### CODE REVIEW

**Review by brettlangdon — COMMENTED** [review]
we should probably keep filters in both place, just change where the `tracer.configure(filters=[])` go.

thinking about a case if someone does `tracer.configure(writer=LogWriter(filters=[]))`

what do you think?

**Comment by Kyle-Verhoog** [comment]
😩 we put LogWriter and AgentWriter in the `internal` module for a reason. I'll check with the agentless team to see if they permit this kind of usage.

**Comment by brettlangdon** [comment]
ah, I am blind. then ignore me. if it is in `internal` already, then should be clear/not fully bound by the public API

**Comment by Kyle-Verhoog** [comment]
We don't mention this kind of usage anywhere in our docs so I'll just make sure the agentless team isn't doing anything with filters.

**Comment by Kyle-Verhoog** [comment]
https://github.com/DataDog/datadog-lambda-python is not using filters as an argument to the LogWriter so we should be good to go

**Review by brettlangdon — APPROVED** [review]

**Pull request merged**
