### PR TITLE
refactor(worker): replace regular thread by PeriodicThread

### PR DESCRIPTION
**Pull request by jd**

### CODE REVIEW

**Review by P403n1x87 — APPROVED** [review]

**Review by brettlangdon — APPROVED** [review]

**Comment by Kyle-Verhoog** [comment]
```
  File "/root/project/ddtrace/internal/nogevent.py", line 23, in <module>
    is_module_patched = gevent.monkey.is_module_patched
AttributeError: 'module' object has no attribute 'is_module_patched'
```

for Python 2 + gevent 1.0

**Comment by jd** [comment]
The profiler support gevent 1.1.0 minimum. Since 1.1.0 has been released 5 years ago, I think it's fine to bump the dep…

**Comment by Kyle-Verhoog** [comment]
Yup, agreed!

**Comment by jd** [comment]
This seems to break the profiler for an unknown reason. Digging.

**Comment by jd** [comment]
The problem is with gevent monkey patch being called after ddtrace is imported. Why ddtrace is imported by `python -m tests.profiling.run`. I don't know yet 🤔

**Comment by jd** [comment]
Ok there's code in `tests/__init__.py`. We shouldn't do that. 🤦

**Comment by Kyle-Verhoog** [comment]
@jd should we move most of those utils to `tests/tracer/__init__.py` I think almost all of them are tracer specific in there? I can take this on if need-be

**Comment by jd** [comment]
I think it triggered an issue in nogevent which I want to fix. I'll see.

**Comment by jd** [comment]
Fix should be in https://github.com/DataDog/dd-trace-py/pull/2215

**Comment by jd** [comment]
#2215 can't work and we need https://github.com/DataDog/dd-trace-py/pull/2217

**Pull request merged**
