### PR TITLE
feat(flask): store response headers

### PR DESCRIPTION
**Pull request by Isabella-Pham**
## Description
Store response headers in the flask integration using the new http helper function.

### CODE REVIEW

**Review by Kyle-Verhoog — COMMENTED** [review]
I don't see response headers being stored 🤔 maybe a copy paste thing?

**Comment by Isabella-Pham** [comment]
> I don't see response headers being stored 🤔 maybe a copy paste thing?

**Review by Kyle-Verhoog — APPROVED** [review]

**Comment by rslinckx** [comment]
It seems this patch and the previous one regarding the request headers have been added to the TraceMiddleware class (which seems to be deprecated), but not the patch-based instrumentation. Was that on purpose ?

Currently, the headers are not sent at all for a regularly patched flask application (ddtrace-run), it seems

**Comment by majorgreys** [comment]
@rslinckx Thank you for pointing this out. We had put this work off until we had merged #1860. I have started the changes in #1920 for patched flask applications.

**Pull request merged**
