### PR TITLE
Fixes exception with None checking request headers

### PR DESCRIPTION
**Pull request by pvicente**
Fixes https://github.com/DataDog/dd-trace-py/issues/6284

## Checklist

- [X] Change(s) are motivated and described in the PR description.
- [X] Testing strategy is described if automated tests are not included in the PR.
- [X] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [X] Change is maintainable (easy to change, telemetry, documentation).
- [X] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [X] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [X] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [ ] Title is accurate.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Testing strategy adequately addresses listed risk(s).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] Release note makes sense to a user of the library.
- [ ] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [ ] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Comment by brettlangdon** [comment]
@pvicente thanks for opening this PR. Would you be willing to add a regression test?

It is unclear to me when we would have `None` as the key for that function. We might want to try and solve it from the caller since the typing we have here is `Mapping[str, str]` and that apparently is not being honored by something.

**Comment by pvicente** [comment]
> @pvicente thanks for opening this PR. Would you be willing to add a regression test?
> 
> It is unclear to me when we would have `None` as the key for that function. We might want to try and solve it from the caller since the typing we have here is `Mapping[str, str]` and that apparently is not being honored by something.

Hi @brettlangdon, could you guide me where to add this regression test please? I'm not sure if I can resolve it from caller if you see the issue I've got proof of the headers:

```
_get_request_header_client_ip headers '{None: 'on', 'Cloudfront-Forwarded-Proto': 'https', 'Cloudfront-Is-Desktop-Viewer': 'true', 'Cloudfront-Is-Mobile-Viewer': 'false', 'Cloudfront-Is-Smarttv-Viewer': 'false', 'Cloudfront-Is-Tablet-Viewer': 'false', 'Cloudfront-Viewer-Asn': '14618', 'Cloudfront-Viewer-Country': 'US', 'Host': 'jinwg5ftte.execute-api.eu-west-1.amazonaws.com', 'User-Agent': 'Amazon CloudFront', 'Via': '2.0 f03ced384777449538f7af55da0e2760.cloudfront.net (CloudFront), 1.1 25d9b5959eaa82bb18ee3f35e6bf34b4.cloudfront.net (CloudFront)', 'X-Amz-Cf-Id': 'zRaWn4lMDcLCDMitFQOvDbI21NG05tX7GXPy945ErtZ5urhw6qE3ew==', 'X-Amzn-Trace-Id': 'Root=1-64a697a9-2ebc14ef1aac805a55743f31', 'X-Forwarded-For': '20.83.144.189, 64.252.68.152, 15.158.50.11', 'X-Forwarded-Port': '443', 'X-Forwarded-Proto': 'https', 'X-Request-Id': 'e4af75fb-32d3-4525-b03a-44738c534da0'}'
```

See first one `None: 'on',` is the one and comes from `appsec.processor.py`

**Comment by brettlangdon** [comment]
@pvicente I hope you don't mind, I opened up #6290 which introduces a fix for the root cause of the issue in our WSGI integration.

Let me know if you think this PR accurately represents the issue you are seeing / should resolve the issue you are seeing.

**Comment by pvicente** [comment]
> @pvicente I hope you don't mind, I opened up #6290 which introduces a fix for the root cause of the issue in our WSGI integration.
> 
> Let me know if you think this PR accurately represents the issue you are seeing / should resolve the issue you are seeing.

@brettlangdon Looks like it's accurate, I'll test it in my env when it's released. Thanks

**Pull request closed without merging**
