### PR TITLE
fix(profiling): don't build _memalloc extension when using Pyston

### PR DESCRIPTION
**Pull request by undingen**
I'm one of the developers of [Pyston](https://github.com/pyston/pyston) an alternative Python implementation.
Recently a user reported that he can't install ddtrace (it failed while building the `_memalloc` extension). With the following patch I was able to install it.
Unfortunately I could not run the testsuite because it also does not support Pyston / could not figure out how to run it successful against Pyston :/.
Maybe it's possible to get this patch in to at least make it possible to install it.

The problem is that while Pyston is a fork of CPython 3.8.12 we try to be fully compatible with it
except a few debugging features and one of it is unfortunately is not supporting the `PyMemAllocator` API.

### CODE REVIEW

**Review by jd — DISMISSED** [review]
Fine with me. We don't test it in the CI though, so it might break in the future 🤞

**Review by brettlangdon — DISMISSED** [review]

**Comment by brettlangdon** [comment]
@undingen would you be willing to add a release note to this PR?

```
pip install -U reno
reno new fix-pyston-memalloc
```

This would be a "fixes" note

**Comment by brettlangdon** [comment]
@Mergifyio backport 1.0 0.x 0.60

**Comment by undingen** [comment]
Thanks.
I have created a new commit with the release document. I was not sure if I should squash it into my first commit so I left it independent and I guess you can squash it when merging on github.

**Review by brettlangdon — DISMISSED** [review]

**Review by Kyle-Verhoog — DISMISSED** [review]

**Review by Kyle-Verhoog — APPROVED** [review]

**Review by brettlangdon — DISMISSED** [review]

**Review by Kyle-Verhoog — APPROVED** [review]

**Review by brettlangdon — APPROVED** [review]

**Pull request merged**
