### PR TITLE
Resolve keyerror in Django traced_get_response

### PR DESCRIPTION
**Pull request by SzySteve**
## Description
In some edge cases (preview mode in wagtail CMS for instance) the request meta object does not contain a query string attribute, so access it safely with a dictionary get rather than killing the request

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Comment by majorgreys** [comment]
Thanks @SzySteve! It'd be great to add a test case to cover this or steps for manual testing. What do you think?

**Comment by SzySteve** [comment]
@majorgreys I am having trouble launching the `docker-compose` stack (seems more than one container is trying to use port 8126) to run tests at the moment

**Comment by Kyle-Verhoog** [comment]
IMO the change is pretty straightforward and doesn't need a regression test. It would be good to have a changelog entry though @SzySteve. This can be done with `reno` (`pip install reno`) and then `reno new django-key-error`.

**Review by Kyle-Verhoog — APPROVED** [review]

**Comment by Kyle-Verhoog** [comment]
Thanks @SzySteve!

**Pull request merged**
