### PR TITLE
allow user-specified site customize directory

### LINKED ISSUE #1344: feature proposal: user sitecustomization.py directory env var
hey ddtrace team. i've been thinking that a clean way to add some custom setup across all our python apps would be to add a `sitecustomize.py` that'd be called by `ddtrace-run` in the following codeblock:
https://github.com/DataDog/dd-trace-py/blob/872a8880e942bf76296b83c703ca00a7e3c3eded/ddtrace/bootstrap/sitecustomize.py#L124-L141

there are a few issues with this:
1. we'd need to update `PYTHONPATH` to point somewhere in our app code directory for `sitecustomize.py` to be part of `sys.path`
    * (some of our jobs have `PYTHONPATH=.` but not all)
2. if `PYTHONPATH=.` and `./sitecustomize.py` exists, `./sitecustomize.py` will run both when `ddtrace-run` runs before [os.exec](https://github.com/DataDog/dd-trace-py/blob/872a8880e942bf76296b83c703ca00a7e3c3eded/ddtrace/commands/ddtrace_run.py#L69)ing *and* in the bootstrapped python app

i'm thinking it may be nice to have a `DD_USER_SITECUSTOMIZATION_DIR` env var that, if present, would be where `ddtrace-run` looks for a user `sitecustomization`. e.g. `DD_USER_SITECUSTOMIZATION_DIR=./datadog_config/`

curious what folks think of this. if you don't want to mess with sitecustomization, is there anything on the roadmap to add setup hooks to `ddtrace-run`?

### PR DESCRIPTION
**Pull request by zhammer**
resolves #1344

this has been working pretty well for us on some tests in our staging environment. as per @majorgreys's comment on #1344, i'm putting up this light implementation as a start. i'm happy to help add some testing / documentation as well! let me know what y'all are thinking

### CODE REVIEW

**Comment by jd** [comment]
I think we should try to keep things more transparent rather than adding one more settings. This works at least for Python 3:

```python
$ cat sitecustomize.py
import os.path
import sys
import importlib

print("first sitecustomize imported")
filedir = os.path.dirname(os.path.abspath(__file__))

sys.path.remove(filedir)

importlib.reload(sys.modules["sitecustomize"])

$ cat user/sitecustomize.py
print("second sitecustomize imported")

$ PYTHONPATH=.:user python3 -c 'print("END")'
first sitecustomize imported
second sitecustomize imported
END
```

Not sure how to solve this for Python 2 yet.

**Comment by zhammer** [comment]
@jd i think you can clean up the 2/3 stuff with ddtrace's own compat [reload_module](https://github.com/DataDog/dd-trace-py/blob/0b8435fee1e76d973df842c44f8296fa8190d317/ddtrace/compat.py#L39) :)

i will say that for our use-case we're mainly interested in having some sort of post `ddtrace-run` pre app-code init script, e.g. `DATADOG_POST_DDTRACE_RUN=ddtracecustomize/our_init.py`. an overridable sitecustomize seemed like the quickest way to set this up.

let me try out your change. my hunch is that adding an extra env var (`DATADOG_USER_SITECUSTOMIZATION_DIR`) would actually be simpler / less risky to our production services than updating our `PYTHONPATH` across the board but will try it out.

**Comment by jd** [comment]
Understood, though I'd prefer to have something really transparent so you don't have to change your code just because you use the wrapper.
Let me know how that works for you!

(Not sure we can use `reload_module` at this stage of loading? Maybe? Cool if we can.)

**Comment by zhammer** [comment]
ah wait, i may be missing something, but can you give an example of how this logic would be added to [ddtrace-run's sitecustomize.py](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/bootstrap/sitecustomize.py)?

i *think* this still has the same problem i describe in #1344, but i'm not totally sure where this logic would live (in the ddtrace-run command or sitecustomize)
> 2. if `PYTHONPATH=.` and `./sitecustomize.py` exists, `./sitecustomize.py` will run both when `ddtrace-run` runs before [os.exec](https://github.com/DataDog/dd-trace-py/blob/872a8880e942bf76296b83c703ca00a7e3c3eded/ddtrace/commands/ddtrace_run.py#L69)ing *and* in the bootstrapped python app

**Comment by zhammer** [comment]
the ideal here is to have a script that *only* runs in the exec'd python app, after ddtrace-run bootstrap runs. the goal is to take the existing instrumentation setup by ddtrace-run and add some extras, custom to our python setups, across several services / jobs

**Comment by jd** [comment]
> ah wait, i may be missing something, but can you give an example of how this logic would be added to ddtrace-run's sitecustomize.py?

You'd add that at the end of it, so it loads the "real" `sitecustomize` that is available on the system installation.

Keep in mind that `sitecustomize` is a standard Python name module, not something ddtrace related — that's what I'd expect it to work transparently.

If what you want is a way to hook yourself in the `ddtrace` bootstrap code, that's a different story, I'm also not sure why you'd want to do that — we may need to take a step back and understand what's your need in the first place? :)

**Comment by zhammer** [comment]
ha yes let's take a step back :)

we're now using ddtrace-run on a large number of python repositories which each have a bunch of services (a service being some python entrypoint into that repo, could be an http service, a message consumer, a cron job, etc)

pretty much all of these services now run under `ddtrace-run`, which has a great baseline of ddtrace instrumentation bootstrapping, but there is a lot of extra org-wide configuration we'd like to add via code. some examples of this:
- if a job is a cron (which we can sniff out from our runtime env), setup a top-level trace for the whole cron invocation
- add our own custom patching to in-house clients (or clients that don't have official ddtrace contrib patches)
- tweak some existing ddtrace patches
- other org-wide config, like adding a "/_status" filter to all of our apps to not trace health checks

since there are so many different entrypoints to our services, it's a bit hard (and invasive) to add a `custom_datadog_init()` function to all job startups. another option is to setup our own `ddtrace-run` type config (like, `ourorgscustomtrace-run`) that calls the `ddtrace` bootstrap and then runs our own code, but we'd prefer to keep using `ddtrace-run` since it works well.

i happened to find that [user sitecustomize import](https://github.com/DataDog/dd-trace-py/blob/1933a15a00fd1d3a229582bbb063538f7baa856a/ddtrace/bootstrap/sitecustomize.py#L141) in the ddtrace bootstrap and thought that was an ideal place to plug in a custom config. though i guess what we're really looking for is something more akin to a `DDTRACE_RUN_POST_INIT` script, that we can point to our configuration script.

let me know what parts of that aren't clear!

**Comment by zhammer** [comment]
@jd let me know if it'd be better for me to move this to a new issue

**Comment by jd** [comment]
Sorry for the late reply, I missed your answer.

It's an interesting idea, I think it's indeed different issue than using sitecustomize indeed. What you want is a hook that can be executed when tracing is set up.

Such a hook should also work if `ddtrace-run` is not used and the Tracer is setup using Python code IMHO.

Could you use something like a hook that is called when `ddtrace` is imported? Do you think that would for all your uses cases?

**Comment by zhammer** [comment]
@jd sorry for the late reply on my end! times have been weird.

i definitely see value in a post-tracer-setup hook, though i think that wouldn't work perfectly for all of our use cases.

**it does work fairly well for:**
> - add our own custom patching to in-house clients (or clients that don't have official ddtrace contrib patches)
> - other org-wide config, like adding a "/_status" filter to all of our apps to not trace health checks

**it doesn't work as well for:**
> - if a job is a cron (which we can sniff out from our runtime env), set up a top-level trace for the whole cron invocation

this is a super specific use case where i wanted to lean on the sitecustomize work ddtrace-run does to run app startup / shutdown hooks with the tracer already instrumented.

> - tweak some existing ddtrace patches
for this i'm specifically interested (at the moment) in rolling our own requests patch. my thinking (which is admittedly a bit hacky) was:

- we start our app with `ddtrace-run`
- `ddtrace-run` instruments patches (respected `DATADOG_PATCH_MODULES=requests:{true|false}`
- post-ddtrace-run hook checks if requests is patched, if it does, unpatches requests and runs something along the lines of `requests_custom.patch()`
- i'm *not sure* how this could work if the hook runs at `Tracer` setup, since [ddtrace-run bootstrap adds patches after setup](https://github.com/DataDog/dd-trace-py/blob/aa3214671d7843447aa11ba1aea1202eae4aff5a/ddtrace/bootstrap/sitecustomize.py#L93-L97).

---

i'm thinking the best path forward may be to copy and paste the `ddtrace-run` command / bootstrap code into our own tool and add our own custom config there, so we'd run apps with `custom-ddtrace-run my_app.py`. my only worry there would be the additional work needed to keep in sync with changes to the official `ddtrace-run`

**Comment by jd** [comment]
We don't necessarily need one solution to fit all use cases.
For example, we could also add hooks to be called when modules are patched. That might cover some other use cases.

**Comment by zhammer** [comment]
@jd that makes sense. have you seen an implementation for this type of config in the past that you've liked? / any ideas for what it could look like? right now [gunicorn's python config comes to mind](https://docs.gunicorn.org/en/latest/configure.html#configuration-file). something like:

```py
# ddtrace.config.py

def after_ddtrace_run(tracer: Tracer):
    print("ddtrace-run has bootstrapped our code!")
    if os.getenv("JOB_TYPE") == "cron":
        top_level_trace = tracer.trace(os.getenv("JOB_NAME"))
        atexit.register(top_level_trace.finish)

def after_module_patch(tracer: Tracer, module_name: str):
    if module_name == "requests":
        use_custom_requests_patching()

def after_ddtrace_init(tracer: Tracer):
    tracer.configure(
        settings={
            "FILTERS": [
                # don't send status handler tracers to DD APM
                FilterRequestsOnUrl(r".*/(_)?status$")
            ]
        }
    )
```

this is a quick mockup of how that *could* look.

pros:
- extensible, in that different hooks can be added over time

cons:
- import order is important here. if `ddtrace.config.py` is loaded before ddtrace code runs, *and* `ddtrace.config.py` imports `ddtrace`, the tracer could be init'ed in the config file and maybe cause some weirdness.
    * idea in the mockup is to have hooks get the tracer as an argument

**Comment by jd** [comment]
Your idea is timely. I've just opened https://github.com/DataDog/dd-trace-py/pull/1428 to add a generic hook system and https://github.com/DataDog/dd-trace-py/pull/1043 add a hook that an be called when a `Tracer` starts a span.

I think we can build on top of that to add more hooks.

**Comment by zhammer** [comment]
@jd awesome to hear. let me know if you need any help, e.g. we could help qa some of this in our staging environment if we have the time :)

**Comment by brettlangdon** [comment]
I am going to close this PR since it hasn't seen activity in awhile. @zhammer please feel free to re-open or open an issue if your original use case was not resolved!

**Pull request closed without merging**
