### PR TITLE
feat(opensearch): add OpenSearch tracing support (#3331)

### PR DESCRIPTION
**Pull request by luislew**
## Description

This PR implements OpenSearch tracing, based primarily on the existing Elasticsearch integration.

## Checklist
- [x] Followed the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) when writing a release note.
- [x] Add additional sections for `feat` and `fix` pull requests.
- [x] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Motivation

AWS has dropped support for Elasticsearch, and going forward will only support OpenSearch. We recently migrated a couple of applications from ES to OS, and were disappointed to lose visibility into the Opensearch API calls. I saw that the issue had been open since February and (rightly) assumed it would be a small amount of work to add the support.

## Design 
`opensearch-py` is a fork on `elasticsearch`, so writing the integration was mostly copy/paste & find/replace work. Most of the differences were simplifications, e.g. there's only _one_ version of the module (`opensearchpy`) vs. `elasticsearch`|`elasticsearchX`.

## Testing strategy

I added integration tests for OpenSearch, based on the existing Elasticsearch tests, and verified these locally. I also tested the code out against our application by copying over the patch code and validating the APM traces in Datadog, e.g:

Screenshot 2022-11-22 at 3 35 12 PM

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added and follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines), or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.

### CODE REVIEW

**Comment by luislew** [comment]
@Kyle-Verhoog @brettlangdon Tagging you both as top contributors 😀 This is basically a bunch of existing, vetted functionality being ported to support OpenSearch. We're using the code in our application now, but of course would love to have it directly from `ddtrace`. Thanks! 🙏🏻

**Review by majorgreys — COMMENTED** [review]
Thank you for the contribution! One basic question but otherwise non-blocking suggestions.

Could this be supported by adding `opensearchpy` to the tuple defined in `_PATCH_ON_IMPORT["elasticsearch"]`?

**Comment by luislew** [comment]
> Thank you for the contribution! One basic question but otherwise non-blocking suggestions.
> 
> Could this be supported by adding `opensearchpy` to the tuple defined in `_PATCH_ON_IMPORT["elasticsearch"]`?

Perfect timing. After some investigation I discovered that using `opensearch.*` spans instead of `elasticsearch.*` means some built-in support for Elasticsearch in the Datadog APM UI. We switched our own code to simply use the `elasticsearch.patch._patch` function on the `opensearchpy` module and it's working great!

I've submitted an alternative to this PR here: https://github.com/DataDog/dd-trace-py/pull/4641

**Comment by mabdinur** [comment]
Duplicate of: https://github.com/DataDog/dd-trace-py/pull/4641

**Comment by itzko21** [comment]
Hey, when this fix should be in the official release ?

**Pull request closed without merging**
