### PR TITLE
add pymysql support

### PR DESCRIPTION
**Pull request by wklken**

### CODE REVIEW

**Comment by apolloFER** [comment]
Hi @palazzem 
Can we expect this in 0.12.0? 
Tnx

**Comment by palazzem** [comment]
Hello @apolloFER ! sure thing, I'm going to rebase the PR and do a proper review in the next few days. the ETA should be next week. Thank you very much!

**Comment by palazzem** [comment]
Rebased on top of our 0.12 release branch, going to review it right now.

**Comment by palazzem** [comment]
And thank you @wklken for the contribution! Sorry it took so long in our roadmap.

/cc @apolloFER

**Pull request merged**
