### PR TITLE
fix(ci_visibility): use default tracer in CI Visibility (#9328)

### PR DESCRIPTION
**Pull request by romainkomorndatadog**
This reverts commit 2008dd7dbd7f6a726cf7d69b5e5d3e49bbb0cf8b and reinstates the changes from #9016 .

## Checklist

- [x] Change(s) are motivated and described in the PR description
- [x] Testing strategy is described if automated tests are not included in the PR
- [x] Risks are described (performance impact, potential for breakage, maintainability)
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed or label `changelog/no-changelog` is set
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/))
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))
- [x] If this PR changes the public interface, I've notified `@DataDog/apm-tees`.

## Reviewer Checklist

- [x] Title is accurate
- [x] All changes are related to the pull request's stated goal
- [x] Description motivates each change
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- [x] Testing strategy adequately addresses listed risks
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] Release note makes sense to a user of the library
- [x] Author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Comment by romainkomorndatadog** [comment]
After chatting with @brettlangdon , we're leaning towards not backporting this to `2.9`.
 
I suppose if #9349 merges and backports into 2.9 first, then this change would be safe enough to backport as well.

**Comment by romainkomorndatadog** [comment]
Closed because of https://github.com/DataDog/dd-trace-py/pull/9328 .

**Comment by romainkomorndatadog** [comment]
🤦 , closed the wrong PR.

**Review by juan-fernandez — APPROVED** [review]

**Comment by romainkomorndatadog** [comment]
@emmettbutler 
> Does dogweb CI pass when run against this commit?

Not yet, it needs #9349 first.

**Review by brettlangdon — APPROVED** [review]

**Review by emmettbutler — COMMENTED** [review]
I'm going to hold off on approving this until there's a clear indication that it's been tested against dogweb CI.

**Comment by romainkomorndatadog** [comment]
@emmettbutler this never broke dogweb CI, dogweb CI broke because of the bug fixed in #9349 and dogweb's use of `tracer.configure()`.

Bluntly put, dogweb CI isn't this PR's problem and it shouldn't be blocking this fix. We shouldn't be blocking a release because of this.

**Review by emmettbutler — APPROVED** [review]
@romainkomorndatadog thanks for clarifying!

**Comment by romainkomorndatadog** [comment]
Well, crap. This needed to merge after #9349 .

**Pull request merged**
