### PR TITLE
Remove unnecessary caching decorator

### PR DESCRIPTION
**Pull request by brettlangdon**
Unless there is something I am missing the reason why we added this decorator, it doesn't seem necessary.

### CODE REVIEW

**Review by majorgreys — APPROVED** [review]

**Review by jd — APPROVED** [review]
Are we even sure caching hostname is a good idea?

**Comment by brettlangdon** [comment]
> Are we even sure caching hostname is a good idea?

Hmm... do we expect it to ever really change during the lifetime of an application?

**Comment by brettlangdon** [comment]
> Probably not, but in theory it can. Is this a **real** optimization, or an early optimization that would break a possible use case for no(?) gain?

as-is it is potentially called on every span: https://github.com/DataDog/dd-trace-py/blob/7c19fbd90271fdc5d04c095b971e530ffb97afe1/ddtrace/tracer.py#L454-L455

so it definitely needs to be cached in some way... exactly like this? /shrug

**Comment by jd** [comment]
Ok, makes sense to cache it I guess. Though I'd rather cache it locally on the `Tracer` object during its lifetime rather than system-wide. 🤷

**Pull request merged**
