### PR TITLE
chore(asgi): revert regression that removed support for background tasks

### PR DESCRIPTION
**Pull request by mabdinur**
Addresses: https://github.com/DataDog/dd-trace-py/pull/5818#issuecomment-1543604812
Partially reverts: https://github.com/DataDog/dd-trace-py/pull/5818

We will need to backport this fix to 1.9, 1.10, 1.11, 1.12 and 1.13 release lines.

This regression is unreleased so a release note is not required.

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) are followed.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] OPTIONAL: PR description includes explicit acknowledgement of the performance implications of the change as reported in the benchmarks PR comment.

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.

### CODE REVIEW

**Review by Yun-Kim — COMMENTED** [review]
Does this revert mean that the error tags not being set on spans from #5818 is still an issue?

**Comment by mabdinur** [comment]
Nope. This is not a full revert. We only finish the span early if the request span has a "ok" status.

**Comment by mabdinur** [comment]
This should resolve the issues where error messages are not set on asgi spans AND ensure the duration of background tasks are not included in request spans

**Review by Yun-Kim — COMMENTED** [review]
Thanks for clarifying @mabdinur. Just to confirm, are you still able to reproduce the error from #5818 after this change? I know we have snapshot tests for this now but AFAIK we already had a test case that showed errors being set previous to the original bug report?

**Comment by mabdinur** [comment]
Previously the span would be finished, sent and then the error tags would be sent. So there were tests and those tests were passing but the logic was broken. Using a snapshot test validates that the error tags are actually sent to the agent.

**Review by Yun-Kim — APPROVED** [review]

**Pull request merged**
