### PR TITLE
Fixing sqlalchemy test failures

### PR DESCRIPTION
**Pull request by codeboten**
Version 8.0.18 is causing segfaults in sqlalchemy tests.

Signed-off-by: Alex Boten <aboten@lightstep.com>

### CODE REVIEW

**Comment by brettlangdon** [comment]
This looks good, but no idea why CircleCI didn't seem to run/isn't updating here

**Comment by majorgreys** [comment]
This might be relevant to our issue: https://bugs.mysql.com/bug.php?id=97220

**Comment by codeboten** [comment]
Thanks for posting that link, I referenced it in #1099 but it makes more sense here.

**Comment by codeboten** [comment]
> This looks good, but no idea why CircleCI didn't seem to run/isn't updating here

Not sure what happened here.

**Comment by brettlangdon** [comment]
@codeboten I might just do a quick fresh PR myself on this repo with these changes to get CircleCI to run it, then can merge it in.

**Comment by brettlangdon** [comment]
https://circleci.com/workflow-run/94b336fa-cd3b-4da8-bd24-648a1a96831c

**Comment by brettlangdon** [comment]
@codeboten thanks! I was able to validate it passes in CircleCI, so good to me.

**Pull request merged**
