### PR TITLE
chore(ci): install the latest version of each Python minor in docker test image

### PR DESCRIPTION
**Pull request by brettlangdon**
## Description
`pyenv` allows us to omit the micro version when installing Python versions.

This will allow us to keep up to date on each micro version without needing to manually edit the list of versions in `docker/.python-version`.

As well, I added a call to `pyenv global` to ensure each Python version is properly configured in the image (without that call Python 2.7 is the default for `python`, and `python3.11` shows a warning that it isn't installed globally).

## Checklist
- [x] Add additional sections for `feat` and `fix` pull requests.
- [x] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.

### CODE REVIEW

**Review by majorgreys — COMMENTED** [review]
My concern here would be tests start failing with a new build of this image and it's not immediately obvious that the root cause is a python patch release.

**Comment by brettlangdon** [comment]
> My concern here would be tests start failing with a new build of this image and it's not immediately obvious that the root cause is a python patch release.

I know there were some Python patch releases for 3.7 which broke C APIs for the profiler, but have we had any other examples of this happening?

In theory nothing should break/change within a minor version.

If we are worried, an alternative approach is a GitHub action which will check and open a PR with the latest versions bumped for approval/merge. This change as-is feels benign, but I am open to the other approach (pin, and have an automated system to update?)

**Comment by Kyle-Verhoog** [comment]
could we instead build a separate "test-latest" version of our image which uses the latest versions of everything? 

I share @majorgreys concern about non-determinism, it's especially subtle in our Docker image because it's not clear when the image is built and published and it's not versioned at all.

**Comment by brettlangdon** [comment]
👍🏻 closing.

**Pull request closed without merging**
