### PR TITLE
fix(tracing): handle when origin is Py2 unicode

### PR DESCRIPTION
**Pull request by brettlangdon**
## Description
Our HTTP Propagator decodes the `x-datadog-origin` header as a `unicode` object. When encoding a trace we try to pass a `unicode` object into a Cython `cdef` function which only takes a `str` argument. This works fine for Python 3, but fails with Python 2 because the types are handled differently.

This fix introduces a helper to ensure we convert any `unicode` `dd_origin` to a `str` for Python 2 when encoding a span.

## Checklist
- [x] Title must conform to [conventional commit](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).
- [x] Add additional sections for `feat` and `fix` pull requests.
- [x] Ensure tests are passing for affected code.
- [x] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Testing strategy

Added additional test parameters to the existing dd origin tests for the encoders to ensure we test with unicode values.

I also found that the test was broken because we never validated that a trace was successfully written into the `DummyWriter`, so we were testing against `[[]]` as `decoded_traces`, which still passed the test.

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] PR cannot be broken up into smaller PRs.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.
- [ ] Add to milestone.

### CODE REVIEW

**Comment by brettlangdon** [comment]
@Mergifyio backport 1.3

**Review by Kyle-Verhoog — COMMENTED** [review]
Should we be normalizing it at the propagator level instead? Maybe makes more sense to enforce it from the start (what if it's some other type that we don't consider..?)

**Comment by brettlangdon** [comment]
> Should we be normalizing it at the propagator level instead? Maybe makes more sense to enforce it from the start (what if it's some other type that we don't consider..?)

🤔 yeah, our typing for `Context.dd_origin` is `Optional[str]`, so it does match what is expected for Cython. Same for context propagation `headers` being `Dict[str, str]`.

I wonder if this would have been caught if we tested typing for Python 2 compatibility.


Would you think `Context(dd_origin=maybe_stringify(origin))` is good enough?

**Review by mabdinur — APPROVED** [review]

**Comment by Kyle-Verhoog** [comment]
> Would you think Context(dd_origin=maybe_stringify(origin)) is good enough?

Yeah I'd prefer doing it upfront like this (can raise errors sooner, make assumptions downstream, etc) unless we really really get a benefit (performance or otherwise) to doing it at encode time.

**Comment by brettlangdon** [comment]
> > Would you think Context(dd_origin=maybe_stringify(origin)) is good enough?
> 
> Yeah I'd prefer doing it upfront like this (can raise errors sooner, make assumptions downstream, etc) unless we really really get a benefit (performance or otherwise) to doing it at encode time.

Updated

**Review by Kyle-Verhoog — APPROVED** [review]

**Review by mabdinur — APPROVED** [review]

**Comment by brettlangdon** [comment]
@Mergifyio backport 1.4

**Review by Kyle-Verhoog — APPROVED** [review]

**Review by mabdinur — APPROVED** [review]

**Pull request merged**
