### PR TITLE
chore: fix coverage report in 0.59 branch

### PR DESCRIPTION
**Pull request by mabdinur**
``origin/master`` branch no longer exists, this change generates a coverage report against 0.x

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Comment by brettlangdon** [comment]
this needs to be done on `0.x` branch as well?

**Comment by Kyle-Verhoog** [comment]
we should probably target 0.x and then backport to 0.59

**Review by majorgreys — APPROVED** [review]

**Comment by brettlangdon** [comment]
I changed the base branch, but now I wonder if that is the right idea, since we should we targeting `0.x` as the base for diffing right? and not `1.x`.

The version on `0.x` is targeting the "default branch", but maybe it should be hard coded to `0.x` ?

**Comment by mabdinur** [comment]
> I changed the base branch, but now I wonder if that is the right idea, since we should we targeting `0.x` as the base for diffing right? and not `1.x`.
> 
> The version on `0.x` is targeting the "default branch", but maybe it should be hard coded to `0.x` ?

I think it makes sense to hardcode the base branch to 0.x and backport this change to 0.59 (and maybe 0.58, 0.57). As 0.x and 1.x diverge comparing the coverage between the two branches won't provide a lot of value

**Comment by brettlangdon** [comment]
> We could just close this PR and backport this change to 0.59: https://github.com/DataDog/dd-trace-py/pull/3291

I think the problem is we tried to update the scripts to either use repo default branch or `1.x`, but I don't think we want to compare 0.59 (or any future changes on `0.x`) to `1.x`. So hard coding to `origin/0.x` makes sense to me.

**Review by brettlangdon — APPROVED** [review]

**Comment by brettlangdon** [comment]
@Mergifyio backport 0.59

**Review by Kyle-Verhoog — APPROVED** [review]

**Comment by brettlangdon** [comment]
@Mergifyio backport 0.58

**Pull request merged**
