### PR TITLE
chore(tracing): replace set_tag usages with set_tag_str

### PR DESCRIPTION
**Pull request by Yun-Kim**
## Description
Replacing usages of set_tag() that are known to work only with text arguments to set_tag_str() in `trace_utils` and `filters`. This should provide a performance benefit as set_tag_str() bypasses the unnecessary type checking that occurs in set_tag().

This change breaks several test cases for `test_trace_utils.py:test_set_http_meta_headers_useragent` which have invalid parameters for request headers (specifically integer, dictionary, list) that are passed to `set_http_meta()`. Currently, `set_http_meta()`'s function signature accepts a dictionary of string keys and string values for the request headers, which these test cases violate. Also, we should expect request headers to always be string values.

However, this also breaks `test_trace_utils.py:test_set_http_meta-headers_useragent_py2`, which uses non-ascii text that will cause a unicode decoding error which is handled in `set_tag()` and won't be set as a tag, but will actually be set as a tag in `set_tag_str()` as it will be converted to unicode (since it is using `ensure_text`). Is this expected behaviour in `set_tag_str()`?

## Checklist
- [ ] Followed the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) when writing a release note.
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Reviewer Checklist
- [x] Title is accurate.
- [x] Description motivates each change.
- [x] No unnecessary changes were introduced in this PR.
- [x] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Tests provided or description of manual testing performed is included in the code or PR.
- [x] Release note has been added and follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines), or else `changelog/no-changelog` label added.
- [x] All relevant GitHub issues are correctly linked.
- [x] Backports are identified and tagged with Mergifyio.

### CODE REVIEW

**Review by Kyle-Verhoog — APPROVED** [review]

**Comment by Kyle-Verhoog** [comment]
@Yun-Kim tests are failing here

**Comment by mabdinur** [comment]
I think the tracer tests rely on the additional checks in `set_tag`. This change might need to refactor a few tests.

**Comment by Yun-Kim** [comment]
@Kyle-Verhoog @mabdinur the failing tests are because of recently added test cases that break the `set_http_meta()` function signature with invalid argument types. 

For these cases, our current behaviour with `set_tag()` is to allow non-text header values and stringify them (list/dict) or make it a metric (int). However, distributed headers should only be composed of string keys and string values. For this reason I went with removing those invalid test arguments. WDYT?

**Comment by Yun-Kim** [comment]
Update: @Kyle-Verhoog this change also subtly causes a failure to [test_set_http_meta_headers_useragent_py2](https://github.com/DataDog/dd-trace-py/blob/1.x/tests/tracer/test_trace_utils.py#L620).  

This test uses non-ascii text that causes two different behaviors in `set_tag()` and `set_tag_str()`:
- `set_tag()`: gets set using `six.text_type()`, which results in a `UnicodeDecodeError` and doesn't actually get set as a tag.
- `set_tag_str()`: gets set using `six.ensure_text()`. This does not result in any unicode decoding errors and actually does get set as a tag.

Interestingly enough, even though `six.text_type()` (unicode in PY2) and `six.ensure_text()` both attempt to convert a string to unicode in Python 2, `six.text_type()` does not have a default encoding of `utf-8` while `six.ensure_text()` does.

I'm considering version gating this for now so that in Python 2 we'll keep `set_tag()` to avoid this discrepancy in behavior. WDYT?

**Review by P403n1x87 — DISMISSED** [review]

**Comment by Yun-Kim** [comment]
Update after offline discussion: I think it's more important to have consistent behaviors between Python versions and to allow these non-ascii headers to be set as tags (even if decoded) rather than to fail and be specific about only allowing ascii unicode text, since this technically already breaks the function signature of `set_tag()`. For this reason, I'm updating the failing test to expect the useragent header to be set as a tag.

**Review by Kyle-Verhoog — APPROVED** [review]

**Pull request merged**
