### PR TITLE
chore(internal): remove match fn from sample for single span sampling

### PR DESCRIPTION
**Pull request by ZStriker19**
## Description
Refactoring out match from the sample function for easier and more understandable use in the span processor introduced here: https://github.com/DataDog/dd-trace-py/pull/3966

## Checklist
- [ ] Title must conform to [conventional commit](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] Ensure tests are passing for affected code.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] PR cannot be broken up into smaller PRs.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.
- [ ] Add to milestone.

### CODE REVIEW

**Review by brettlangdon — APPROVED** [review]

**Comment by majorgreys** [comment]
So this change is pulling logic around span sampling into a processor. What about the alternative: pushing more of the span sampling logic into the sampling rule itself?

**Comment by brettlangdon** [comment]
> So this change is pulling logic around span sampling into a processor. What about the alternative: pushing more of the span sampling logic into the sampling rule itself?

@majorgreys the issue that we noticed when working on the span processor, is that in order to break early from rule evaluation we'd have to calling `match` twice.

e.g.:

```python
for rule in rules:
    rule.sample(span)  # today calls match and does sampling, and returns if it was sampled
    if rule.match(span):
        break
```

vs

```python
for rule in rules:
    if rule.match(span):
        rule.sample(span)  # does not call match
        break
``


wdyt?

**Review by majorgreys — APPROVED** [review]
I am ok with this change as we figure out how this class works along with span processors.

**Comment by ZStriker19** [comment]
> I am ok with this change as we figure out how this class works along with span processors.

@majorgreys  I've changed the single span processor to work with this change.

**Pull request merged**
