### PR TITLE
Add tox to Docker image

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
Not sure why we don't have this 🤔. Our dev docs in the README assume that it is present in the container else the commands fail. We also end up installing it over and over in CI which seems like wasted work.

### CODE REVIEW

**Comment by jd** [comment]
`git log` has the answer to your question.

The idea is to be able to have the latest tox version in the CI, not an outdated version from when we built the Docker image.

**Comment by jd** [comment]
You can update `run-tox-scenario` to call `pip install tox` first thing.

I'm not a fan of using an "outdated" tox TBH.

**Comment by Kyle-Verhoog** [comment]
Right. But since you have to install it anyway, what's the harm in providing an older one and then updating it? I just don't see why we can't include it 😆

**Comment by jd** [comment]
Sure though you'd need to change `pip install tox` to `pip install -U tox` in the ci. :)

**Pull request merged**
