### PR TITLE
perf(writer): avoid starting if already started

### PR DESCRIPTION
**Pull request by P403n1x87**
## Description

Every time there is an attempt at starting the writer, a new `ServiceStatusError` instance is created which shows up in CPU profiles. By checking the writer service status we reduce the number of exceptions that get created at runtime.

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Review by jd — COMMENTED** [review]
I'm not really excited by this kind of optimization. This is now how it should be fixed. 😢 

The writer should be started when `Tracer` is created/configured. I'd be more interested in seeing this fixed ultimately than having this kind of quick work-around. 😢

**Comment by P403n1x87** [comment]
> I'm not really excited by this kind of optimization. This is now how it should be fixed. 😢

Agreed. The real issue is the fact that the writer needs a delayed start. This change is a quick-fix for the slight performance regression introduced by #2450 (the exception's `__init__` in the Before section below). Long-term we'd want to fix the actual issue, which probably requires something like #2511 .

## Before

Screenshot 2021-06-11 at 10 54 01


## After

Screenshot 2021-06-11 at 10 52 33

**Comment by jd** [comment]
> @jd did we end up making that change to detect and yell if gevent is available and hasn't been patched by the time ddtrace is imported?

Yes.

And yes you're right, this was for a delayed start in case gevent was patched too late.

But that breaks other parts of the tracer/profiler nowadays anyway, so there's no reason to keep it around. Patching gevent too late is a no-no. 😢

**Review by majorgreys — APPROVED** [review]
LGTM

**Review by Yun-Kim — APPROVED** [review]

**Pull request merged**
