### PR TITLE
feat(tests): new release of setuptools raises import error

### PR DESCRIPTION
**Pull request by avara1986**
## Description
All CI pipelines are failing with a import error in _encoding.pyx

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] PR cannot be broken up into smaller PRs.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.
- [ ] Add to milestone.

### CODE REVIEW

**Review by juanjux — DISMISSED** [review]

**Review by gnufede — DISMISSED** [review]

**Review by gnufede — APPROVED** [review]

**Review by juanjux — APPROVED** [review]

**Comment by P403n1x87** [comment]
Do we know what caused this?

**Comment by avara1986** [comment]
> Do we know what caused this?

No, new package dependency release? :(

**Comment by P403n1x87** [comment]
> No, new package dependency release? :(

Looking at PyPI data from within the riot shell of one of the failing commands I get

~~~
[2019-10-09T14:40:45] httpretty (0.9.7)
[2020-10-16T17:37:23] iniconfig (1.1.1)
[2020-11-01T01:40:20] toml (0.10.2)
[2020-11-19T17:10:42] opentracing (2.4.0)
[2020-12-10T07:33:11] mock (4.0.3)
[2021-05-05T14:18:17] six (1.16.0)
[2021-05-16T22:03:41] sortedcontainers (2.4.0)
[2021-07-12T09:36:20] tenacity (8.0.1)
[2021-08-25T16:25:59] pluggy (1.0.0)
[2021-10-04T01:48:57] pytest-cov (3.0.0)
[2021-10-04T16:47:19] bytecode (0.13.0)
[2021-11-04T17:17:00] py (1.11.0)
[2021-11-18T00:39:10] packaging (21.3)
[2021-12-22T12:22:00] wheel (0.37.1)
[2022-02-08T10:54:02] tomli (2.0.1)
[2022-04-22T21:33:27] hypothesis (6.45.0)
[2022-04-23T14:35:55] pytest (7.1.2)
[2022-05-08T07:00:02] xmltodict (0.13.0)
[2022-05-10T23:26:03] pyparsing (3.0.9)
[2022-05-31T11:19:58] pip (22.1.2)
[2022-07-01T14:56:11] typing-extensions (4.3.0)
[2022-07-05T12:51:24] pytest-mock (3.8.2)
[2022-07-14T00:37:44] setuptools (63.2.0)
[2022-07-15T08:25:11] pytest-asyncio (0.19.0)
[2022-07-21T18:16:58] ddsketch (2.0.4)
[2022-07-28T13:20:27] attrs (22.1.0)
[2022-08-06T20:54:41] coverage (6.4.3)
[2022-08-09T21:49:57] protobuf (4.21.5)
~~~
it seems that the prime suspect is `protobuf`? However I started noticing the problem from 2022-08-10. I wonder if the Ci cache is to be blamed?

Anyway, thanks for putting up this fix so promptly! It would be good to get to the bottom of this to see if there's anything that we can do better next time to avoid these situations.

**Comment by P403n1x87** [comment]
I think I've found the issue, which seems to be with [setuptools](https://pypi.org/project/setuptools/#history). I have requested `<64` in `pyproject.toml` and the tests seem to work again.

**Comment by P403n1x87** [comment]
I've put the manual merge label as we also have the `setuptools` pin option as a simpler workaround that would save us touching all the sources in this PR (see https://github.com/pypa/setuptools/issues/3504).

**Review by brettlangdon — CHANGES_REQUESTED** [review]
This is a breaking change, we cannot accept this.

Unless we re-expose `SpanTypes` in `ddtrace.ext` this change cannot be made unless we make a major version bump.

**Comment by P403n1x87** [comment]
> This is a breaking change, we cannot accept this.

Ah! I've missed this! Good point. I then suggest we make this PR a `setuptools` pin instead, which we can more easily backport on other branches.

**Comment by brettlangdon** [comment]
resolved in #4085

**Pull request closed without merging**
