### PR TITLE
chore(ci): add retries for flaky tests

### PR DESCRIPTION
**Pull request by erikayasuda**
Some test suites like telemetry, langchain, and debugger tend to flake pretty consistently. Adding some retries to the base test job definitions so that flakes don't abort PRs in the merge queue before retrying. Added some overrides for additional retry attempts for the suites that tend to have flakier tests.

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by emmettbutler — APPROVED** [review]
This is fine to add, but keep in mind that retries generally don't fix the issue, they just make it occur less frequently.

**Comment by erikayasuda** [comment]
> This is fine to add, but keep in mind that retries generally don't fix the issue, they just make it occur less frequently.

Yeah, I figured the flakyness would still be recorded so it's still being tracked somewhere. Doing this because lately most releases have silently failed because of flakyness, and also with more people using the merge queue it could make that experience a bit painful.

**Review by brettlangdon — APPROVED** [review]

**Review by taegyunkim — APPROVED** [review]

**Pull request merged**
