### PR TITLE
ci: upgrade riot in docker ci image

### PR DESCRIPTION
**Pull request by majorgreys**
## Description

Upgrade docker image to unblock #1828 

## Checklist
- ~[ ] Entry added to release notes using [reno](https://docs.openstack.org/reno/latest/user/usage.html)~
- ~[ ] Tests provided; and/or~
- ~[ ] Description of manual testing performed and explanation is included in the code and/or PR.~
- ~[ ] Library documentation is updated.~
- ~[ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).~

### CODE REVIEW

**Review by jd — CHANGES_REQUESTED** [review]
The problem is that this is going to break the CI right away :(

**Comment by majorgreys** [comment]
@jd Right, I wasn't sure if we could get around that as a first step since we do not have riot pinned in the Dockerfile. We could also pull both tox and riot out of here and handle in the ci config whenever we use the `datadog/dd-trace-py` image.

**Comment by jd** [comment]
Yes, that was my initial intention but @Kyle-Verhoog complained and added them back here. So now we get stalled version in the image.
I agree, I think the proper fix is to make sure we install those in the dd-trace-py Docker image when we need this. Now the challenge is that in CircleCI, we launch it using `docker` to run a command which is not installation riot first thing… that'd solve #1828 issue without breaking the CI right now.

**Comment by majorgreys** [comment]
Resolved by #1864

**Pull request closed without merging**
