### PR TITLE
chore: move integration agent tests to riot

### PR DESCRIPTION
**Pull request by majorgreys**
## Commit Message

{{title}}

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Comment by Kyle-Verhoog** [comment]
This is a duplicate of #2967

**Comment by majorgreys** [comment]
@Kyle-Verhoog Sorry missed that and started this as I was working on #3003. I'm not sure if the approach I've taken here with combining these three agent tests and starting all containers at once will work but wanted to give it a try.

**Comment by majorgreys** [comment]
@Kyle-Verhoog is it worth finishing this up? I realize that the change in trace agent url requires more changes in the tests as those urls are hardcoded in several places. There might be more problems that crop up as I continue on this path. Are your changes preferable to these?

**Comment by Kyle-Verhoog** [comment]
Hmm, the changes in #2967 just port the tests as-is to riot. So this PR could logically follow that one. Do both?

**Comment by majorgreys** [comment]
Duplicate of #2967

**Pull request closed without merging**
