### PR TITLE
Add a ContextProvider using Python 3.7 ContextVars instead of thread locals

### PR DESCRIPTION
**Pull request by airhorns**
If you're trying to use `ddtrace` in a Django Channels application, it is currently pretty hard to get your traces to properly account for the whole slew of spans that might happen in processing a web request or channel message. Specifically, Channels applications that use synchronous code (like say the Django ORM or any old code) are encouraged to use [SyncToAsync](https://github.com/django/asgiref/blob/master/asgiref/sync.py#L83-L122) (or [DatabaseSyncToAsync](https://github.com/django/channels/blob/2a98606c1e0600cbae71ae1f02f31aae5d01f82d/channels/db.py) ) to wrap sync stuff and let async stuff carry on merrily. Those wrappers use an `asyncio.ThreadPoolExecutor` under the hood to run synchronous code on a different thread and yield execution to other async stuff on the main thread. Those inner threads have of course different thread local storage, which means a different ddtrace context, and thus a different set of spans for tracing. 

I think that channels is just the most frequently used thing that does this and that for anything else that uses threadpools ddtrace will also be broken, so at least for my app, I went on a quest to fix it and came up with this.

From https://docs.python.org/3/library/contextvars.html:

> Context managers that have state should use Context Variables instead of threading.local() to prevent their state from bleeding to other code unexpectedly, when used in concurrent code.

Instead of using thread locals, the thing Python suggests now is to use `ContextVar`s, which expose an API that lets things like `asyncio` copy them upon starting new threads. That means that if there is a context outside an `asyncio.ThreadPoolExecutor`, it is easy, cheap, and safe to copy it into new threads spawned by it. `ContextVar`s are also coroutine aware though such that they are more than thread local, they are coroutine local, so if you have multiple stacks of execution on the main thread via `async/await`, each one has it's own possible value of the `ContextVar`. In my case of wanting traces to encapsulate work done in a channels `SyncToAsync` wrapper, that context copying would allow the inner thread to share the same set of spans as the outer calling coroutine, but not share spans among those coroutines or among the inner threads, which is perfect! This PR adds a `ContextProvider` that uses `ContextVar`s to store the currently active `ddtrace` context.

Sadly, there's one more piece to the puzzle to actually getting this to work, which is convincing `asyncio` to actually copy the `ContextVar`s from the calling coroutine to the inner thread. Python (in this developer's opinion, tragically) decided not to make the default behavior copying contextvars, even though they admit it makes sense: https://bugs.python.org/issue34014 . Instead, we're forced to use a special `asyncio.Executor` that does the `ContextVar` copying on its own. There is a handy one here: https://pypi.org/project/contextvars-executor/ . This PR does not set up this executor on it's own, but I tried to explain and give folks who want to use `ContextVarContextProvider` a hint that that needs to happen in the classdoc.

This use case is pretty esoteric but knowing that this is the future of how you're supposed to do this stuff in Python I feel like this class belongs in `ddtrace` itself for the `await` friendly folks like me using `asyncio`. 

Phew.

### CODE REVIEW

**Comment by brettlangdon** [comment]
@airhorns wow, this is awesome. Thank you for such a detailed explanation of the problem you are running into here.

This sounds similar to the "workaround" we have for `gevent` where when spawning a new Greenlet we'll try to clone any existing context.

But because we do this cloning for each Greenlet it means each context gets reported as it's own trace, so they are sort of treated like distributed traces, where any one piece could get sampled out. It is definitely recommended to configure priority sampling when running something like this where a single trace is broken up between multiple contexts, that way the entire trace will either be sampled or not.

This PR is something we will have to review as a team and figure out how we want to handle since we have to handle for `gevent` anyways, maybe we can approach this problem in a different way.

https://github.com/DataDog/dd-trace-py/blob/4e5acbd8ca1d4087291d9d9c1709b61651bba230/ddtrace/contrib/gevent/provider.py#L1-L44
https://github.com/DataDog/dd-trace-py/blob/4e5acbd8ca1d4087291d9d9c1709b61651bba230/ddtrace/contrib/gevent/greenlet.py#L8-L21

**Comment by brettlangdon** [comment]
(and similar to our `asyncio` provider too, as you alluded too)

**Comment by airhorns** [comment]
Okey, no rush! There is a backport of `contextvars` for Python < 3.7 as well but I haven't tried it, it might get us all the way there though. https://github.com/MagicStack/contextvars

**Comment by sciyoshi** [comment]
@brettlangdon please keep us posted as we'd love to have this functionality merged back upstream. Also - hey @Kyle-Verhoog, didn't realize you were at Datadog now, congrats! 😄

**Comment by orf** [comment]
Can we get any movement on this? In a lot of cases `asyncio` tracing is pretty hard to get right, and often broken (depending on when/where you patch with ddtrace). This solves this issue really elegantly, and we've been successfully using it in production.

**Comment by majorgreys** [comment]
Thank you @airhorns for sharing this contribution.

We recently released ContextVar-based context manager which is now the default for Python 3.7. Please take a look at #990 and do file any issues you find with it.

**Pull request closed without merging**
