### PR TITLE
chore(iast): add local debug scripts to find leaks

### PR DESCRIPTION
**Pull request by avara1986**
Add to the repository the scripts that @juanjux and I use to debug C++ leaks. This folder (scripts/iast/) contains some scripts to check the memory usage of native code.

### 1. Build the docker image

```sh
docker build . -f docker/Dockerfile_py311_debug_mode -t python_311_debug
```

#### 2.1. Run the container with the script to find references  (this script will run the memory usage check)

```sh
docker run --rm -it -v ${PWD}:/ddtrace python_311_debug /bin/bash -c "cd /ddtrace && scripts/iast/run_references.sh"
>> References: 1003
>> References: 2
>> References: 2
>> References: 2
>> References: 2
>> References: 2
```

#### 2.2. Run the container with the script with memray usage check

```sh
docker run --rm -it -v ${PWD}:/ddtrace python_311_debug /bin/bash -c "cd /ddtrace && scripts/iast/run_memray.sh"
google-chrome file://$PWD/memray-flamegraph-lel.html
```

#### 2.3. Run the container with the script with Max RSS

```sh
docker run --rm -it -v ${PWD}:/ddtrace python_311_debug /bin/bash -c "cd /ddtrace && scripts/iast/run_memory.sh"
>> Round 0 Max RSS: 41.9453125
>> 42.2109375
```

## Checklist

- [x] Change(s) are motivated and described in the PR description
- [x] Testing strategy is described if automated tests are not included in the PR
- [x] Risks are described (performance impact, potential for breakage, maintainability)
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed or label `changelog/no-changelog` is set
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/))
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))
- [x] If this PR changes the public interface, I've notified `@DataDog/apm-tees`.
- [x] If change touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.

## Reviewer Checklist

- [x] Title is accurate
- [x] All changes are related to the pull request's stated goal
- [x] Description motivates each change
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- [x] Testing strategy adequately addresses listed risks
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] Release note makes sense to a user of the library
- [x] Author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by juanjux — APPROVED** [review]

**Review by erikayasuda — APPROVED** [review]
This looks handy, thanks for adding :)

**Comment by erikayasuda** [comment]
After a second thought and check, I'm realizing these scripts also get included when we build ddtracepy 🤔 Should we be storing these debug scripts elsewhere?

**Comment by avara1986** [comment]
> After a second thought and check, I'm realizing these scripts also get included when we build ddtracepy 🤔 Should we be storing these debug scripts elsewhere?

Thanks for a second check @erikayasuda! I add extra thought and, why are we not skipping all script folder when we build ddtrace-py? :stuck_out_tongue: 

https://github.com/DataDog/dd-trace-py/blob/main/setup.py#L471
```python
setup(
    name="ddtrace",
    packages=find_packages(exclude=["tests*", "benchmarks*"]),
```

**Comment by avara1986** [comment]
Like that @erikayasuda? :point_right:  https://github.com/DataDog/dd-trace-py/pull/9324

**Comment by erikayasuda** [comment]
> Like that @erikayasuda? 👉 #9324

Yesss 🥳 Thanks for updating!

**Pull request merged**
