### PR TITLE
feat(profiling): add debug log when profiler uploads last profile

### PR DESCRIPTION
**Pull request by jd**

### CODE REVIEW

**Review by dbenamydd — COMMENTED** [review]
I think these log lines should be visible at the default log level. We want to add this because there's a confusing experience right now where if you run a profiled service and hit ctrl+c or otherwise shut it down, it seems to hang for several seconds while it uploads the final profile. We want to make this less confusing out of the box, not for the small percentage of users who activate debug logs.

**Comment by jd** [comment]
@dbenamydd this is what the tracer does. Do you think the tracer and profiler should have different behaviours?

**Comment by dbenamydd** [comment]
I'd expect them to both show this by default, although it's possible there context on the tracer side that I don't know about!

The other thought is that I'd expect a single message about both if they're both doing this. Eg (and adding in some wordsmithing)

> Uploading final traces and profiles. Press %s to exit immediately.

**Comment by jd** [comment]
> I'd expect them to both show this by default, although it's possible there context on the tracer side that I don't know about!

@majorgreys , @brettlangdon or @Kyle-Verhoog might know 😄 

> The other thought is that I'd expect a single message about both if they're both doing this. Eg (and adding in some wordsmithing)

Agreed, but that'll come later, I need to do refactoring. At least https://github.com/DataDog/dd-trace-py/pull/2409 and #2245 are needed first.

**Comment by brettlangdon** [comment]
@jd do we still need this PR? Closing for now, feel free to reopen!

**Pull request closed without merging**
