### PR TITLE
chore(ci): update machine executor image

### PR DESCRIPTION
**Pull request by brettlangdon**
CircleCI has provided updates to the `ubuntu-2004` image to address some networking issues.

### CODE REVIEW

**Review by majorgreys — DISMISSED** [review]

**Review by Kyle-Verhoog — APPROVED** [review]
Can we add a motivation to the PR description?

**Comment by brettlangdon** [comment]
> Can we add a motivation to the PR description?

done!

**Review by mabdinur — APPROVED** [review]

**Review by Kyle-Verhoog — APPROVED** [review]

**Comment by brettlangdon** [comment]
Something about our jobs (`./scripts/ddtest` maybe?) really doesn't like this image.

**Comment by majorgreys** [comment]
> Something about our jobs (`./scripts/ddtest` maybe?) really doesn't like this image.

I'm seeing this in [one error log](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/17117/workflows/365053a0-31f2-4d7d-8a37-4aeb73f1040e/jobs/1169693/parallel-runs/0/steps/0-109):

```[+] Running 1/1
 ⠿ testrunner Pulled  0.1s
WARN[0000] The "TMPDIR" variable is not set. Defaulting to a blank string. 
the input device is not a TTY
```

It seems the TTY auto-detection is not working as it should.

We might just need to pass `-T` argument to `docker-compose run` in the `scripts/ddtest`. So that we can continue using it locally, we'd want to only pass that argument if we are running it in CircleCI.

**Review by P403n1x87 — APPROVED** [review]

**Review by Kyle-Verhoog — APPROVED** [review]

**Pull request merged**
