### PR TITLE
chore(profiling): update http exporter to intake v1.3

### PR DESCRIPTION
**Pull request by jd**

### CODE REVIEW

**Comment by jd** [comment]
Not adding a changelog as I'm not sure it should be a user-visible change. Thoughts?

**Review by brettlangdon — COMMENTED** [review]
is there a min agent requirement that has changed? that is the only thing I can think of to call out in a release note.

otherwise, normal rules apply of... if it needs to be backported then it probably needs a note

**Comment by jd** [comment]
> is there a min agent requirement that has changed? that is the only thing I can think of to call out in a release note.

No, I didn't find any change for this. As the agent is mostly a proxy, I'm not surprised.

> otherwise, normal rules apply of... if it needs to be backported then it probably needs a note

It does not need to be backported.

**Review by brettlangdon — APPROVED** [review]

**Review by brettlangdon — APPROVED** [review]

**Review by mabdinur — APPROVED** [review]

**Review by P403n1x87 — APPROVED** [review]

**Comment by Kyle-Verhoog** [comment]
Test failure:

```
assert 0 >= 1
 +  where 0 = len(deque([]))
tracer = <ddtrace.tracer.Tracer object at 0x7fa5d03d9a50>

    @pytest.mark.skipif(not stack.FEATURES["stack-exceptions"], reason="Stack exceptions not supported")
    def test_exception_collection_trace(tracer):
        r = recorder.Recorder()
        c = stack.StackCollector(r, tracer=tracer)
        with c:
            with tracer.trace("test123") as span:
                try:
                    raise ValueError("hello")
                except Exception:
                    nogevent.sleep(1)
    
        exception_events = r.events[stack_event.StackExceptionSampleEvent]
>       assert len(exception_events) >= 1
E       assert 0 >= 1
E        +  where 0 = len(deque([]))

tests/profiling/collector/test_stack.py:352: AssertionError
```

Don't think it's related though

**Pull request merged**
