### PR TITLE
fix(ci): enable mysqlconnector and mysqldb tests

### PR DESCRIPTION
**Pull request by majorgreys**
## Checklist

- [x] Change(s) are motivated and described in the PR description
- [x] Testing strategy is described if automated tests are not included in the PR
- [x] Risks are described (performance impact, potential for breakage, maintainability)
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed or label `changelog/no-changelog` is set
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/))
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))
- [x] If this PR changes the public interface, I've notified `@DataDog/apm-tees`.

## Reviewer Checklist

- [x] Title is accurate
- [x] All changes are related to the pull request's stated goal
- [x] Description motivates each change
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- [x] Testing strategy adequately addresses listed risks
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] Release note makes sense to a user of the library
- [x] Author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by wconti27 — APPROVED** [review]

**Review by emmettbutler — COMMENTED** [review]
I can't tell what changed here because the diff is really big. If you pare down the diff to just the functional changes I'll give this another review.

**Comment by majorgreys** [comment]
> I can't tell what changed here because the diff is really big. If you pare down the diff to just the functional changes I'll give this another review.

oh no, didn't realize the json got formatted. will fix.

**Comment by brettlangdon** [comment]
@majorgreys I fixed the merge conflict and updated from `main`, can you review to make sure I did it correctly?

**Review by emmettbutler — CHANGES_REQUESTED** [review]
Looks like the newly-enabled tests are failing. Let me know if you'd like any help with that.

**Pull request closed without merging**
