### PR TITLE
fix(celery): set celery distributed tracing headers correctly

### PR DESCRIPTION
**Pull request by goodspark**
Upstreaming a fix by @iredelmeier and @rossdylan

There seem to be two problems at play here:
- If the `headers` object is empty, such as if it's coming from a protocol v1 task, the object was previously being created fresh rather than being updated. The headers therefore weren't being propagated.
- The headers were being nested under an extra `headers` key.

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [ ] Testing strategy is described if automated tests are not included in the PR.
- [ ] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [ ] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [ ] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [ ] Title is accurate.
- [ ] No unnecessary changes are introduced.
- [ ] Description motivates each change.
- [ ] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Testing strategy adequately addresses listed risk(s).
- [ ] Change is maintainable (easy to change, telemetry, documentation).
- [ ] Release note makes sense to a user of the library.
- [ ] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [ ] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by emmettbutler — CHANGES_REQUESTED** [review]
@goodspark looks like the precheck job is failing because of a style issue

**Review by emmettbutler — CHANGES_REQUESTED** [review]
Hi @goodspark, and thanks for the pull request!

Looking at the failing `celery` test and this diff, it's not clear to me what bug this is fixing. If you added a regression test in `tests/contrib/celery` that demonstrated the issue, it would clarify why this change is necessary in addition to ensuring that the bug doesn't reoccur.

Let me know if you'd like help with that, and thanks again!

**Review by mabdinur — COMMENTED** [review]
Hey @goodspark, 

Thanks for bringing this bug to our attention. Do you still have time to work on this change?

**Comment by emmettbutler** [comment]
I'm closing this because it's been inactive for a bit. Please comment if you have any new information to add.

**Pull request closed without merging**
