### PR TITLE
feat: use reno to add release notes

### PR DESCRIPTION
**Pull request by jd**

### CODE REVIEW

**Comment by brettlangdon** [comment]
@jd would like your thoughts/review on #1599 as well. Should we enforce that, and if so, does that approach work?

**Comment by jd** [comment]
Yes, I think it's a good idea to have a job that tells you if you forgot to add a changelog or not and use a label to force the absence of it. 👍 
I guess you can simplify and convert #1599 to a non-draft PR!

**Comment by brettlangdon** [comment]
This just does `reno lint` and adds a new section to the docs, but does not use `reno` to add release notes to the docs, right?

**Comment by jd** [comment]
You have to use `reno new` on your computer to create a release note and add it with your commit, and it'll just work.
You'll see the release notes in the docs (that's done with the sphinx extension)

**Review by Kyle-Verhoog — COMMENTED** [review]
Is there any migration step we can take to move our current "changelog" to reno? Or do we just start using it from this point on?

**Comment by jd** [comment]
That's a good point, but I don't think so.

`reno` uses git to put the right release note entry into its right version. There's no way to build that from an old changelog file since… it's too late. Unless we modify the git history 😢

**Comment by Kyle-Verhoog** [comment]
Gotcha, well it'll improve our lives going forward so I'm all for that 😄

**Review by Kyle-Verhoog — APPROVED** [review]

**Pull request merged**
