### PR TITLE
fix: don't allow package version to be `None`

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
If users try to repackage the library there is the possibility that the `__version__` can be `None` which eventually causes the writer to fail as it tries to serialize `None` into the http headers sent to the agent.

This PR provides a more sensible default.

thanks to @thehesiod for finding and describing this error 🙂.

### CODE REVIEW

**Comment by thehesiod** [comment]
thank you!

**Comment by brettlangdon** [comment]
hmm, when does this happen?

**Comment by Kyle-Verhoog** [comment]
@brettlangdon it was occurring in @thehesiod's case in a pretty niche situation where the version would be `None` as a result of
https://github.com/DataDog/dd-trace-py/blob/14fb771ad23eb1abbb0784698afa6cc1f0ad2bdf/ddtrace/__init__.py#L14-L18


which would then be used here: https://github.com/DataDog/dd-trace-py/blob/14fb771ad23eb1abbb0784698afa6cc1f0ad2bdf/ddtrace/api.py#L154

**Comment by brettlangdon** [comment]
Makes sense, that is off scenario, but possible.

aside: I wonder if we should default to `"dev"` instead of `None` /cc @jd

**Comment by Kyle-Verhoog** [comment]
@jd agreed. But you're proposing a larger refactoring change (which I totally agree with). This is correction to existing code that, from what I can tell, assumed that it was catching all possible exceptions that could be raised and it wasn't.

Given the way the current code is structured I think it makes sense. I also don't like it either. A larger change to this code will take longer to review/get merged whereas this addresses the problem immediately without introducing any new "badness" that was not already there 😛.

Exception code aside, I think it does make sense to change the default for version to be, at least, not `None`.

Your thoughts? 🙂

**Comment by jd** [comment]
The problem is that I think the medicine is worse than the illness: this is not going to fix the illness, it's going to hide it.

I'm not asking for a large refactoring. I'm stating the current behavior is sane. What should be fixed is:

1. the header that is `None` should be fixed (Brett proposed a solution for this)
2. if we want to make the code more robust we shouldn't do what this PR does but make the worker thread restart-on-crash (I hope it's not a *large* refactoring!)

**Comment by Kyle-Verhoog** [comment]
Fair enough 🙂. The real issue at hand here is that a header can be `None` so let's correct that. I've got some changes in the pipeline for how the worker deals with exceptions so we can revisit the design there.

**Comment by thehesiod** [comment]
in general assuming what errors can occur from a global error handler is bad policy, especially w/o any sort of logging that errors are uncaught since it causes the thread to go away

**Pull request merged**
