### PR TITLE
chore(ciapp): add library_version tag to the root test span

### PR DESCRIPTION
**Pull request by jirikuncar**
Adds `library_version` to the root span which is missing in the CI Visibility intake track.

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Review by Kyle-Verhoog — COMMENTED** [review]
Would be good to get a little more context on why this is required and what it provides us/the user in the PR description.

If it's user-facing then probably worth having a release note.

**Review by juan-fernandez — APPROVED** [review]
looks good from CI Visibility's perspective

**Comment by jirikuncar** [comment]
> it would be good to clarify here why the existing Datadog-Meta-Tracer-Version header to the agent is not enough.

@majorgreys @Kyle-Verhoog more details can be found in CIAPP-4038 card.

> I'm also wondering if the naming should allow similar metadata about the instrumentation to be included in the trace. Any idea on a dot namespace that this could be subsumed under, e.g., `instrumentation.version`?

Can we discuss it together with other tracer maintainers?

**Comment by juan-fernandez** [comment]
> To @Kyle-Verhoog's suggestion, it would be good to clarify here why the existing `Datadog-Meta-Tracer-Version` header to the agent is not enough.

That's a fair question. CI Visibility's way to report tests can be agentless, meaning that there's no agent adding any tag. We have added the version tag to the agentless payload format, but we need it in agent based approach too, and we want it to be the same (so as not to be confusing). 

> I'm also wondering if the naming should allow similar metadata about the instrumentation to be included in the trace. Any idea on a dot namespace that this could be subsumed under, e.g., `instrumentation.version`?

Is there anything other than `language` and `version` that would be added to `instrumentation` ? This might be a good idea, but we haven't thought of more metadata other than these two tags

**Review by Kyle-Verhoog — DISMISSED** [review]

**Review by juan-fernandez — APPROVED** [review]

**Pull request merged**
