### PR TITLE
fix(opentelemetry): support attribute argument in TracerProvider.get_tracer()

### PR DESCRIPTION
**Pull request by mabdinur**
Resolves incompatibility introduced by: https://github.com/open-telemetry/opentelemetry-python/commit/d4e13bdf95190314b0d21a9357f850fa2e6a4cd3. 

In `opentelemetry-api==1.26.0`, `ddtrace.opentelemetry.TracerProvider.get_tracer(...)`  gets called with the attributes argument ([here](https://github.com/open-telemetry/opentelemetry-python/blob/v1.26.0/opentelemetry-api/src/opentelemetry/trace/__init__.py#L519)). This optional argument is not currently supported in ddtrace and this raises a TypeError when ddtrace-opentelemetry support is enabled. 

This PR resolves this incompatibility by providing two implementations for `ddtrace.opentelemetry.TracerProvider.get_tracer`, one for opentelemetry-api>=1.26 and one for opentelemetry<1.26.

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Comment by cbeauchesne** [comment]
Jira to close once fixed -> https://datadoghq.atlassian.net/browse/APMAPI-180

And also PR to revert https://github.com/DataDog/system-tests/pull/2818

**Comment by mabdinur** [comment]
Blocked by: https://github.com/DataDog/dd-trace-py/pull/9929

**Review by ZStriker19 — APPROVED** [review]

**Review by zacharycmontoya — APPROVED** [review]

**Comment by doudoujay** [comment]
@mabdinur hello there I'm wondering why pinning to 1.25.0 wouldnt fix this?
```
# 1.26.0 is broken with dtrace.opentelemetry.TracerProvider.get_tracer 
# https://github.com/DataDog/dd-trace-py/pull/9941
opentelemetry-api==1.25.0
```

my dockerfile:
```
# Base image
FROM python:3.10

# Datadog https://docs.datadoghq.com/serverless/google_cloud_run?code-lang=python
# https://registry.hub.docker.com/r/datadog/serverless-init
COPY --from=datadog/serverless-init:1.2.5 /datadog-init /app/datadog-init
RUN pip install --target /dd_tracer/python/ ddtrace
.....
```


After the docker build i still got 
```
sudo docker run --rm mycontainer:latest pip list | grep opentelemetry-api
opentelemetry-api                             1.26.0
```

**Comment by doudoujay** [comment]
To other `DD_TRACE_OTEL_ENABLED` trace user, I found the only temp solution is to disable `DD_TRACE_OTEL_ENABLED` before the release is pushed to https://pypi.org/project/ddtrace/

**Comment by mabdinur** [comment]
> To other `DD_TRACE_OTEL_ENABLED` trace user, I found the only temp solution is to disable `DD_TRACE_OTEL_ENABLED` before the release is pushed to https://pypi.org/project/ddtrace/

This change was merged yesterday and it resolves an incompatibility introduced in opentelemetry-api v1.25.0: https://github.com/DataDog/dd-trace-py/pull/9929

Try using v1.24.0. Opentelemetry-api<=1.24.0 should compatible with all recent versions of ddtrace.

**Pull request merged**
