### PR TITLE
ci: move profiling tests to riot

### PR DESCRIPTION
**Pull request by P403n1x87**
## Description

This change migrates the profile test suite from tox to riot.

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Review by brettlangdon — DISMISSED** [review]

**Comment by jd** [comment]
Last time I checked riot did not support correctly passing multiple args to `pytest` – which I heavily use in my day-to-day activities.

For example: `riot run foobar -- -k 'not foobar'` would not work as expected.

One of the necessary PR to make that work was https://github.com/DataDog/riot/pull/128 but it needs more work.

So until riot is fixed, I'd prefer we wait on this. 😢

**Comment by P403n1x87** [comment]
Ah too bad 🙁 . I'll close this for now then.

**Comment by P403n1x87** [comment]
Re-opening to only add to riot. We keep running this with tox in CI for now.

**Review by brettlangdon — COMMENTED** [review]
do we need to remove from tox and update the circleci job?

**Comment by P403n1x87** [comment]
> do we need to remove from tox and update the circleci job?

Once @jd gets a chance to test the riot jobs and they're happy with them we can remove from tox and update CircleCI to invoke riot.

**Review by brettlangdon — APPROVED** [review]

**Pull request closed without merging**
