### PR TITLE
fix: avoid latest release of mysql-connector-python

### PR DESCRIPTION
**Pull request by P403n1x87**
## Description

The latest release of mysql-connector-python seems to introduce a
regression on Python 2.7 so we temporarily prevent tox from installing
it.

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Review by majorgreys — DISMISSED** [review]

**Review by Kyle-Verhoog — DISMISSED** [review]

**Review by Kyle-Verhoog — APPROVED** [review]

**Review by Yun-Kim — DISMISSED** [review]
LGTM, what was the regression introduced by the latest version of mysql-connector-python?

**Review by majorgreys — APPROVED** [review]

**Comment by P403n1x87** [comment]
> LGTM, what was the regression introduced by the latest version of mysql-connector-python?

Looks like an import internal to the library is failing.

**Review by Yun-Kim — DISMISSED** [review]

**Review by majorgreys — APPROVED** [review]

**Review by Kyle-Verhoog — APPROVED** [review]
@P403n1x87 can we add a link to the breaking specific release in the PR description for reference in the future?

**Comment by Kyle-Verhoog** [comment]
Ah so turns out that mysql connector dropped python 2 support in their latest release: https://pypi.org/project/mysql-connector-python/8.0.24/

```
Programming Language
Python :: 3
Python :: 3.6
Python :: 3.7
Python :: 3.8
Python :: 3.9
```

**Pull request merged**
