### PR TITLE
flask: add autopatching

### PR DESCRIPTION
**Pull request by talwai**

### CODE REVIEW

**Comment by brettlangdon** [comment]
@talwai I was thinking about this last couple days, if we are going to do auto-patching of `Flask`, should we just patch the `flask.Flask` methods rather than still relying on `blinker`/signals/etc?

There is a good single entry point [flask.Flask.full_dispatch_request](https://github.com/pallets/flask/blob/0.12/flask/app.py#L1600-L1615) which would be pretty easy to wrap, and might actually give us more accurate request timing and is supported back to version `0.7`.

**Comment by talwai** [comment]
Thanks @brettlangdon ! That looks like a more natural entrypoint indeed though it may be out of the scope of this PR, which is trying to do the 'simple' thing of working our existing patching into `flask.Flask`'s init block. I think we'll queue some work to revisit the `signals` approach after this lands, and we verify that there are no regressions when running Flask with implicit tracing under `patch_all()`.

**Comment by brettlangdon** [comment]
@talwai that sounds like a good plan.

I have a very basic prototype of what I discussed locally. I'd be happy to polish it up a little more and submit a PR, even knowing it might not get merged in right away, so we don't lose track of it :)

**Comment by talwai** [comment]
PR is 100% welcome!

**Pull request merged**
