### PR TITLE
Add support for Python 3.7

### PR DESCRIPTION
**Pull request by jd**

### CODE REVIEW

**Comment by jd** [comment]
Needs https://github.com/DataDog/dd-trace-py/pull/868

**Comment by jd** [comment]
Need https://github.com/DataDog/dd-trace-py/pull/873

**Comment by brettlangdon** [comment]
The issues you found so far are resolved correct? Assume we can move forward with this still?

**Comment by jd** [comment]
Yeah, I'm waiting for https://github.com/DataDog/dd-trace-py/pull/882 to be merged since it'll conflict *and* simplify this PR (and therefore, my life).

**Comment by jd** [comment]
This is ready!

**Pull request merged**
