### PR TITLE
Add arch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Add arch64 wheel build support in github action with qemu

### CODE REVIEW

**Comment by brettlangdon** [comment]
Nice!

@odidev it might be worth contributing upstream to [cibuildwheel](https://github.com/joerick/cibuildwheel) looks like they only have aarch64 support via TravisCI right now. Would be really awesome for them/others using cibuildwheel to have GitHub actions support for aarch64 as well.

What do you think?

**Comment by odidev** [comment]
@brettlangdon thanks for quick response. Please find my response inline-

> Would be really awesome for them/others using cibuildwheel to have GitHub actions support for aarch64 as well.

The community is working on it. Please have a look at https://github.com/joerick/cibuildwheel/pull/482. I am not sure about the release plan for cibuildwheel  with this ([#482](https://github.com/joerick/cibuildwheel/pull/482)) change. Till then, this PR will help building/uploading aarch64 wheels to pypi.

**Review by jd — CHANGES_REQUESTED** [review]
Looks like some profiling changes got mixed together

**Comment by brettlangdon** [comment]
> The community is working on it. Please have a look at joerick/cibuildwheel#482. I am not sure about the release plan for cibuildwheel with this (#482) change. Till then, this PR will help building/uploading aarch64 wheels to pypi.

Nice! It looks like this change was approved 11 hours ago. We probably wouldn't be able to fully test/use your PR until sometime next week (we don't have any releases planned this week anyways), so might be worth waiting to see if official support via `cibuildwheel` gets released this/next week.

Is it ok with you if we just leave this PR open for now, we can follow the `cibuildwheel` PR and then make a decision early next week on either using this PR as-is or updating to use the new `cibuildwheel` way?

**Comment by odidev** [comment]
> Is it ok with you if we just leave this PR open for now, we can follow the `cibuildwheel` PR and then make a decision early next week on either using this PR as-is or updating to use the new `cibuildwheel` way?

Sounds good to me. Thanks.

**Comment by odidev** [comment]
> Looks like some profiling changes got mixed together

Fixed this issue. Thanks.

**Comment by brettlangdon** [comment]
This has been merged in upstream in cibuildwheel.

It hasn't been released to pypi, but it seems if we are able to install latest from git/master then we should be able to validate this.

https://cibuildwheel.readthedocs.io/en/latest/options/#archs

**Review by majorgreys — APPROVED** [review]
Let's get merge this in and we can update once cibuildwheel does a release with the support.

**Review by jd — APPROVED** [review]

**Comment by odidev** [comment]
@jd, Thanks for merging the PR. Can you please let me know the plan for releasing aarch64 wheels?

**Comment by brettlangdon** [comment]
hey @odidev, good question. We won't publish any aarch64 wheels for any existing releases, but they should be automatically included in every release going forward.

We have 0.46.0 which should be out before end of next week.

**Pull request merged**
