### PR TITLE
fix(ci): update dev image pyenv to v2.3.6

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
v2.3.6 contains Python 3.11.

https://github.com/pyenv/pyenv/releases/tag/v2.3.6

### CODE REVIEW

**Review by brettlangdon — APPROVED** [review]

**Review by majorgreys — APPROVED** [review]

**Review by brettlangdon — COMMENTED** [review]
should we also move to using "latest" for python versions in `.python-versiosn` as well?

https://github.com/pyenv/pyenv/blob/e03118235a13f3caab9ec99b92325adee7d0fdb5/COMMANDS.md#pyenv-install

`pyenv install 3.11` or `pyenv install 3.11:latest`

**Comment by Kyle-Verhoog** [comment]
https://hub.docker.com/repository/registry-1.docker.io/datadog/dd-trace-py/builds/08b969a5-cf5a-4b30-93f6-b7936ce4ad6f image build is passing

**Comment by Kyle-Verhoog** [comment]
> should we also move to using "latest" for python versions in .python-versiosn as well?

i've had enough `latest` for now 😆 

it's an easy enough change to put up as a proposal PR if you wanna make a case for it

**Comment by brettlangdon** [comment]
> it's an easy enough change to put up as a proposal PR if you wanna make a case for it

Very nice way of saying "piss off" 🤣

**Comment by brettlangdon** [comment]
https://github.com/DataDog/dd-trace-py/pull/4477

**Pull request merged**
