### PR TITLE
test(compat): skip maybe_stringify test on PY2

### PR DESCRIPTION
**Pull request by P403n1x87**
## Description

This test hangs occasionally on Python 2, making the tracer test flaky.

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Review by jd — COMMENTED** [review]
How can this hang?

**Comment by P403n1x87** [comment]
> How can this hang?

It seems this is due to some internal hypothesis processing in `hypothesis/internal/conjecture/shrinker.py`

**Review by Yun-Kim — APPROVED** [review]

**Comment by brettlangdon** [comment]
do you have a link to code for hypothesis issue? still seems weird to be having an issue in py2

**Comment by P403n1x87** [comment]
> do you have a link to code for hypothesis issue? still seems weird to be having an issue in py2

When I turned the full stacktrace on with pytest, sending a SIGTERM would show the interpreter running through the code in this method https://github.com/HypothesisWorks/hypothesis/blob/5181a22fcb05a346f5f74c8ed69abdb611ba8ce3/hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py#L1030

**Review by Kyle-Verhoog — APPROVED** [review]
Really strange.. it would be great to still have these tests for python 2 since strings are so different between 2 and 3 but approving to get our CI unblocked.

**Pull request merged**
