### PR TITLE
Move changelog check to its own script

### PR DESCRIPTION
**Pull request by brettlangdon**
## Description
The changelog validation workflow we introduced didn't actually block PRs that didn't have a changelog entry aded.

This is because we were checking against `git diff origin/master... releasenotes/notes`, but if you didn't add anything the command would still succeed.

The main change here is moving to `git diff --name-only --diff-filter=A origin/master... | grep releasenotes/notes` which will succeed if there was a new filed _added_ in `releasenotes/notes`, but fail if not.

We also moved this check to it's own script to help readability and to add some logging output to help analyze success/failures.

## Checklist
- [ ] ~Entry added to release notes using [reno](https://docs.openstack.org/reno/latest/user/usage.html)~
- [ ] ~Tests provided; and/or~
- [x] Description of manual testing performed and explanation is included in the code and/or PR.
- [ ] ~Library documentation is updated.~
- [ ] ~[Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).~

### CODE REVIEW

**Comment by brettlangdon** [comment]
The validation failed as expected:

```
Run scripts/check-releasenotes "master" "/home/runner/work/_temp/_github_workflow/event.json"
  scripts/check-releasenotes "master" "/home/runner/work/_temp/_github_workflow/event.json"
  shell: /bin/bash -e {0}
Base ref: origin/master
GitHub event path: /home/runner/work/_temp/_github_workflow/event.json
JQ: /usr/bin/jq
Release note not found.
Use 'reno new <slug>' to add a new note to 'releasenotes/notes', or add the label 'changelog/no-changelog' to skip this validation
Error: Process completed with exit code 1.
```

**Comment by brettlangdon** [comment]
Only major issue I have is needing to push on the PR to pick up the `changelog/no-changelog` label being added.

Maybe an improvement (for the future) is to fetch the current PR labels from the API rather than relying solely on the GitHub even file provided in the GitHub action build?

**Comment by Kyle-Verhoog** [comment]
Hmm this just made me realize that when a changelog entry isn't required either the PR-er has to:
- push their change (will fail due to no label)
- add the label
- force push to retrigger the build or add a subsequent commit

not a huge deal but might be a pain since that last step will nullify any approvals on the PR.

**Comment by Kyle-Verhoog** [comment]
jinx

**Comment by brettlangdon** [comment]
haha, yeah. could be solved with an API pull of the labels since then you can manually re-run and it'll be fine.

could also make it where it isn't required to merge, so more informative, but I kind of like the "HEY, ADD A CHANGELOG" message it gives (or the "make a decision" message)

**Review by Kyle-Verhoog — DISMISSED** [review]

**Comment by Kyle-Verhoog** [comment]
totally forgot about the ability to trigger the job on label/unlabel! 👌

**Comment by brettlangdon** [comment]
but it didn't run... am I missing an event?

**Comment by brettlangdon** [comment]
there we go, should be good. I just tested by removing and re-adding the label, and it does run as expected 👍🏻

**Review by Kyle-Verhoog — APPROVED** [review]
🙌

**Pull request merged**
