### PR TITLE
Updated to pypi advance usage docs

### PR DESCRIPTION
**Pull request by sarina-dd**
Changed instances of `Trace Search & Analytics` to `App Analytics` per request on the docs JIRA board.

### CODE REVIEW

**Comment by sarina-dd** [comment]
👍 changes complete

**Comment by brettlangdon** [comment]
Here is a preview of the docs changes: https://245040-61572326-gh.circle-artifacts.com/0/tmp/docs/advanced_usage.html

Not 100% sure why the side menu is kind of messed up, but everything else looks right.

**Comment by sarina-dd** [comment]
> Here is a preview of the docs changes: https://245040-61572326-gh.circle-artifacts.com/0/tmp/docs/advanced_usage.html
> 
> Not 100% sure why the side menu is kind of messed up, but everything else looks right.

Interesting. This is my first time working within this repo, so I'm not quite sure what the issue may be. I'll try to troubleshoot later today 👍

**Comment by brettlangdon** [comment]
oh @sarina-dd I wouldn't spend any time on it. The side bar rendering weird is just because of how it being served by CircleCI. It will render totally fine when we deploy the change.

But thanks for offering!!

**Pull request merged**
