### PR TITLE
fix(telemetry): update compatible field in telemetry payload

### PR DESCRIPTION
**Pull request by mabdinur**
This field is a boolean and not a string. 

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Review by Kyle-Verhoog — COMMENTED** [review]
> Remove compatible field from telemetry payload. This field is a boolean and not a string

is it not required?

**Comment by mabdinur** [comment]
> > Remove compatible field from telemetry payload. This field is a boolean and not a string
> 
> is it not required?

Nope. I can set it to true instead of removing it. We can queue up an integration that is not supported.

**Review by brettlangdon — APPROVED** [review]

**Review by paullegranddc — APPROVED** [review]

**Review by Kyle-Verhoog — APPROVED** [review]

**Comment by mabdinur** [comment]
@Mergifyio backport 0.x

**Comment by mabdinur** [comment]
@Mergifyio backport 0.60

**Comment by paullegranddc** [comment]
🔥

**Comment by mabdinur** [comment]
@Mergifyio backport 1.0

**Pull request merged**
