### PR TITLE
refactor(internal): factor LFU caching logic out in own class

### PR DESCRIPTION
**Pull request by P403n1x87**
## Description

The LFU caching logic has been refactored out of the cached decorator and into the LFUCache class to make the functionality available more generally for when a decorator is not suitable.

## Checklist
- [x] Title must conform to [conventional commit](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).
- [x] Add additional sections for `feat` and `fix` pull requests.
- [x] Ensure tests are passing for affected code.
- [x] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] PR cannot be broken up into smaller PRs.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.
- [ ] Add to milestone.

### CODE REVIEW

**Review by brettlangdon — APPROVED** [review]

**Comment by brettlangdon** [comment]
Do we need to update tests to ensure using it on it's own works as expected?

**Comment by P403n1x87** [comment]
> Do we need to update tests to ensure using it on it's own works as expected?

I believe the decorator tests still cover the whole behaviour of the new class, so I didn't add a dedicated test case.

**Review by ZStriker19 — APPROVED** [review]

**Comment by P403n1x87** [comment]
> Actually judging by this article, should we call it an LFU cache instead?

Indeed. It seems that people agree on denoting the _eviction_ policy, so LFU. For me it's more natural to think in terms of _retention_, for reasons. But I guess we should probably do what the majority does to avoid confusion?

**Comment by ZStriker19** [comment]
🤷  up to you, I don't have enough world programming context to make the call.

**Review by brettlangdon — APPROVED** [review]

**Review by brettlangdon — APPROVED** [review]

**Review by ZStriker19 — APPROVED** [review]
Nice!

**Pull request merged**
