### PR TITLE
Add graphql tracing support

### PR DESCRIPTION
**Pull request by beezz**
This PR adds support for tracing `graphql.graphql` from [graphql-core](https://github.com/graphql-python/graphql-core) library.

### CODE REVIEW

**Comment by palazzem** [comment]
Thank you a lot @beezz for this contribution! We will take a look as soon as we have some free cycles!

**Comment by beezz** [comment]
@palazzem One month passed. This is so discouraging.

**Comment by palazzem** [comment]
Hello @beezz! sorry for the delay but we had some big internal improvements, so unfortunately the review of your PR has been delayed. We'll do our best to not keep that one too much on hold! Thank you!

**Comment by beezz** [comment]
@palazzem Thanks for the update. Let me know if and how can I help here.

**Comment by stefanpelders** [comment]
@palazzem still on hold? 😭

**Comment by palazzem** [comment]
@stefanpelders starting the review today! 💯 ... in the meantime, did you try this branch? it would be great having also some feedbacks from the community itself!

Thank you!

**Comment by beezz** [comment]
@palazzem We are running the `graphql` branch in production since 0.8.5.

**Comment by palazzem** [comment]
Nice @beezz! going through this today so that we can ship it!

**Comment by beezz** [comment]
@palazzem I noticed you removed the 0.10.0 milestone. So what is the plan with this PR now?

**Comment by palazzem** [comment]
Hello @beezz! I had to reschedule this PR since the 0.10.0 was expected to include only minor fixes and our new Distributed Sampling (that took most of our time). This PR can be reviewed and merged now so I'll ping you immediately after the review.

Sorry again for the waiting!

**Comment by beezz** [comment]
Hello @palazzem. I'm closing this PR and will continue with graphql ddtrace support in a separate package so people can use it. https://github.com/beezz/ddtrace-graphql

**Comment by palazzem** [comment]
@beezz I'm so sorry this has been delayed for some show-stopper we had :(
Anyway I would like to include your work in our tracing library. Can you rethink this action and submit this PR so I can ensure it gets merged next week?

**Pull request closed without merging**
