### PR TITLE
chore(ci): move profile tests to riot

### PR DESCRIPTION
**Pull request by brettlangdon**
The profiling tests are the last tests still using tox, this PR moves them to riot and removes all usage of tox from README/CircleCI/scripts.

<details>
<summary>Previous profile tox envs (36)</summary>

```
py27-profile
py27-profile-gevent
py35-profile
py35-profile-gevent
py36-profile
py36-profile-gevent
py37-profile
py37-profile-gevent
py38-profile
py38-profile-gevent
py39-profile
py39-profile-gevent
py310-profile
py310-profile-gevent
py311-profile
py311-profile-gevent
py27-profile-minreqs
py27-profile-minreqs-gevent
py35-profile-minreqs
py35-profile-minreqs-gevent
py36-profile-minreqs
py36-profile-minreqs-gevent
py37-profile-minreqs
py37-profile-minreqs-gevent
py38-profile-minreqs
py38-profile-minreqs-gevent
py39-profile-minreqs
py39-profile-minreqs-gevent
py310-profile-minreqs
py310-profile-minreqs-gevent
py311-profile-minreqs
py311-profile-minreqs-gevent
py37-profile-protobuf319
py38-profile-protobuf319
py39-profile-protobuf319
py310-profile-protobuf319
py311-profile-protobuf319
```

</details>

<details>
<summary>New profile riot envs (32)</summary>

```
 No.    Hash     Name     Interpreter                Environment                                                                        Packages                                                                                                       
 #1505  1ed9e02  profile  Interpreter(_hint='2.7')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'tenacity' 'protobuf'                                                   
 #1506  a6117d3  profile  Interpreter(_hint='2.7')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'tenacity==5.0.1' 'protobuf==3.0.0'                                     
 #1507  183e924  profile  Interpreter(_hint='2.7')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'gunicorn' 'gevent==1.1.0' 'greenlet<2'                                 
 #1508  1fe2085  profile  Interpreter(_hint='2.7')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'gunicorn' 'gevent'                                                     
 #1509  6ff9aaa  profile  Interpreter(_hint='3.5')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity' 'protobuf'                          
 #1510  74a75c9  profile  Interpreter(_hint='3.5')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity==5.0.1' 'protobuf==3.8.0'            
 #1511  b7d4b65  profile  Interpreter(_hint='3.5')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent==1.4.0' 'greenlet==0.4.14'  
 #1512  b4bf279  profile  Interpreter(_hint='3.5')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent'                            
 #1513  a08dd70  profile  Interpreter(_hint='3.6')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity' 'protobuf'                          
 #1514  cd4c4a1  profile  Interpreter(_hint='3.6')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity==5.0.1' 'protobuf==3.8.0'            
 #1515  16068e5  profile  Interpreter(_hint='3.6')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent==1.4.0' 'greenlet==0.4.14'  
 #1516  1c96ce3  profile  Interpreter(_hint='3.6')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent'                            
 #1517  1b15a30  profile  Interpreter(_hint='3.7')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity' 'protobuf'                          
 #1518  43cfbc2  profile  Interpreter(_hint='3.7')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity==6.0.0' 'protobuf==3.8.0'            
 #1519  102cf0a  profile  Interpreter(_hint='3.7')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent==1.4.0' 'greenlet==0.4.14'  
 #1520  5d6f54d  profile  Interpreter(_hint='3.7')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent'                            
 #1521  1ce356c  profile  Interpreter(_hint='3.8')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity' 'protobuf'                          
 #1522  f884c2b  profile  Interpreter(_hint='3.8')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity==7.0.0' 'protobuf==3.19.0'           
 #1523  139c624  profile  Interpreter(_hint='3.8')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent==20.6.1' 'greenlet==0.4.16' 
 #1524  db592df  profile  Interpreter(_hint='3.8')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent'                            
 #1525  14e4d18  profile  Interpreter(_hint='3.9')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity' 'protobuf'                          
 #1526  cedb415  profile  Interpreter(_hint='3.9')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity==7.0.0' 'protobuf==3.19.0'           
 #1527  48059c6  profile  Interpreter(_hint='3.9')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent==20.6.1' 'greenlet==0.4.16' 
 #1528  a157848  profile  Interpreter(_hint='3.9')   DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent'                            
 #1529  e28ff1d  profile  Interpreter(_hint='3.10')  DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity' 'protobuf'                          
 #1530  9b9a7f4  profile  Interpreter(_hint='3.10')  DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity==8.0.0' 'protobuf==3.19.0'           
 #1531  65c8aef  profile  Interpreter(_hint='3.10')  DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent==21.8.0' 'greenlet==1.1.0'  
 #1532  5f096ae  profile  Interpreter(_hint='3.10')  DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent'                            
 #1533  10625b5  profile  Interpreter(_hint='3.11')  DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity' 'protobuf'                          
 #1534  1f0a448  profile  Interpreter(_hint='3.11')  DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false                           'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'tenacity==8.2.0' 'protobuf==4.22.0'           
 #1535  8fe2e58  profile  Interpreter(_hint='3.11')  DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent==22.10.2'                   
 #1536  197d9d9  profile  Interpreter(_hint='3.11')  DD_TESTING_RAISE=1 DD_REMOTE_CONFIGURATION_ENABLED=false DD_PROFILE_TEST_GEVENT=1  'mock' 'pytest' 'pytest-mock' 'coverage' 'pytest-cov' 'opentracing' 'hypothesis<6.45.1' 'gunicorn'             
                                                                                                                                        'pytest-benchmark' 'py-cpuinfo~=8.0.0' 'uwsgi' 'pytest-asyncio' 'gunicorn' 'gevent'                            

```

</details>

### Changes in this PR:

- Profile jobs moved from tox into riot
- CircleCI config updated to:
    - Run profile suite with riot instead of tox
    - Remove all tox helpers/commands
    - Remove all profiling windows jobs (they were disabled anyways)
    - Increase parallelism of profiling jobs to 16 since there are 32 venvs so they divide evenly
- Scripts
    - run-tox-scenario was removed
    - ddtest was updated to not install tox
- Docs
    - References to tox have been removed
- setup.py
    - Custom tox test command class was removed, Tox was removed from tests_require
- tox.ini has been removed

### Considerations:

- We no longer are testing `test_uwsgi.py` with Python 2.7
    - I kept running into [bugs](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/33463/workflows/5b880db9-6aa1-46d6-8ef5-d0ece98d9a36/jobs/2259486?invite=true#step-105-494) that I could not debug/reproduce locally
    - This was only happening with uWSGI + Python 2.7, I figured the effort to resolve wasn't worth the added test coverage (I am happy to be challenged here)
- CI runtime for profile went from 18m to 12m
    - This is probably more from moving from 36 envs to 32 and changing parallelism
    - Workflow credit usage is about the same
- I tried to replicate the original tox envs as best I can, but there was some redundancy with "minreqs" envs and the "protobuf319" envs. We might be missing a few edge cases/variants, but I couldn't figure out any specific negative impact from the changed venvs.
- The riotfile for profiling is a little more complicated than other tests, this is because I decided to break out "latest" vs "minreqs" venvs instead of building a product of dependencies. This helped keep the total number of venvs down.
    - The command being different for Python 2.7 also meant the config was interesting to build.
- I haven't been able to run the full test suite locally, I have had issues with uWSGI installing on my M1 Mac, so almost _all_ of the validation was done in CircleCI only :/

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) are followed.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] PR description includes explicit acknowledgement/acceptance of the performance implications of this PR as reported in the benchmarks PR comment.

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.

### CODE REVIEW

**Review by emmettbutler — APPROVED** [review]
This is great. Once this is in 1.x, I recommend running `scripts/compile-and-prune-test-requirements` and pull requesting the result. Doing so will lock the new riot environments.

**Comment by brettlangdon** [comment]
> This is great. Once this is in 1.x, I recommend running `scripts/compile-and-prune-test-requirements` and pull requesting the result. Doing so will lock the new riot environments.

@emmettbutler do I need to do this step now as part of this PR? Do I have to wait for it to get merged into 1.x ?

**Comment by P403n1x87** [comment]
> > This is great. Once this is in 1.x, I recommend running `scripts/compile-and-prune-test-requirements` and pull requesting the result. Doing so will lock the new riot environments.
> 
> @emmettbutler do I need to do this step now as part of this PR? Do I have to wait for it to get merged into 1.x ?

I'd run it as part of this PR. This should make any potential backports easier to make. @emmettbutler do you agree?

**Comment by brettlangdon** [comment]
I have added the `.riot/requirements/*` files, but there were two that it failed to build because of an error with Gevent/Cython... it wasn't obvious to me why it was failing.

**Comment by emmettbutler** [comment]
I just committed the results of my local `compile-and-prune-test-requirements` run to this branch. I hope that's helpful!

**Review by emmettbutler — APPROVED** [review]

**Comment by brettlangdon** [comment]
> I just committed the results of my local `compile-and-prune-test-requirements` run to this branch. I hope that's helpful!

How did you end up with a bunch of different hashes than I did ?

**Comment by brettlangdon** [comment]
> > I just committed the results of my local `compile-and-prune-test-requirements` run to this branch. I hope that's helpful!
> 
> How did you end up with a bunch of different hashes than I did ?

We discussed this on a Zoom call. We aren't sure how this happened exactly. Spot checking the CircleCI job it appears that we have the requirements file for all the necessary hashes, so we are going to accept the right for now.

We have planned future improvements to automate/check this.

**Review by Yun-Kim — APPROVED** [review]
🎉

**Review by P403n1x87 — APPROVED** [review]

**Pull request merged**
