### PR TITLE
fix(redis): define result in _run_redis_command

### PR DESCRIPTION
**Pull request by dnguy078**
- This fix resolves an issue in redis utils where a variable may not be declared within a try/catch
- Relates to changes from https://github.com/DataDog/dd-trace-py/pull/9786, applying same logic to `_run_redis_command`
```

File "/lib/python3.12/site-packages/ddtrace/contrib/redis/patch.py", line 152, in _instrumented_execute_command
    return _run_redis_command(ctx=ctx, func=func, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
File "lib/python3.12/site-packages/ddtrace/contrib/redis/patch.py", line 136, in _run_redis_command
    rowcount = determine_row_count(redis_command=redis_command, result=result)
                                                                       ^^^^^^
UnboundLocalError: cannot access local variable 'result' where it is not associated with a value
```
## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by erikayasuda — APPROVED** [review]
LGTM, thanks for pushing the fix!

**Comment by dnguy078** [comment]
Thank you for the approval @erikayasuda , is there anything that needs to be done to resolve the `Codeowners` CI check ?

**Comment by erikayasuda** [comment]
> Thank you for the approval @erikayasuda , is there anything that needs to be done to resolve the `Codeowners` CI check ?

@dnguy078 The Codeowners check should have no issues, but it's not a required check so it shouldn't be a blocker for merging. Looks like the PR keeps getting outdated from main, which is why the merge keeps getting blocked.

The team is trying to improve this CI process, but for now I'll check up on this PR today to make sure we can get it in. Thanks for the patience!

**Comment by dnguy078** [comment]
Thank you @erikayasuda , would it be possible to apply the backport label 2.10 and 2.11 to this PR?

**Pull request merged**
