### PR TITLE
tests/aiohttp: yield back to the loop until complete

### PR DESCRIPTION
**Pull request by jd**
The current code might fail because the loop is only executed once; if one of the thread is late, its request won't be processed.

The call to `t.join()` has a timeout and has basically no effect here. It's now moved at the end of the waiting loop to be sure all threads are completed.

Since pytest would not catch an assertion failure in a thread, the assertion check for replies is moved to the main thread.

### CODE REVIEW

**Comment by jd** [comment]
This might help #876 but I'm not sure it's enough for now.

**Comment by jd** [comment]
This should be good; the problem was likely that we were checking the number of traces whereas there is a slight chance we get more than 1 trace. We want to check the number of spans instead.

**Comment by brettlangdon** [comment]
interesting, seems odd that we could get a variable number of traces, no?

**Comment by jd** [comment]
@DataDog/apm-python should we go ahead with this? It really fixes the issue here :)

**Pull request merged**
