### PR TITLE
chore(ci-visibility): add docstrings to pytest fixtures

### LINKED ISSUE #6143: pytest fixtures contain no docstrings
### Which version of dd-trace-py are you using?

ddtrace 1.14.0

### Which version of pip are you using?

pip 23.1.2

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>

```
alembic==1.11.1
amqp==5.1.1
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asn1crypto==1.5.1
asyncudp==0.10.0
attrs==23.1.0
Automat==22.10.0
b2sdk==1.21.0
Babel==2.12.1
bcrypt==4.0.1
beautifulsoup4==4.12.2
billiard==3.6.4.0
black==23.3.0
bleach==6.0.0
boto3==1.26.77
boto3-stubs==1.26.77
botocore==1.29.77
botocore-stubs==1.29.77
build==0.10.0
bytecode==0.14.2
cachetools==5.3.1
cattrs==23.1.2
cbor2==5.4.6
celery==5.2.7
celery-redbeat==2.1.1
celery-types==0.17.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
cmarkgfm==2022.10.27
coverage==7.2.7
cryptography==41.0.1
cssselect==1.2.0
cssutils==2.7.1
curlylint==0.13.1
datadog==0.45.0
ddsketch==2.0.4
ddtrace==1.14.0
Deprecated==1.2.14
disposable-email-domains==0.0.90
dnspython==2.3.0
doc8==1.1.1
docutils==0.19
elasticsearch==7.10.1
elasticsearch-dsl==7.4.1
email-validator==2.0.0.post2
envier==0.4.0
factory-boy==3.2.1
Faker==18.10.1
first==2.0.2
flake8==6.0.0
forcediphttpsadapter==1.0.2
freezegun==1.2.2
github_reserved_names==2023.5.2
google-api-core==2.11.0
google-auth==2.19.1
google-cloud-bigquery==3.11.0
google-cloud-core==2.3.2
google-cloud-storage==2.9.0
google-crc32c==1.5.0
google-resumable-media==2.5.0
googleapis-common-protos==1.59.0
greenlet==2.0.2
grpcio==1.55.0
grpcio-status==1.55.0
gunicorn==20.1.0
hiredis==2.2.3
html5lib==1.1
humanize==4.6.0
hupper==1.12
idna==3.4
importlib-metadata==6.0.1
importlib-resources==5.12.0
iniconfig==2.0.0
isort==5.12.0
itsdangerous==2.1.2
Jinja2==3.1.2
jmespath==1.0.1
jsonschema==4.17.3
kombu==5.2.4
limits==3.5.0
linehaul==1.0.1
logfury==1.0.1
lxml==4.9.2
Mako==1.2.4
MarkupSafe==2.1.3
mccabe==0.7.0
mirakuru==2.5.1
mistune==3.0.1
msgpack==1.0.5
msgpack-types==0.2.0
mypy==1.0.1
mypy-extensions==1.0.0
mypy-zope==0.9.1
natsort==8.3.1
opentelemetry-api==1.18.0
orjson==3.9.1
packaging==23.1
packaging-legacy==23.0
paginate==0.5.6
paginate-sqlalchemy==0.3.1
parsy==1.1.0
passlib==1.7.4
PasteDeploy==3.0.1
pathspec==0.11.1
pbr==5.11.1
pep8-naming==0.13.3
pip-api==0.0.30
pip-tools==6.13.0
plaster==1.1.2
plaster-pastedeploy==1.0.1
platformdirs==3.5.3
pluggy==1.0.0
port-for==0.6.3
premailer==3.10.0
pretend==1.0.9
prompt-toolkit==3.0.38
proto-plus==1.22.2
protobuf==4.23.2
psutil==5.9.5
psycopg2==2.9.6
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycodestyle==2.10.0
pycparser==2.21
pycurl==7.44.1
pydantic==1.10.9
pyflakes==3.0.1
Pygments==2.15.1
PyJWT==2.7.0
pymacaroons==0.13.0
PyNaCl==1.5.0
pyOpenSSL==23.2.0
pyparsing==3.0.9
pyproject_hooks==1.0.0
PyQRCode==1.2.1
pyramid==2.0.1
pyramid-debugtoolbar==4.10
pyramid-jinja2==2.10
pyramid-mailer==0.15.1
pyramid-mako==1.1.0
pyramid-retry==2.1.1
pyramid-rpc==0.8
pyramid-services==2.2
pyramid-tm==2.5
pyrsistent==0.19.3
pytest==7.3.2
pytest-postgresql==3.1.3
pytest-socket==0.6.0
python-dateutil==2.8.2
python-slugify==8.0.1
pytz==2023.3
pyupgrade==3.6.0
PyYAML==6.0
readme-renderer==37.3
redis==4.5.5
repoze.sendmail==4.4.1
requests==2.31.0
requests-aws4auth==1.2.3
responses==0.23.1
restructuredtext-lint==1.4.0
rfc3986==2.0.0
rsa==4.9
s3transfer==0.6.1
sentry-sdk==1.25.1
six==1.16.0
soupsieve==2.4.1
SQLAlchemy==2.0.16
stdlib-list==0.8.0
stevedore==5.1.0
stripe==5.4.0
structlog==23.1.0
tenacity==8.2.2
text-unidecode==1.3
tokenize-rt==5.1.0
toml==0.10.2
tqdm==4.65.0
transaction==3.1.0
translationstring==1.4
trove-classifiers==2023.5.24
typeguard==2.13.3
types-awscrt==0.16.19
types-babel==2.11.0.14
types-boto3==1.0.2
types-certifi==2021.10.8.3
types-first==2.0.5.1
types-html5lib==1.1.11.14
types-itsdangerous==1.1.6
types-passlib==1.7.7.12
types-psycopg2==2.9.21.10
types-pyOpenSSL==23.2.0.0
types-python-slugify==8.0.0.2
types-pytz==2023.3.0.0
types-PyYAML==6.0.12.10
types-redis==4.5.5.2
types-requests==2.31.0.1
types-s3transfer==0.6.1
types-setuptools==67.8.0.0
types-stdlib-list==0.8.3.2
types-stripe==3.5.2.10
types-urllib3==1.26.25.13
typing_extensions==4.6.3
ua-parser==0.16.1
urllib3==1.26.15
venusian==3.0.0
vine==5.0.0
waitress==2.1.2
wcwidth==0.2.6
webauthn==1.8.1
webencodings==0.5.1
WebOb==1.8.7
WebTest==3.0.0
whitenoise==6.4.0
wired==0.3
wrapt==1.15.0
WTForms==3.0.1
xmltodict==0.13.0
zipp==3.15.0
zope.deprecation==5.0
zope.event==4.6
zope.interface==6.0
zope.schema==7.0.1
zope.sqlalchemy==3.0
zxcvbn==4.4.28
```

</details>

### How can we reproduce your problem?

Run `python -m pytest --fixtures`

Refs https://docs.pytest.org/en/stable/reference/reference.html#command-line-flags

### What is the result that you get?

```shellsession
...
----------------------------- fixtures defined from ddtrace.contrib.pytest.plugin -----------------------------
ddspan -- ../lib/python3.11/site-packages/ddtrace/contrib/pytest/plugin.py:256
    no docstring available

ddtracer [session scope] -- ../lib/python3.11/site-packages/ddtrace/contrib/pytest/plugin.py:262
    no docstring available

patch_all [session scope] -- ../lib/python3.11/site-packages/ddtrace/contrib/pytest/plugin.py:269
    no docstring available
```

### What is the result that you expected?

A short docstring on each fixture that explains how to use it.

### PR DESCRIPTION
**Pull request by romainkomorndatadog**
Fixes #6143 by adding docstrings:

```
---... fixtures defined from ddtrace.contrib.pytest.plugin ...---
ddspan -- ../../go/src/github.com/DataDog/dd-trace-py/ddtrace/contrib/pytest/plugin.py:344
    Return the :class:`ddtrace.span.Span` instance associated with the
    current test when Datadog CI Visibility is enabled.

ddtracer [session scope] -- ../../go/src/github.com/DataDog/dd-trace-py/ddtrace/contrib/pytest/plugin.py:353
    Return the :class:`ddtrace.tracer.Tracer` instance for Datadog CI
    visibility if it is enabled, otherwise return the default Datadog tracer.

patch_all [session scope] -- ../../go/src/github.com/DataDog/dd-trace-py/ddtrace/contrib/pytest/plugin.py:363
    Patch all available modules for Datadog tracing when ddtrace-patch-all
    is specified in command or .ini.
```

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)
- [x] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [x] This PR doesn't touch any of that.

### CODE REVIEW

**Review by nikita-tkachenko-datadog — APPROVED** [review]

**Review by ericlaz — APPROVED** [review]

**Comment by romainkomorndatadog** [comment]
@miketheman , since you opened #6143 , it'd be great to get your rubber stamp. :)

**Review by mabdinur — APPROVED** [review]

**Review by miketheman — COMMENTED** [review]
Thanks!

My only critique is that the usage of sphinx-tags in the docstrings that are emitted to CLI are a little unclear if the reader is unfamiliar, but this is definitely an improvement.

**Comment by romainkomorndatadog** [comment]
@miketheman I uninspiredly matched https://github.com/pytest-dev/pytest/blob/main/src/_pytest/fixtures.py#L1363 to try and stay consistent with pytest's docstrings, but yeah, the markup isn't all that great from the CLI:

image

**Comment by miketheman** [comment]
@romainkomorndatadog agreed! Maybe someday pytest CLI will be smarter about stripping those out/formatting them better, in which case y'all won't have to change a thing! 🤞

**Pull request merged**
