### PR TITLE
fix(aiohttp): Remove strong reference to response object on callback (#8108)

### LINKED ISSUE #8108: Memory leak in aiohttp integration since v2.2.0
### Summary of problem

We noticed a huge memory leak after upgrading the `ddtrace` dependency in our application from v1.9.0 to v2.4.0. With Datadog tracing middleware enabled (`trace_app(...)`), the memory footprint of the Python process keeps increasing as requests come in, and this keeps going and going until the process runs out of memory.

### Which version of dd-trace-py are you using?

Any version since v2.2.0 seems to exhibit the issue, and v2.1.9 does not.

### Which version of pip are you using?

23.2.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
aiohttp==3.9.1
aiosignal==1.3.1
attrs==23.2.0
bytecode==0.15.1
cattrs==23.2.3
ddsketch==2.0.4
ddtrace==2.4.0
Deprecated==1.2.14
envier==0.5.0
frozenlist==1.4.1
idna==3.6
importlib-metadata==6.11.0
multidict==6.0.4
opentelemetry-api==1.22.0
protobuf==4.25.2
setuptools==69.0.3
six==1.16.0
typing_extensions==4.9.0
wrapt==1.16.0
xmltodict==0.13.0
yarl==1.9.4
zipp==3.17.0
</details>

### How can we reproduce your problem?

Install aiohttp (v3.9.1) and ddtrace, and then start the following trivial app:
```python
from aiohttp import web
from ddtrace import tracer
from ddtrace.contrib.aiohttp import trace_app


async def hello(request):
    return web.Response(text="Hello, world")

app = web.Application()
app.add_routes([web.get('/', hello)])
tracer.configure(enabled=False)
trace_app(app, tracer, service="aiohttp-web")
web.run_app(app, host="0.0.0.0", port=8800)
```

Then keep hitting it with a lot of requests and watch the memory footprint grow in a linear fashion without bounds. On v2.1.9 and earlier, I've observed the memory footprint to plateau at around 44 MB.

### What is the result that you get?

The memory footprint of the process grows without bounds.

### What is the result that you expected?

The memory footprint plateaus after a while.

### PR DESCRIPTION
**Pull request by seandstewart**
The previous implementation added a lambda which held a reference to the response object to the request task, creating a strong reference to the request object which could lead to a memory leak, because the request and response cannot be garbage collected until the task itself is.

This reworks the middleware to store the request span in a context var and use only that context var for the task callback, ensuring that the request and response objects can be freed from memory even if the underlying task has not been garbage collected.

I haven't been able to get my local environment working correctly, so I have not been able to test this behavior to ensure correctness.

Attempts to resolve #8108

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Comment by seandstewart** [comment]
Failed test is for the botocore integration, which was not impacted by this change.

**Comment by wantsui** [comment]
Hi @seandstewart, thanks for contributing this PR! 

Just as a heads up, I'm duplicating this PR so the rest of the test suite runs:  https://github.com/DataDog/dd-trace-py/pull/11518 ! I'm also reviewing this PR to get this merged in.

**Comment by sanchda** [comment]
Looks like this was duplicated in #11518.  I'm going to go ahead and close this out, but the author's code changes are being taken.  Thank you very much for the contribution!!

**Comment by wantsui** [comment]
Just a heads up that I closed the cloned version of this PR in favor of @ZStriker19 's https://github.com/DataDog/dd-trace-py/pull/12081 .

**Pull request closed without merging**
