### PR TITLE
fix(grpc): ensure grpc.intercept_channel is unpatched properly

### PR DESCRIPTION
**Pull request by ysk24ok**
## Commit Message

{{title}}

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Comment by brettlangdon** [comment]
@ysk24ok great catch, thanks!

Would you also be able to add a release note for this change?

```
$ pip install reno
$ reno new <slug-for-note>
```

This would be a `fixes:` note.

**Comment by ysk24ok** [comment]
@brettlangdon Thank you for your review. Added a release note. Could you take a look?

**Review by brettlangdon — APPROVED** [review]
hey @ysk24ok

**Review by Kyle-Verhoog — APPROVED** [review]

**Comment by brettlangdon** [comment]
@Mergifyio backport 0.57

**Comment by brettlangdon** [comment]
This has been released in `ddtrace==0.57.1`

**Pull request merged**
