### PR TITLE
chore(tracing/aiohttp_jinja2): automatically enable aiohttp_jinja2 tracing on its own

### PR DESCRIPTION
**Pull request by brettlangdon**
aiohttp_jinja2 used to be included in the aiohttp integration. In #3356 the aiohttp_jinja2 integration was separated into its own integration but kept in the testsuite of aiohttp. For backwards compatibility aiohttp_jinja2 was still enabled using the aiohttp integration. Both of these combined this led to a bug that went uncaught by the testsuite which was fixed in #3449.

To avoid further issues and to be consistent with the rest of the library the aiohttp_jinja2 is separated further out with its test suite and is no longer enabled via aiohttp so now the two integrations are independent.

### CODE REVIEW

**Comment by brettlangdon** [comment]
@Mergifyio backport 1.0

**Review by mabdinur — APPROVED** [review]

**Review by majorgreys — COMMENTED** [review]
We should add separate test suite for `aiohttp_jinja2` and similarly modify the `aiohttp` test suite for when `aiohttp_jinja2` is not installed.

**Comment by brettlangdon** [comment]
> We should add separate test suite for `aiohttp_jinja2` and similarly modify the `aiohttp` test suite for when `aiohttp_jinja2` is not installed.

Yes, I wasn't sure how intertwined it was. But worth revisiting before merging.

**Comment by Kyle-Verhoog** [comment]
Yeah we should be able to separate out the aiohttp tests to at least its own module (probably not worth doing an entire other suite for it though)

**Comment by brettlangdon** [comment]
```
ImportError while loading conftest '/root/project/tests/contrib/aiohttp/conftest.py'.
tests/contrib/aiohttp/conftest.py:2: in <module>
    import aiohttp_jinja2
E   ModuleNotFoundError: No module named 'aiohttp_jinja2'
```

**Review by brettlangdon — COMMENTED** [review]
👍🏻

**Review by brettlangdon — COMMENTED** [review]
lgtm

**Review by majorgreys — APPROVED** [review]
Technically, we should label this PR as a `feat` rather than a chore/refactor.

**Pull request merged**
