### PR TITLE
chore(ci): increase parallel test runners on CI

### PR DESCRIPTION
**Pull request by Yun-Kim**
## Description
This PR updates our circleCI configuration to increase the number of parallel test runners for the following test suites:
- opentracer: 10 min --> 5 min
- ddtracerun: 9 min --> 7 min
- test_logging:  11 min --> 3 min
- asgi: 12 min --> 4 min
- fastapi: 9 min --> 4 min
- graphql: 10 min --> 4 min
- pyramid: 12 min --> 3 min
- rediscluster: 10 min --> 3 min
- benchmarks: 12 min --> 6 min
- mako: 9 min --> 3 min
- aiohttp: 13 min --> 8 min
- aiobotocore: 11 min --> 8 min

## Checklist
- [ ] Followed the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) when writing a release note.
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added and follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines), or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.

### CODE REVIEW

**Comment by Kyle-Verhoog** [comment]
I wonder if at this point, more runners is just going to be more expensive/contentious and we don't get any significant gains because the profiling job is still the longest.

@Yun-Kim should we just increase the parallelism for profiling further?

**Comment by Yun-Kim** [comment]
> I wonder if at this point, more runners is just going to be more expensive/contentious and we don't get any significant gains because the profiling job is still the longest.

Yup, the profiling job is the bottleneck right now, but since #4591 is already open and should theoretically speed it up once merged, we might as well hit the next longest-running jobs. 

> @Yun-Kim should we just increase the parallelism for profiling further?

I was thinking moving profile tests to riot should give us the largest speed improvements first before increasing parallelism. Should we prioritize this one to be merged first? @mabdinur do you need any assistance getting this one through?

**Comment by mabdinur** [comment]
> > I wonder if at this point, more runners is just going to be more expensive/contentious and we don't get any significant gains because the profiling job is still the longest.
> 
> @Kyle-Verhoog yup, the profiling job is the bottleneck right now, but since #4591 is already open and should theoretically speed it up once merged, I thought we might as well hit the next longest-running jobs.
> 
> > @Yun-Kim should we just increase the parallelism for profiling further?
> 
> I was thinking moving profile tests to riot should give us the largest speed improvements first before increasing parallelism. Should we prioritize #4591 to be merged first? @mabdinur do you need any assistance getting this one through?

A few tests which run a uwsgi app in a subprocess are failing on python 2.7.  I documented the error and added next steps to the PR description. Feel free to make changes/close that PR.

**Review by P403n1x87 — APPROVED** [review]

**Comment by Yun-Kim** [comment]
Closing this as we've made some other CI optimizations to tox test suites that make some of these changes unnecessary. If we need to make any more speed ups on CI I'll open a new PR.

**Pull request closed without merging**
