### PR TITLE
fix(debugging): use the correct span decoration probe type name

### LINKED ISSUE #6415: DI - Unsupported probe type: SPAN_DECORATION_PROBE
### Summary of problem

Cannot create "Span Probe" or "Span Tag Probe". 

### Which version of dd-trace-py are you using?

1.16.1

### Which version of pip are you using?
23.1.2

### Which libraries and their versions are you using?

on request

### How can we reproduce your problem?

Run ddtrace in Django application and try attach span probes

### What is the result that you get?

If I run 

```bash
DD_TRACE_DEBUG=1 ./runserver
```

I see the probes try to be attached with the following error:

```
Traceback (most recent call last):
  File "/data/virtualenv/virtenv-001/lib/python3.8/site-packages/ddtrace/internal/remoteconfig/_subscribers.py", line 49, in _worker
    self._get_data_from_connector_and_exec()
  File "/data/virtualenv/virtenv-001/lib/python3.8/site-packages/ddtrace/internal/remoteconfig/_subscribers.py", line 43, in _get_data_from_connector_and_exec
    self._exec_callback(data, test_tracer=test_tracer)
  File "/data/virtualenv/virtenv-001/lib/python3.8/site-packages/ddtrace/debugging/_probe/remoteconfig.py", line 322, in _exec_callback
    self._update_probes_for_config(metadatas[idx]["id"], rc_configs[idx])
  File "/data/virtualenv/virtenv-001/lib/python3.8/site-packages/ddtrace/debugging/_probe/remoteconfig.py", line 345, in _update_probes_for_config
    {probe.probe_id: probe for probe in get_probes(config_id, config)} if config not in (None, False) else {}
  File "/data/virtualenv/virtenv-001/lib/python3.8/site-packages/ddtrace/debugging/_probe/remoteconfig.py", line 116, in _wrapper
    return [_ for _ in f(*args, **kwargs) if _match_env_and_version(_)]
  File "/data/virtualenv/virtenv-001/lib/python3.8/site-packages/ddtrace/debugging/_probe/remoteconfig.py", line 275, in get_probes
    return [build_probe(config)]
  File "/data/virtualenv/virtenv-001/lib/python3.8/site-packages/ddtrace/debugging/_probe/remoteconfig.py", line 269, in build_probe
    raise ValueError("Unsupported probe type: %s" % _type)
ValueError: Unsupported probe type: SPAN_DECORATION_PROBE
```

I see that in the ddtrace code https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/debugging/_probe/model.py#L304 there is reference to value `SPAN_DECORATE_PROBE` which doesn't match to what I assume is the correct value of `SPAN_DECORATION_PROBE` therefore no probe is being attached

### What is the result that you expected?

Able to attach probes

### PR DESCRIPTION
**Pull request by P403n1x87**
Fixed the name of the type of span decoration probes that is used in remote configuration payloads which did not match what the library was expecting.

Fixes #6415.

## Testing Strategy

Automated testing requires a mocking of RCM and the payloads that it delivers. This will be implemented in future work with system tests.

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by Yun-Kim — COMMENTED** [review]
Could we add a regression test? Otherwise LGTM

**Comment by P403n1x87** [comment]
> Could we add a regression test? Otherwise LGTM

We would need an entire mock of RCM for that. These will come with system tests which are WIP.

**Review by mabdinur — APPROVED** [review]

**Review by brettlangdon — APPROVED** [review]

**Comment by brettlangdon** [comment]
Regression test?

**Comment by P403n1x87** [comment]
> Regression test?

System tests [WIP]

**Pull request merged**
