### PR TITLE
Create test for empty middleware

### LINKED ISSUE #1021: Django middleware not properly supported if left empty
In Django 1.10 and above, `dd-trace-py` will attempt to check first if the user is using the `MIDDLEWARE` Django setting and will fallback to `MIDDLEWARE_CLASSES` if unset. In my application, I deliberately declare an empty list for the `MIDDLEWARE` setting to tell Django that I am not personally putting any middleware into the application. Unfortunately, `dd-trace-py` simply checks if the `settings.MIDDLEWARE` attribute is falsy and since this is true it then falls back to `MIDDLEWARE_CLASSES`.

If an empty list/tuple is declared in Django settings for `MIDDLEWARE`, it should still be properly injected.

### PR DESCRIPTION
**Pull request by ryanwilsonperkin**
Fixes #1021 

When trying to find the insertion point for injecting middleware, only fallback to `MIDDLEWARE_CLASSES` if `MIDDLEWARE` is `None`. If not, it may be another falsey value like `[]` or `tuple()` indicating that the Django application itself does not install any middleware.

### CODE REVIEW

**Comment by ryanwilsonperkin** [comment]
Tried doing this in a TDD fashion and expected the second commit to fix the test failures in the first, however it seems that it's still failing on the same issue and I wonder if the `override_settings` isn't working properly because of the `django.setup()` in the `setUp`. Any thoughts from the maintainers on how to structure this test better?

**Comment by ryanwilsonperkin** [comment]
Thanks @brettlangdon. I'm going to try to get the tests set up to run locally (Django at least) and see if I can debug this.

**Comment by ryanwilsonperkin** [comment]
Hey @brettlangdon, I've managed to get the Django tests failing-then-working as expected by adding the new test for functionality and then patching it. Unfortunately it looks like the `mongoengine` tests are broken and I suspect that's for a different reason? Any idea what might be going wrong [here](https://circleci.com/gh/DataDog/dd-trace-py/144051)?

**Comment by brettlangdon** [comment]
@ryanwilsonperkin yeah, ignore `mongoengine`, I am working on those... `pymongo==3.9` broke ALL the things :)

**Comment by brettlangdon** [comment]
also, awesome, I slotted this for next release, we'll try to get around to giving it a good review and merged in soon!

**Comment by ryanwilsonperkin** [comment]
Lovely, thanks!

**Comment by brettlangdon** [comment]
I just updated from `master` which should fix the Mongo test failures, then after a ✔️ we can merge.

**Pull request merged**
