### PR TITLE
chore(asyncpg): skip incompatible framework test

### PR DESCRIPTION
**Pull request by mabdinur**
## Description

The following tests asserts an asyncpg connection is garbage collected. This test is incompatible with the profiler and should be skipped: [test_no_explicit_close_with_debug](https://github.com/MagicStack/asyncpg/blob/master/tests/test_connect.py#L1730)

## Checklist
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.

### CODE REVIEW

**Review by Kyle-Verhoog — CHANGES_REQUESTED** [review]
what change caused this? is this a new test in the asyncpg suite or a change we made to the profiler?

**Comment by mabdinur** [comment]
> what change caused this? is this a new test in the asyncpg suite or a change we made to the profiler?

@jd do you know of any recent changes that would have caused this test to fail?

**Comment by Kyle-Verhoog** [comment]
@mabdinur how do we know it's profiling related?

**Comment by Kyle-Verhoog** [comment]
image
looks like there was a change in asyncpg but I haven't looked yet to see if it's flaky on their side too or if ddtrace is responsible.

**Comment by Kyle-Verhoog** [comment]
seems like it could be #4125 based on @Yun-Kim and I's findings. It lines up with the CI starting to flake too.

**Comment by Yun-Kim** [comment]
Failing framework test fixed by #4448.

**Pull request closed without merging**
