### PR TITLE
docs: add Gunicorn/gevent support documentation

### PR DESCRIPTION
**Pull request by jd**

### CODE REVIEW

**Review by Kyle-Verhoog — APPROVED** [review]

**Review by majorgreys — DISMISSED** [review]

**Comment by Kyle-Verhoog** [comment]
```
/home/circleci/project/docs/advanced_usage.rst:517: Spell check: Gunicorn: Gunicorn.
```

**Review by majorgreys — DISMISSED** [review]
LGTM other than release notes

**Review by brettlangdon — APPROVED** [review]

**Comment by majorgreys** [comment]
@brettlangdon Users of the library reviewing the release notes would benefit from learning about this documentation. If you are currently using `ddtrace-run` with `gunicorn` and you haven't noticed issues with `gevent` patching, you would otherwise not consult the documentation to change your environment variable.

**Comment by brettlangdon** [comment]
> @brettlangdon Users of the library reviewing the release notes would benefit from learning about this documentation. If you are currently using `ddtrace-run` with `gunicorn` and you haven't noticed issues with `gevent` patching, you would otherwise not consult the documentation to change your environment variable.

That is a good point.

**Comment by brettlangdon** [comment]
did we not add one with the `DD_GEVENT_PATCH_ALL` change/PR?

**Review by brettlangdon — APPROVED** [review]

**Review by P403n1x87 — APPROVED** [review]

**Pull request merged**
