### PR TITLE
Added py.typed for ddtrace

### LINKED ISSUE #951: mypy stub files
mypy throws an error when ddtrace is in use:

image

It would be nice if this library could ship with stub files or be put on https://github.com/python/typeshed. I'm not sure how to do that yet but maybe someone here is.

More info from mypy side here https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports

### PR DESCRIPTION
**Pull request by Yun-Kim**
## Description
Added `py.typed` file to publish mypy type hinting for ddtrace.

Resolves #951

### CODE REVIEW

**Review by brettlangdon — APPROVED** [review]

**Review by Kyle-Verhoog — APPROVED** [review]

**Review by mabdinur — APPROVED** [review]
LGMT

**Comment by gitpushdashf** [comment]
Not seeing this in 0.51.0. Should it be in there?

**Comment by Kyle-Verhoog** [comment]
Ah I think it got merged just after the cutoff for 0.51. We can backport it to 0.51 quite easily though 🙂 

@mergifyio backport 0.51

**Comment by gitpushdashf** [comment]
Awesome, thank you!

**Comment by Kyle-Verhoog** [comment]
@gitpushdashf I just kicked off the release for 0.51.1 with this change for ya. Should be up on PyPI shortly 🙂

**Pull request merged**
