### PR TITLE
chore(ci): ensure we wait on graphene and internal for code coverage

### PR DESCRIPTION
**Pull request by brettlangdon**
Before this meant we might have generated code coverage without first having graphene and internal test results.

In practice, this probably didn't occur since graphene and internal are not the slowest tests that we have so we'd likely always have the coverage results from them

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- ~Testing strategy is described if automated tests are not included in the PR.~
- ~Risk is outlined (performance impact, potential for breakage, maintainability, etc).~
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) are followed.
- ~Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).~
- [x] Author is aware of the performance implications of this PR as reported in the benchmarks PR comment.

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer is aware of, and discussed the performance implications of this PR as reported in the benchmarks PR comment.

### CODE REVIEW

**Comment by P403n1x87** [comment]
We can't cook up a smart way to keep this in sync with the rest of the config, can we? (I think `debugger` is also missing? 🤔 )

**Comment by brettlangdon** [comment]
> We can't cook up a smart way to keep this in sync with the rest of the config, can we? (I think `debugger` is also missing? 🤔 )

Unless we do config generation which I know Christophe played with before.

I think the risk/concerns are pretty low though. The impact is codecov doesn't have 100% of the information to give us an accurate coverage report.... 🤷🏻

**Comment by brettlangdon** [comment]
> I think debugger is also missing?

it is there, there aren't all alphabetical 🙄

**Review by Yun-Kim — APPROVED** [review]

**Review by Yun-Kim — APPROVED** [review]
This isn't in the scope of this PR but I would really love if we could put lists like this in alphabetical order so we can avoid missing problems like this.

**Comment by P403n1x87** [comment]
> > I think debugger is also missing?
> 
> it is there, there aren't all alphabetical 🙄

oh 🤦 sorry I should have not assumed alphabetical ordered!

**Review by P403n1x87 — APPROVED** [review]

**Review by emmettbutler — APPROVED** [review]

**Pull request merged**
