### PR TITLE
Test with Python 3.10 dev build

### PR DESCRIPTION
**Pull request by brettlangdon**

### CODE REVIEW

**Comment by brettlangdon** [comment]
Oh boy is `riot` + `select_pys` so much better at updating than `tox` 😆

**Comment by brettlangdon** [comment]
lot of test failures, but a lot of them are "connection refused" so hard to tell if the problem is 3.10

**Review by Kyle-Verhoog — COMMENTED** [review]
All of our async tests are going to fail since we use https://docs.python.org/3/library/asyncio-task.html#asyncio.coroutine extensively 😕

**Comment by brettlangdon** [comment]
> All of our async tests are going to fail since we use https://docs.python.org/3/library/asyncio-task.html#asyncio.coroutine extensively 😕

ah... yeah...

**Comment by jd** [comment]
We should be able replace `asyncio.coroutine` with `async/await` since this has been introduced in Python 3.5 IIRC.

**Comment by jd** [comment]
We don't have to support Python 2 for this :) I started in #2285

**Comment by brettlangdon** [comment]
the tests failing now are all `riot` since `tox` will ignore missing python versions, but `riot` does not.

**Pull request closed without merging**
