### PR TITLE
LICENSE: Fix copyright holder notice

### PR DESCRIPTION
**Pull request by underyx**
Just noticed you forgot to fill in this notice.

### CODE REVIEW

**Comment by underyx** [comment]
While we're here, maybe you could help me understand if it's okay for us to copy your monkey-patching architecture like this? https://github.com/kiwicom/kiwi-platform-py/pull/15/files

I'm not sure if adapting the source also requires the BSD notice to be added, or it's just about full redistributions.

**Comment by underyx** [comment]
Oh hi Julien! 😄

Maybe any idea about https://github.com/DataDog/dd-trace-py/pull/977#issuecomment-505832227?

**Comment by jd** [comment]
@underyx IANAL though you should probably add a notice that states where this comes from and the license for it at least in the file where you copied the code. That should avoid any issue in the future. :)

**Comment by brettlangdon** [comment]
@underyx if you are re-using our code, then it must include our copyright and BSD3 license.

**Pull request merged**
