### PR TITLE
Update error event handler name within SQLAlchemy engine

### PR DESCRIPTION
**Pull request by RobertTownley**
Resolves issue #841 (SQLAlchemy: ConnectionEvents.dbapi_error() event is deprecated)

**Background**
The `ddtrace` library's sqlalchemy engine currently listens for the `dbapi_error` event. This throws a deprecation warning within sqlalchemy, as mentioned in the above issue.

**Solution**
This PR changes the name of the event being listened for from `dbapi_error` to `handle_error`.

Reference to the new `handle_error` event within SQLAlchemy: https://docs.sqlalchemy.org/en/13/core/events.html#sqlalchemy.events.ConnectionEvents.handle_error

### CODE REVIEW

**Comment by RobertTownley** [comment]
Ah my apologies: if the test runner is any indication, this wasn't the easy fix I was crossing my fingers towards :) I'll take another swing at this in a bit

**Comment by Kyle-Verhoog** [comment]
@RobertTownley no worries! Thanks for the contribution.

My guess (without looking into this at all) is that we want to put a flag in to use the `dbapi_error` for `sqlalchemy <= version X` (where it was deprecated) and then use `handle_error` for `> version X`. 

I'll take a look later 😄

**Comment by RobertTownley** [comment]
@Kyle-Verhoog I wrote a dumb check against the sqlalchemy version # to determine the name of the event to listen for. The # of params changes depending on the event, but since none of them are used, I figured that we can handle it with an expanded `*args`

That got the sqlalchemy tests passing, but something about the AWS testing step is unhappy. Any clues as to why that might be?

**Comment by Kyle-Verhoog** [comment]
Hi @RobertTownley, yeah test failing isn't your fault. Looks like a new version of aiobotocore got released that we're incompatible with 😕. We'll see to getting that resolved so that we can merge this 😄

**Comment by RobertTownley** [comment]
Ah good to hear (well, not "good", but... y'know). Anyway, thanks for the quick review, good luck with the boto stuff, and I'll keep an eye out for the merge / new version

**Pull request merged**
