### PR TITLE
chore(subprocess): add patch tests, enable running tests on CI

### PR DESCRIPTION
**Pull request by Yun-Kim**
This PR adds patch test cases for the subprocess integration so that it will not cause the patch test file precheck job introduced by #6496 to fail. Note that this PR simply enables running subprocess integration tests on CI and generates the patch test cases, a future PR is necessary to implement the patch test assertions and fix the failing tests.

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by emmettbutler — DISMISSED** [review]
You'll also want to make sure the subprocess suite is included in all of the related suitespecs in `.suitespec.json`.

**Review by gnufede — APPROVED** [review]

**Comment by juanjux** [comment]
@Yun-Kim 

The two failing subprocess tests have been fixed so this should be merge-able now. I will add a further PR with the boilerplate tests in this PR implemented once it's merged.

**Review by juanjux — DISMISSED** [review]

**Review by emmettbutler — DISMISSED** [review]

**Comment by Yun-Kim** [comment]
Hey @juanjux, thanks for fixing the tests! 

I think we may need to implement the patch test assertions in this PR as otherwise this fails with the current boilerplate code. Feel free to take over this PR 😄

**Comment by juanjux** [comment]
Will do, thanks!

**Comment by juanjux** [comment]
I'm finding some problems which I think are related to the base class patch suite have the `@run_in_subprocess` decorator which makes `subprocess` being imported before being patched. I'm going to run some experiments on CI (can't reproduce some of the problems locally) and thus setting this to draft for now.

**Comment by juanjux** [comment]
@Yun-Kim  PR updated. I disabled some auto generated tests because they use the `@run_in_subprocess` decorator and this conflicts with the patching since it imports the module before it can be patched but there are also unittests testing it. PTAL.

**Review by majorgreys — APPROVED** [review]

**Pull request merged**
