### PR TITLE
fix(dbapi): add iterable methods to object proxy

### LINKED ISSUE #4143: TracedSQLiteCursor should implement SQLite iteration
### Which version of dd-trace-py are you using?

`datadog==0.41.0` and `datadog-lambda==3.60.0`

### Which version of pip are you using?

21.1.3

### Which version of the libraries are you using?

Complete `pip3 freeze` output:

```
attrs==22.1.0
awslambdaric==2.0.4
boto3==1.24.12
botocore==1.27.53
certifi==2022.6.15
chardet==5.0.0
charset-normalizer==2.1.0
datadog==0.41.0
datadog-lambda==3.60.0
ddtrace==0.61.2
decorator==5.1.1
future==0.18.2
idna==3.3
jmespath==1.0.1
mapbox-vector-tile==1.2.1
packaging==21.3
pmtiles==2.0.0
protobuf==3.20.1
pyclipper==1.3.0.post3
pyparsing==3.0.9
pyproj==3.3.1
python-dateutil==2.8.2
requests==2.28.1
s3transfer==0.6.0
sentry-sdk==1.8.0
Shapely==1.8.2
simplejson==3.17.2
six==1.16.0
tenacity==8.0.1
urllib3==1.26.11
wrapt==1.14.1
```

### How can we reproduce your problem?

Run a SQLite query and [use the result of `conn.execute()` as an iterator](https://docs.python.org/3/library/sqlite3.html#cursor-objects):

    row = next(conn.execute('select * from table'))

We are working around this bug by not using SQlite’s iterator feature:

    res = conn.execute('select * from table')
    row = res.fetchone()

### What is the result that you get?

```
ProcessUploadException: 'TracedSQLiteCursor' object is not an iterator
  File "/var/task/lib/python3.9/site-packages/sentry_sdk/integrations/aws_lambda.py", line 164, in sentry_handler
  File "/var/task/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise
  File "/var/task/lib/python3.9/site-packages/sentry_sdk/integrations/aws_lambda.py", line 155, in sentry_handler
  File "/var/task/lib/python3.9/site-packages/datadog_lambda/wrapper.py", line 143, in __call__
  File "/var/task/felt_pipeline/library/instantiate_sentry.py", line 76, in decorated
  File "/var/task/felt_pipeline/lambdas/pipeline_create_feature_tiles.py", line 70, in lambda_handler
  File "/var/task/felt_pipeline/lambdas/pipeline_create_feature_tiles.py", line 109, in mbtiles_convert
```

### What is the result that you expected?

One row from the SQLite table.

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
According to the [dbapi spec](https://peps.python.org/pep-0249/#iter)
cursors can be iterable. For some reason wrapt.ObjectProxy does not
proxy the `__iter__` or `__next__` methods. The solution is to simply
add them to the base TraceCursor class which is used in our dbapi
integrations.

Fixes #4143

### CODE REVIEW

**Review by jd — APPROVED** [review]

**Review by majorgreys — APPROVED** [review]
Do we need to do the same with the wrapping we do in other non-dbapi integrations? 

We are now doing the same proxying in multiple places. We should be able to add an internal utility class to reuse.

**Comment by Kyle-Verhoog** [comment]
> We are now doing the same proxying in multiple places. We should be able to add an internal utility class to reuse.

yeah we've run into this a few times now, it's worth following up by subclassing/extending ObjectProxy to have these methods

**Comment by P403n1x87** [comment]
> > We are now doing the same proxying in multiple places. We should be able to add an internal utility class to reuse.
> 
> yeah we've run into this a few times now, it's worth following up by subclassing/extending ObjectProxy to have these methods

Just a thought: would the new internal wrapping stuff help with these sorts of issues?

**Comment by Kyle-Verhoog** [comment]
> would the new internal wrapping stuff help with these sorts of issues?

yes! if we just patch the methods we need to and leave the object as-is then these issues are avoided as well

**Comment by mabdinur** [comment]
@Mergifyio backport 1.5

**Comment by mabdinur** [comment]
@Mergifyio backport 1.5

**Comment by mabdinur** [comment]
@Mergify backport 1.5

**Pull request merged**
