### PR TITLE
test: add pytest-mock to default packages for riot

### PR DESCRIPTION
**Pull request by brettlangdon**
## Description
This is a package we currently install by default in `tox`, would be nice to also make available to `riot` venvs.

`pytest-mock`'s biggest benefit is adding `mocker` fixture for pytest functions which will auto-cleanup/reset any mocking at the end of the test execution.

### CODE REVIEW

**Review by majorgreys — APPROVED** [review]

**Review by Kyle-Verhoog — COMMENTED** [review]
a motivation of why we need this (seems unnecessary right now) would be good

**Comment by brettlangdon** [comment]
> a motivation of why we need this (seems unnecessary right now) would be good

@Kyle-Verhoog I updated the description, let me know what you think

**Comment by P403n1x87** [comment]
Does this mean that we should consider using the `mocker` fixture with new tests going forward?

**Comment by brettlangdon** [comment]
> Does this mean that we should consider using the `mocker` fixture with new tests going forward?

I was thinking it was more of a "and now you can if you want", but `mocker` is nice, would be worth considering using it going forward

**Review by P403n1x87 — APPROVED** [review]

**Pull request merged**
