### PR TITLE
Auto-instrument Django with WSGI middleware

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
## Description

Auto-instrument Django's `get_wsgi_application` with `DDWSGIMiddleware`. This feature also enables the tracing of [`StreamingHttpResponse`](https://docs.djangoproject.com/en/3.1/ref/request-response/#django.http.StreamingHttpResponse)s which was not previously possible by just patching Django.

Dependent on #1808.

The app in https://github.com/DataDog/trace-examples/pull/106 is also used to test this feature.

image

## Checklist
- [ ] Ensure distributed tracing is correct when using the WSGI middleware with web framework integrations.
- [ ] Use span_modifier to set resource, service
- [x] Entry added to release notes using [reno](https://docs.openstack.org/reno/latest/user/usage.html)
- [x] Tests provided; and/or
- [x] Description of manual testing performed and explanation is included in the code and/or PR.
- [x] ~Library documentation is updated.~
- [x] ~[Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).~

### CODE REVIEW

**Review by brettlangdon — COMMENTED** [review]
How does this help/hurt existing issues of bubbling metadata to the trace root span (including but not limited to, stack traces)?

Is there any place in django where we explicitly grab and root span and modify it?

**Comment by Kyle-Verhoog** [comment]
@brettlangdon the django integration doesn't reach for the root span at all so there shouldn't be issues there. However something that is going to get messy is how to deal with distributed tracing. One approach might be to strip the tracing headers out of the request in the WSGI/ASGI middlewares so that they aren't consumed downstream by Django.

**Comment by brettlangdon** [comment]
Does this WSGI middleware provide any additional visibility or benefit to the Django integration?

Should we just use this WSGI middleware as a reusable helper across all web apps?

**Comment by Kyle-Verhoog** [comment]
> Does this WSGI middleware provide any additional visibility or benefit to the Django integration?


From the PR description:

> This feature also enables the tracing of StreamingHttpResponses which was not previously possible by just patching Django.


> Should we just use this WSGI middleware as a reusable helper across all web apps?

Yes that's the plan

**Comment by brettlangdon** [comment]
Sorry, not sure how I glossed over that in the description....

this will change the service root operation name though, meaning people's links/dashboards/monitors might break.

We probably need to figure out how to make this change more carefully, e.g. probably need to introduce `_dd.measured: 1` for the `django.request` spans to ensure we continue to compute metrics from that span.

Can we make it so the `wsgi.request` is actually just the `django.request` span?

If we did that, probably means we need a way to bubble up django specific metadata into that span, but might be the safer way to handle this change, changing the structure of the trace (at least who the root span is) can cause issues... might be better off avoiding if we can.

**Comment by Kyle-Verhoog** [comment]
> We probably need to figure out how to make this change more carefully, e.g. probably need to introduce _dd.measured: 1 for the django.request spans to ensure we continue to compute metrics from that span.

We actually don't do this currently. So for anyone to actually have their Django spans measured now have to add a retention filter in the app. Which should continue to work no matter the trace shape I believe?

> Can we make it so the wsgi.request is actually just the django.request span?
A couple issues with this:

1. It's not true. The WSGI handling is done by the WSGI server, not django, as seen with StreamingHttpResponses

2. It would still mess up metrics/monitors because now the request is going to encompass a larger time span from before.

It might just have to be a breaking change that we disclaim in the release notes.

**Comment by Kyle-Verhoog** [comment]
Going to close this for now as there isn't a non-breaking way to introduce instrumenting Django by default with the WSGI integration.

Users are free to use the WSGI integration to wrap their Django app and gain the additional visibility if desired.

**Pull request closed without merging**
