### PR TITLE
fix(tracing): disable connection reuse by default

### PR DESCRIPTION
**Pull request by majorgreys**
Disable connection reuse by default added as a performance optimization in #2999.

### CODE REVIEW

**Comment by majorgreys** [comment]
@Mergifyio backport 1.x 0.60

**Review by mabdinur — APPROVED** [review]

**Review by brettlangdon — CHANGES_REQUESTED** [review]
We should update the release note: https://github.com/DataDog/dd-trace-py/blob/f8ed932c0/releasenotes/notes/keep-alive-b5ec5febb435daad.yaml

**Comment by majorgreys** [comment]
> We should update the release note: https://github.com/DataDog/dd-trace-py/blob/f8ed932c0/releasenotes/notes/keep-alive-b5ec5febb435daad.yaml

Missed this!

If that's a feature, this should be a fix then and be a separate release note. That work?

**Comment by majorgreys** [comment]
Or treat the feature up till now not released?

**Review by brettlangdon — APPROVED** [review]

**Review by mabdinur — APPROVED** [review]

**Comment by brettlangdon** [comment]
@Mergifyio backport 1.0

**Pull request merged**
