### PR TITLE
chore(ci): add rust toolchain to ci environments

### PR DESCRIPTION
**Pull request by brettlangdon**
Not currently being used, but will be needed in the future.

## Testing

These are the necessary edits I've need on #9232 in order to get CI to be green for building the package in CircleCI and cibuildwheel.

## Checklist

- [x] Change(s) are motivated and described in the PR description
- [x] Testing strategy is described if automated tests are not included in the PR
- [x] Risks are described (performance impact, potential for breakage, maintainability)
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed or label `changelog/no-changelog` is set
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/))
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))
- [x] If this PR changes the public interface, I've notified `@DataDog/apm-tees`.

## Reviewer Checklist

- [x] Title is accurate
- [x] All changes are related to the pull request's stated goal
- [x] Description motivates each change
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- [x] Testing strategy adequately addresses listed risks
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] Release note makes sense to a user of the library
- [x] Author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Comment by brettlangdon** [comment]
Still not getting builds passing 100%

https://github.com/DataDog/dd-trace-py/actions/runs/9045298537/job/24854896593#step:7:1971

> rustup: installer for platform 'i686-unknown-linux-musl' not found, this may be unsupported

I have tried adding that target and it still fails.

This PR as-is is still progress.

**Review by emmettbutler — APPROVED** [review]

**Comment by brettlangdon** [comment]
I haven't figured out how to get the musl target to properly install/be available yet, so will hold until I figure that out.

**Comment by brettlangdon** [comment]
I won't enable auto-merge for this, we first need to discuss if it is safe/advisable for us to drop musllinux-i686 builds. 

We will *have* to do that whenever we add Rust since it doesn't support that as a target, but we need to try and determine if any of our users are actively using it.

This is considered a breaking change right? Since this would be dropping system support that we say we support.

**Comment by brettlangdon** [comment]
Moving back to a draft, since there are some options we can possibly take to still support musllinux-i686

From @sanchda:

- Random thoughts
  - i686 musl is a tier 2 target with std support, so the language should build
  - the fact that i686 linux unknown exists and is a thing makes me think that i686 support is mostly there (although certain things may be missing for certain libraries)
- possible alternatives to dropping
  - cross-compile for an i686-musl target from x86_64-musl.  Conceptually this should work at the compiler level
  - cross-build for an i686-musl target from an i686-gnu target.  I used to do this for C and C++, but I’m not sure how hard it is to do it for rust.
    - libdatadog [does a version of this workflow](https://github.com/DataDog/libdatadog/blob/main/tools/docker/Dockerfile.build), which I believe involves calling the debian cargo from alpine to bootstrap things
  - build the required ecosystem for i686-musl from scratch, use it as a base image for Docker

**Comment by romainkomorndatadog** [comment]
I know this is kind of off-topic, but I'd really want to make sure that whatever changes we make in CI are easily reproduced locally for dev scenarios. I don't know if that means modifying the testrunner image, or adding hatch/riot things, so that we can easily build and test in it, but it's important that the dev and CI workflows converge rather than diverge.

**Comment by brettlangdon** [comment]
> I know this is kind of off-topic, but I'd really want to make sure that whatever changes we make in CI are easily reproduced locally for dev scenarios. I don't know if that means modifying the testrunner image, or adding hatch/riot things, so that we can easily build and test in it, but it's important that the dev and CI workflows converge rather than diverge.

@romainkomorndatadog this is already done, there just happens to be a handful of different places where we need to add rust compiler :/

e.g. `./scripts/ddtest` already has rust compiler.

if you want to build locally you'll need to install rust on your laptop, but assume that isn't a massive barrier (other than we'll want to make sure repo onboarding docs include that step).

**Comment by brettlangdon** [comment]
We have figured out how to get builds working for musl linux i686. We have to use the custom image from #9319

**Review by emmettbutler — APPROVED** [review]

**Pull request merged**
