### PR TITLE
chore(aiopg): remove references to asyncio.coroutine

### PR DESCRIPTION
**Pull request by Yun-Kim**
Our aiopg integration continues to have references to the deprecated `asyncio.coroutine` decorator and `yield from` syntax, whereas the former has been removed as of Python 3.11. This PR removes those references and replaces them with the `async def/await` syntax.

Note: We do not yet support `aiopg>=1.0`, but this PR unblocks the syntax errors for that support work.

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) are followed.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] Author is aware of the performance implications of this PR as reported in the benchmarks PR comment.

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer is aware of, and discussed the performance implications of this PR as reported in the benchmarks PR comment.

### CODE REVIEW

**Review by Kyle-Verhoog — CHANGES_REQUESTED** [review]
I think we have to `pytest.mark.asyncio()` these test cases in order for pytest to run them.

Looks like they are silently failing:

```
tests/contrib/aiopg/test.py::AiopgAnalyticsTestCase::test_analytics_without_rate
  /root/.pyenv/versions/3.6.15/lib/python3.6/unittest/case.py:605: RuntimeWarning: coroutine 'AiopgAnalyticsTestCase.test_analytics_without_rate' was never awaited
    testMethod()

tests/contrib/aiopg/py35/test.py::TestPsycopgPatch::test_cursor_ctx_manager
  /root/.pyenv/versions/3.6.15/lib/python3.6/unittest/case.py:605: RuntimeWarning: coroutine 'TestPsycopgPatch.test_cursor_ctx_manager' was never awaited
    testMethod()
```

https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/30222/workflows/071ad940-273e-406d-be83-ccbf643c8827/jobs/2051256

**Comment by Kyle-Verhoog** [comment]
Other than that this looks good to go! 👏

**Comment by Yun-Kim** [comment]
Looks like `pytest.mark.asyncio` does not fix the issue as the coroutines still don't get awaited. Will have to dig into this further.

**Review by mabdinur — APPROVED** [review]

**Comment by Yun-Kim** [comment]
Currently we support (and test) up to `aiopg<=0.16.0`. However, these older versions of `aiopg` internally keeps references to `asyncio.coroutine` while `aiopg>=1.0` updated itself to use `async def`. It looks like this PR isn't quite applicable to the older versions we test with at the moment, so I'll be closing this until we can in clude this in a larger effort PR to support `aiopg>=1.0`.

**Pull request closed without merging**
