### PR TITLE
fix(asm): improve cookies management for fastapi by using starlette parser

### PR DESCRIPTION
**Pull request by christophe-papazian**
Improve cookie management for fastapi and ASM by using starlette parser. This ensure that data sent to the waf before the request is processed by the customer code gets exactly the same cookies data as customer code.
Previously, computation was done on the middleware level with Python http.cookies

Also, minor improvement of asm fast api test for cookies to handle some corner case. It will also be tested in system tests.

FastAPI ASM support is still a private wip feature, and this is a fix for https://github.com/DataDog/dd-trace-py/pull/7220

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)
- [x] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [x] This PR doesn't touch any of that.

### CODE REVIEW

**Review by juanjux — APPROVED** [review]

**Review by majorgreys — COMMENTED** [review]
Does this make sense as a fix?

**Comment by christophe-papazian** [comment]
> Does this make sense as a fix?

It's a fix of an unreleased feature. Should I use fix for that ?

**Review by avara1986 — APPROVED** [review]

**Review by majorgreys — CHANGES_REQUESTED** [review]
Needs release note and backports if it is a fix.

**Comment by christophe-papazian** [comment]
> Needs release note and backports if it is a fix.

But it was not released yet.

**Review by majorgreys — APPROVED** [review]

**Pull request merged**
