### PR TITLE
[tracking] asyncio utils

### PR DESCRIPTION
**Pull request by thehesiod**
It accomplishes the following:
1) ~~adds aiobotocore support~~ (merged https://github.com/DataDog/dd-trace-py/pull/257)
2) ~~adds aiopg support + simplification of TracedCursor to avoid duplicate code~~ (merged https://github.com/DataDog/dd-trace-py/pull/258)
3) ~~adds chaining of asyncio contexts to child tasks~~ (merged https://github.com/DataDog/dd-trace-py/pull/260)
4) ~~parenting distributed tracing support to aiohttp + error support~~ (merged https://github.com/DataDog/dd-trace-py/pull/259)
5) aiohttp client tracing (https://github.com/DataDog/dd-trace-py/pull/294)

enhancement bugfixes:
* ~~support for aiohttp `MIN_ERROR`~~ (can no be achieved via trace filtering)
* ~~fix for https://github.com/DataDog/dd-trace-py/issues/323 (another in https://github.com/DataDog/dd-trace-py/pull/380)~~ other PRs merged

### CODE REVIEW

**Comment by thehesiod** [comment]
ok so I've that the aiopg + aiobotocore patching is working.  I created some unittests but I think I haven't integrated them correctly as the test system is throwing several errors when it attempts to run them.  Also the flake8 testing is using python2 so it's unable to validate the files with "yield from" so I'm not sure how you guys want to approach that.  If I could get some guidance in that area it would be great.

**Comment by thehesiod** [comment]
I've verified metrics go to datadog with these changes, however I noticed that the aiobotocore patch does not end up chaining to an outer aiohttp span.

**Comment by thehesiod** [comment]
ok, all works!

**Comment by palazzem** [comment]
Thank you @thehesiod! I'll provide the proper review to this great work so that during the week we can surely work/merge that!

Thanks again for this important contribution for new async Python libraries!

**Comment by thehesiod** [comment]
btw what's missing in this mix is an aiohttp "client" tracer

**Comment by thehesiod** [comment]
@palazzem ping :)

**Comment by palazzem** [comment]
Hello @thehesiod and sorry for being late! I'll try to make a proper release by the end of this week or at most the next one. Probably it could be better if you can split this PR in multiple PRs since here we're providing different integrations and functionalities. What would be great is having a PR for:
* `aiobotocore`
* `aiopg`
* chaining of `asyncio` contexts
* parenting distributed tracing support to `aiohttp` (this one requires especially a separated PR because we're still evaluating if making it active by default)
* `aiohttp` error status support
* simplification of `TracedCursor`

I know that probably it's some work on your side, but it will speed up the process. Indeed, we can merge each single PR as soon as we review it, without waiting for a full review of all functionalities. What do you think?

**Comment by thehesiod** [comment]
I'll try working on this today

**Comment by palazzem** [comment]
Thank you a lot @thehesiod !

**Comment by thehesiod** [comment]
aiobotocore: https://github.com/DataDog/dd-trace-py/pull/257

**Comment by palazzem** [comment]
Great @thehesiod ! that will make our review easier! 
Thanks again!

**Comment by thehesiod** [comment]
just added support for 'base' parent span info to be able to parent tasks in sub-processes w/o having to wrap them in new spans

**Comment by thehesiod** [comment]
and I think this is needed for task chaining due to the following scenario:
begin task A
task A starts task B1..B10
finish task B1-B9 (B10 still on trace stack)
task A starts task C

now task C gets parented to task B10 since it's still on the stack, however was not actually triggered by B10

**Comment by thehesiod** [comment]
ok, just pushed a fix which yields much better task chaining

**Comment by thehesiod** [comment]
ping :)

**Comment by thehesiod** [comment]
ping, any update about error handling?  Our other services (@alexmac) would like to switch to the official aiohttp module but we don't want 4xxs marked as errors.  thanks!

**Comment by palazzem** [comment]
@thehesiod sure! we're shipping a new release with some bugfixes and then we can work on it. Your current approach is providing a way to configure the status code that is considered an error, having 500 as default. In your applications what is the status code that you want to mark as error?

**Comment by thehesiod** [comment]
so my current impl is to keep 400+ as error, but allow others to configure the minimum error code to be considered an error.  We want 500+ as error

**Comment by thehesiod** [comment]
going to remove the error filtering with http://pypi.datadoghq.com/trace/docs/#trace-filtering now that it's available.

**Comment by thehesiod** [comment]
closing in favor of https://github.com/DataDog/dd-trace-py/pull/294 now that all other issues have been resolved

**Pull request closed without merging**
