### PR TITLE
ci: lower max pool of workers for grpc server

### PR DESCRIPTION
**Pull request by majorgreys**
## Description

Followup on #1961 to further reduce the number of threads in the server pool as another attempt to avoid the deadlocks that are causing the grpc job to hang in CI.

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Review by jd — DISMISSED** [review]
Please say why in the commit message 😄

**Comment by majorgreys** [comment]
Ran the job three times and did not get the timeout issue again but did get this exception:

```
E0128 15:54:50.778918098    3456 sync_posix.cc:85]           assertion failed: pthread_mutex_lock(mu) == 0
ERROR: InvocationError for command /root/project/.tox/grpc_contrib-py27-grpc118-googleapis-common-protos/bin/pytest tests/contrib/grpc (exited with code -6 (SIGABRT)) (exited with code -6)
```

https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/4865/workflows/f5bb0d3d-7cfb-43b1-a919-c82c61eae9f5/jobs/465320

**Comment by majorgreys** [comment]
> Please say why in the commit message 😄

Added! Had this as a draft initially as I wasn't sure if it would work, was just a hunch on what to try.

**Review by Kyle-Verhoog — APPROVED** [review]

**Review by jd — COMMENTED** [review]
Thank you! I'm a bit worried there's a deadlock but I guess it's not our fault?

**Pull request merged**
