### PR TITLE
chore(tracing): change system.pid to process_id

### PR DESCRIPTION
**Pull request by wconti27**
## Description
Changing the system.pid span attribute to process_id.  Tests were also updated to have new process_id assertion.

## Motivation
Part of a larger effort to make tag naming more consistent among Datadog tracing libraries. 'process_id' is a required attribute for all spans.

## Design 
No real design choices to be made. Changed constant string for PID and updated snapshots

## Testing strategy
Snapshot tests updated. Also changed a util test asserting on system.pid before to now assert on process_id

Newly added general tags are also being tested in the system testing repo as well with this PR (component, span.kind, language, process_id): [add_meta_tag_testing ](https://github.com/DataDog/system-tests/pull/645)

## Relevant issue(s)
Related PR's:
- [Add component tag within Python tracer ](https://github.com/DataDog/dd-trace-py/pull/4524)
- [Add span.kind tag within Python tracer ](https://github.com/DataDog/dd-trace-py/tree/AIT-5038-add-span-kind-tag)
- [Add language tag within Python tracer ](https://github.com/DataDog/dd-trace-py/pull/4535)
- [Change system.pid tag to process_id within Python tracer ](https://github.com/DataDog/dd-trace-py/pull/4534)

## Reviewer Checklist
- [x] Title is accurate.
- [x] Description motivates each change.
- [x] No unnecessary changes were introduced in this PR.
- [x] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Tests provided or description of manual testing performed is included in the code or PR.
- [x] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [x] All relevant GitHub issues are correctly linked.
- [x] Backports are identified and tagged with Mergifyio.

### CODE REVIEW

**Comment by brettlangdon** [comment]
Context for others, our backend already remaps `system.pid` to `process_id`, so the `system.pid` tag doesn't show up for anyone right now anyways.

**Comment by brettlangdon** [comment]
I labeled as not needing a changelog, and updated title to be a `chore` since there shouldn't be any customer facing impact from this change since we already remap the tag.

Anyone feeling differently?

**Review by brettlangdon — APPROVED** [review]

**Comment by Yun-Kim** [comment]
> I labeled as not needing a changelog, and updated title to be a `chore` since there shouldn't be any customer facing impact from this change since we already remap the tag.
> 
> Anyone feeling differently?

Technically this is a breaking change since `ddtrace.constants` is a public module. If we're confident this shouldn't affect users in any way, we should still consider adding a release note just in case?

**Comment by brettlangdon** [comment]
> > I labeled as not needing a changelog, and updated title to be a `chore` since there shouldn't be any customer facing impact from this change since we already remap the tag.
> > Anyone feeling differently?
> 
> Technically this is a breaking change since `ddtrace.constants` is a public module. If we're confident this shouldn't affect users in any way, we should still consider adding a release note just in case?

🤔 hmm. The variable name isn't change, the value changing _should_ be ok ... ?

I don't think I have a strong opinion about adding a note for:

> tracing: ``ddtrace.constants.PID`` is now ``process_id`` instead of ``system.pid``

?

**Review by mabdinur — APPROVED** [review]

**Pull request merged**
