### PR TITLE
ci: add Python 3.10 in Docker image

### PR DESCRIPTION
**Pull request by jd**

### CODE REVIEW

**Review by brettlangdon — APPROVED** [review]
👍🏻 I thought this was already there 🤔

**Comment by brettlangdon** [comment]
3.10 rc is going on right now, so won't be long until we can have `3.10` (and update the default?)

**Comment by jd** [comment]
> 👍🏻 I thought this was already there 🤔

You tried, but you needed buster, which broke mysql/psycopg2 and you revert.

So I picked up the job back 😁

**Comment by brettlangdon** [comment]
it has all come full circle 😆

**Review by Kyle-Verhoog — APPROVED** [review]

**Pull request merged**
