### PR TITLE
Add support for Python 2.7 on Windows

### PR DESCRIPTION
**Pull request by brettlangdon**
Fix broken builds for Python 2.7 on windows where ``<stdint.h>`` was not available.
This change also ensures we build and publish cp27-win wheels.

### CODE REVIEW

**Comment by brettlangdon** [comment]
So far this PR ensures we can build cp27-win wheels without error, but we still need to test that the wheels work as intended on windows before merging.

**Review by jd — DISMISSED** [review]
Unless Windows lies about __int64 we should be good.

**Comment by jd** [comment]
Setting manual merge label if you don't want this to be merged @brettlangdon

**Comment by brettlangdon** [comment]
👍🏻 to manual merge, yes

**Comment by brettlangdon** [comment]
```
PS C:\Users\brett-datadog> .\python2.2.7.18\tools\python.exe -m pip install .\ddtrace-0.49.0.dev37+ga1ea18a2-cp27-cp27m-win_amd64.whl
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing c:\users\brett-datadog\ddtrace-0.49.0.dev37+ga1ea18a2-cp27-cp27m-win_amd64.whl
Collecting protobuf>=3 (from ddtrace==0.49.0.dev37+ga1ea18a2)
  Downloading https://files.pythonhosted.org/packages/61/75/0123d3b3ff35717b194f0d2938377a977d9c1b932f2636f01d3819407c32/protobuf-3.15.8-py2.py3-none-any.whl (173kB)
     |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 174kB 2.2MB/s
Collecting tenacity>=5 (from ddtrace==0.49.0.dev37+ga1ea18a2)
  Downloading https://files.pythonhosted.org/packages/41/ee/d6eddff86161c6a3a1753af4a66b06cbc508d3b77ca4698cd0374cd66531/tenacity-7.0.0-py2.py3-none-any.whl
Collecting typing; python_version < "3.5" (from ddtrace==0.49.0.dev37+ga1ea18a2)
  Downloading https://files.pythonhosted.org/packages/3b/c0/e44213fcb799eac02881e2485724ba5b0914600bc9df6ed922e364fdc059/typing-3.7.4.3-py2-none-any.whl
Collecting enum34; python_version < "3.4" (from ddtrace==0.49.0.dev37+ga1ea18a2)
  Downloading https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
Collecting funcsigs>=1.0.0; python_version == "2.7" (from ddtrace==0.49.0.dev37+ga1ea18a2)
  Downloading https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting six>=1.7.0 (from ddtrace==0.49.0.dev37+ga1ea18a2)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting attrs>=19.2.0 (from ddtrace==0.49.0.dev37+ga1ea18a2)
  Downloading https://files.pythonhosted.org/packages/c3/aa/cb45262569fcc047bf070b5de61813724d6726db83259222cd7b4c79821a/attrs-20.3.0-py2.py3-none-any.whl (49kB)
     |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 51kB 1.7MB/s
Collecting monotonic>=0.6; python_version == "2.7" (from tenacity>=5->ddtrace==0.49.0.dev37+ga1ea18a2)
  Downloading https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Collecting futures>=3.0; python_version == "2.7" (from tenacity>=5->ddtrace==0.49.0.dev37+ga1ea18a2)
  Downloading https://files.pythonhosted.org/packages/d8/a6/f46ae3f1da0cd4361c344888f59ec2f5785e69c872e175a748ef6071cdb5/futures-3.3.0-py2-none-any.whl
Installing collected packages: six, protobuf, monotonic, futures, typing, tenacity, enum34, funcsigs, attrs, ddtrace
  WARNING: The script ddtrace-run.exe is installed in 'C:\Users\brett-datadog\python2.2.7.18\tools\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed attrs-20.3.0 ddtrace-0.49.0.dev37+ga1ea18a2 enum34-1.1.10 funcsigs-1.0.2 futures-3.3.0 monotonic-1.5 protobuf-3.15.8 six-1.15.0 tenacity-7.0.0 typing-3.7.4.3
WARNING: You are using pip version 19.2.3, however version 20.3.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\Users\brett-datadog> .\python2.2.7.18\tools\python.exe
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ddtrace
>>> from ddtrace.internal import _rand
>>> dir(_rand)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__test__', '_getstate', 'compat', 'os', 'rand64bits', 'seed']
>>> _rand.rand64bits()
5941114066147766285L
>>> _rand.rand64bits()
3241864821367263781L
>>> _rand.rand64bits()
7951037575430177780L
>>> _rand.rand64bits()
1197892036694622031L
>>> _rand.rand64bits()
9673192342372174513L
>>> _rand.seed()
>>> _rand.rand64bits()
1404312687414514635L
>>> _rand.rand64bits()
10551165008799724378L
>>>
```

**Review by P403n1x87 — APPROVED** [review]

**Review by jd — APPROVED** [review]

**Pull request merged**
