### PR TITLE
fix(kafka): do identity checks on kafka messages to work around __len__ issue

### PR DESCRIPTION
**Pull request by emmettbutler**
This pull request fixes https://github.com/DataDog/dd-trace-py/issues/8602 by changing `if message` tests in the Kafka contrib to `if message is not None`. This avoids the runtime calling `__len__` on the message object, which is not guaranteed by confluent-kafka to be defined.

## Checklist

- [x] Change(s) are motivated and described in the PR description
- [x] Testing strategy is described if automated tests are not included in the PR
- [x] Risks are described (performance impact, potential for breakage, maintainability)
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed or label `changelog/no-changelog` is set
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/))
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))
- [x] If this PR changes the public interface, I've notified `@DataDog/apm-tees`.
- [x] If change touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.

## Reviewer Checklist

- [x] Title is accurate
- [x] All changes are related to the pull request's stated goal
- [x] Description motivates each change
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- [x] Testing strategy adequately addresses listed risks
- [x] Change is maintainable (easy to change, telemetry, documentation)
- [x] Release note makes sense to a user of the library
- [x] Author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by mabdinur — APPROVED** [review]
Nice fix but we should look into removing the [__bool__ = True](https://github.com/DataDog/dd-trace-py/blob/v2.7.2/ddtrace/contrib/kafka/patch.py#L74) override. This could cause more issues down the line. We should find a way to support Pin without this hack.

**Comment by philipbjorge** [comment]
@emmettbutler -- 
Do you know if this fix will be backported into 2.7?
We're being impacted by this and trying to figure out whether to downgrade or wait for a backport. Cheers.

**Comment by emmettbutler** [comment]
@philipbjorge yes, the backport is in progress here https://github.com/DataDog/dd-trace-py/pull/8712

**Comment by emmettbutler** [comment]
The backport has been merged and this change will be released in the next 2.7 patch release.

**Pull request merged**
