### PR TITLE
fix(asm): insert user information in span

### PR DESCRIPTION
**Pull request by pvicente**
Fixes https://github.com/DataDog/dd-trace-py/issues/6551

Make it posible to choose user information span, by default it was root_span but sometimes this root_span is not the one where user information should be set. See issue for more details.

## Checklist
- [X] Change(s) are motivated and described in the PR description.
- [X] Testing strategy is described if automated tests are not included in the PR.
- [X] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [X] Change is maintainable (easy to change, telemetry, documentation).
- [X] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [X] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [X] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by emmettbutler — CHANGES_REQUESTED** [review]
Thanks for the contribution! It looks solid to me. Would you be willing to add a unit test for this new functionality?

**Comment by juanjux** [comment]
Hi,

Thanks for the contribution! Since this doesn't break backwards compatibility it LGTM. However, you also do a PR, linked to this one, for updating the docs here: https://docs.datadoghq.com/security/application_security/threats/add-user-info/?tab=set_user (if you can't for any reason just tell me and I'll do it once this is merged).

**Review by juanjux — DISMISSED** [review]

**Comment by pvicente** [comment]
> Thanks for the contribution! It looks solid to me. Would you be willing to add a unit test for this new functionality?

Hi, I've just added a test for both functions, let me know if that is ok

**Comment by pvicente** [comment]
> Hi,
> 
> Thanks for the contribution! Since this doesn't break backwards compatibility it LGTM. However, you should also do a PR, linked to this one, for updating the docs here: https://docs.datadoghq.com/security/application_security/threats/add-user-info/?tab=set_user (if you can't for any reason just tell me and I'll do it once this is merged).

Hi @juanjux, I've checked the docs repo but not sure if you want me to change how functions are called now in [here](https://github.com/DataDog/documentation/blob/1f11ceee92075d636a3d6672e4a0304a71739a34/content/en/security/application_security/threats/add-user-info.md?plain=1#L288).

is it just adding parameter span=selected_span? 

TBH, I'm not sure how to write it up in docs or what to say about this.

**Review by emmettbutler — DISMISSED** [review]

**Comment by pvicente** [comment]
@mabdinur could you review this please?

**Comment by juanjux** [comment]
@pvicente don't worry about the docs, I'll update them once this is merged.

**Comment by pvicente** [comment]
> @pvicente don't worry about the docs, I'll update them once this is merged.

Thanks @juanjux, any chance this PR could be merged soon?

**Comment by pvicente** [comment]
@tabgok @emmettbutler could you please review it and merge if all ok in your side?

**Review by emmettbutler — APPROVED** [review]

**Review by mabdinur — APPROVED** [review]

**Comment by pvicente** [comment]
@mabdinur who is in charge of doing backport of these changes to other release branches?

**Comment by romainkomorndatadog** [comment]
@pvicente , we usually do backports based on the `backport-xxx` tags that get added. For fixes, our [guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#backporting) are the maintained release branches (which would be `1.17` and `1.18`, and `1.19` since we just started the `1.19` release cycle).

I just added the labels (as one can see). I'm not sure what the schedule will be for rolling out those two backports. `1.19` should be out early next week at the latest.

**Pull request merged**
