### PR TITLE
chore(ci): remove backport action

### PR DESCRIPTION
**Pull request by brettlangdon**
We require signed commits in order to merge PRs and this action does not support commit signing.

We could create a bot/GPG key specifically for this action and configure it with git, but in order to avoid having PRs end up in a bad state we will remove it instead

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) are followed.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] Author is aware of the performance implications of this PR as reported in the benchmarks PR comment.

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer is aware of, and discussed the performance implications of this PR as reported in the benchmarks PR comment.

### CODE REVIEW

**Review by Yun-Kim — APPROVED** [review]

**Review by emmettbutler — APPROVED** [review]

**Review by mabdinur — CHANGES_REQUESTED** [review]
Although this action does not produce PRs with signed commits, I think it still has value. Occasionally we forget to backport changes after a PR is merged. This action solves this problem. After a backport PR is opened we can sign commits manually. Maybe we can document the manual commit signing step in a github comment or the PR description. 

Thoughts?

**Comment by brettlangdon** [comment]
> Although this action does not produce PRs with signed commits, I think it still has value. Occasionally we forget to backport changes after a PR is merged. This action solves this problem. After a backport PR is opened we can sign commits manually. Maybe we can document the manual commit signing step in a github comment or the PR description.
> 
> Thoughts?

@mabdinur I also have this https://github.com/DataDog/dd-trace-py/pull/5118

which adds a local script that basically duplicates what this action does, but it needs to be run manually _after_ a PR has been merged.

I was torn between having an automated process that is broken vs a manual action that works.

**Comment by Yun-Kim** [comment]
> I was torn between having an automated process that is broken vs a manual action that works.

I would prefer the latter over the former. In fact, I would argue that we should remove it as this would likely cause confusion/headaches for first-time contributors or anyone who's not aware that this job is currently broken. Once we can figure out how to properly run an automated job for this, then we should put it back in a PR.

In the meantime, I suggest we add a job (PR commenter bot?) to remind authors to backport their changes once merged and just stick to manual backporting.

**Review by mabdinur — APPROVED** [review]

**Comment by brettlangdon** [comment]
> Heck, or just add a PR checklist item as a reminder.

this was my thinking.

**Pull request merged**
