### PR TITLE
Disable Python 3.4 + Django tests as they segfault

### PR DESCRIPTION
**Pull request by jd**

### CODE REVIEW

**Comment by jd** [comment]
Now SQLAlchemy is segfaulting and it's not even on Python 3.4. WTF.

**Comment by codeboten** [comment]
@jd did you ever figure out why the sqlalchemy tests started seg faulting?

**Comment by brettlangdon** [comment]
@codeboten no idea. I tried to trace down the Django failing tests, seemed like it was coming from importing something from `attr` in `pytest`, but really didn't lead anywhere.

I have been meaning to try and reproduce locally or maybe try using GitHub actions quick to see if it is a CircleCI issue, maybe a tox/pip caching issue?

**Comment by codeboten** [comment]
Been able to pretty consistently reproduce the sqlalchemy segfault locally using docker-compose + the testrunner container. Here's the backtrace from a coredump if it helps:
```
Core was generated by `/src/.tox/sqlalchemy_contrib-py35-sqlalchemy12-psycopg228-mysqlconnector/bin/py'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  write_thread_id (tstate=0xf1, is_current=0, fd=2) at Python/traceback.c:701
701	    dump_hexadecimal(fd, (unsigned long)tstate->thread_id, sizeof(unsigned long)*2);
[Current thread is 1 (Thread 0x7f0d627bc700 (LWP 45342))]
(gdb) bt
#0  write_thread_id (tstate=0xf1, is_current=0, fd=2) at Python/traceback.c:701
#1  _Py_DumpTracebackThreads (fd=fd@entry=2, interp=interp@entry=0x55f990603d70, current_thread=0x0) at Python/traceback.c:735
#2  0x000055f98e3fae3e in faulthandler_dump_traceback (interp=<optimized out>, all_threads=<optimized out>, fd=<optimized out>) at ./Modules/faulthandler.c:242
#3  faulthandler_fatal_error (signum=11) at ./Modules/faulthandler.c:339
#4  <signal handler called>
#5  0x00007f0e6b249c7c in elf_machine_rela (skip_ifunc=0, reloc_addr_arg=0x7f0e59825fb0, version=0xa8, sym=0x7f0e5961f5a8, reloc=0x7f0e596207b8, map=0x55f99135a900)
    at ../sysdeps/x86_64/dl-machine.h:307
#6  elf_dynamic_do_Rela (skip_ifunc=0, lazy=<optimized out>, nrelative=<optimized out>, relsize=<optimized out>, reladdr=<optimized out>, map=0x55f99135a900) at do-rel.h:137
#7  _dl_relocate_object (scope=<optimized out>, reloc_mode=reloc_mode@entry=0, consider_profiling=<optimized out>, consider_profiling@entry=0) at dl-reloc.c:259
#8  0x00007f0e6b251de1 in dl_open_worker (a=a@entry=0x7f0d627bbc20) at dl-open.c:435
#9  0x00007f0e6b24d644 in _dl_catch_error (objname=objname@entry=0x7f0d627bbc10, errstring=errstring@entry=0x7f0d627bbc18, mallocedp=mallocedp@entry=0x7f0d627bbc0f,
    operate=operate@entry=0x7f0e6b251a70 <dl_open_worker>, args=args@entry=0x7f0d627bbc20) at dl-error.c:187
#10 0x00007f0e6b251609 in _dl_open (file=0x7f0e6b0342cf "libgcc_s.so.1", mode=-2147483646, caller_dlopen=0x7f0e6b03266b <pthread_cancel_init+43>, nsid=-2, argc=<optimized out>,
    argv=<optimized out>, env=0x55f991308960) at dl-open.c:660
#11 0x00007f0e6a69631d in do_dlopen (ptr=ptr@entry=0x7f0d627bbe60) at dl-libc.c:87
#12 0x00007f0e6b24d644 in _dl_catch_error (objname=0x7f0d627bbe40, errstring=0x7f0d627bbe48, mallocedp=0x7f0d627bbe3f, operate=0x7f0e6a6962e0 <do_dlopen>, args=0x7f0d627bbe60)
    at dl-error.c:187
#13 0x00007f0e6a6963af in dlerror_run (operate=operate@entry=0x7f0e6a6962e0 <do_dlopen>, args=args@entry=0x7f0d627bbe60) at dl-libc.c:46
#14 0x00007f0e6a696422 in __GI___libc_dlopen_mode (name=name@entry=0x7f0e6b0342cf "libgcc_s.so.1", mode=mode@entry=-2147483646) at dl-libc.c:163
#15 0x00007f0e6b03266b in pthread_cancel_init () at ../sysdeps/nptl/unwind-forcedunwind.c:52
#16 0x00007f0e6b032854 in _Unwind_ForcedUnwind (exc=0x7f0d627bcd70, stop=0x7f0e6b030bf0 <unwind_stop>, stop_argument=0x7f0d627bbf70) at ../sysdeps/nptl/unwind-forcedunwind.c:126
#17 0x00007f0e6b030d80 in __GI___pthread_unwind (buf=<optimized out>) at unwind.c:121
#18 0x00007f0e6b029595 in __do_cancel () at pthreadP.h:283
#19 __pthread_exit (value=value@entry=0x0) at pthread_exit.c:28
#20 0x000055f98e3b898c in PyThread_exit_thread () at Python/thread_pthread.h:266
#21 0x000055f98e3bdd46 in t_bootstrap (boot_raw=0x55f99163f610) at ./Modules/_threadmodule.c:1028
#22 0x00007f0e6b0284a4 in start_thread (arg=0x7f0d627bc700) at pthread_create.c:456
#23 0x00007f0e6a65fd0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by brettlangdon** [comment]
Oh yeah, I haven't tried digging into the SQLAlchemy issues yet 😩 

Nothing in there stands out to me right away :(

**Comment by codeboten** [comment]
One more data point, it only happens when both mysql and postgres tests are run together. Looks like something gets angry on exit :(

**Comment by codeboten** [comment]
So at least the sqlalchemy failures were caused by a new version of mysql-connector, created a PR here https://github.com/DataDog/dd-trace-py/pull/1138, found the following issue https://bugs.mysql.com/bug.php?id=97220

**Comment by jd** [comment]
Thanks for the investigation. Clearly something in C land is doing bad things. :(

**Comment by codeboten** [comment]
For what it's worth, I've managed to get the django tests passing by disabling the circle cache for those tests, way slower, but at least consistent

**Pull request closed without merging**
