### PR TITLE
WIP: Implement a ContextVarProvider for Python 3.7+

### PR DESCRIPTION
**Pull request by orf**
This is a continuation of https://github.com/DataDog/dd-trace-py/pull/723.

I adapted this a bit, I realized that on 3.7+ we can just use a ContextVar based provider instead of any thread locals, and not even need an asyncio based one.

Lets hope the tests pass.

### CODE REVIEW

**Comment by brettlangdon** [comment]
Related to #723 ?

**Comment by orf** [comment]
Yep, sorry, I've updated the PR text. From #723:

> The AsyncioContextProvider built into ddtrace works for exclusively async applications where stuff that happens asynchronously happens exclusively asynchronously. For things like django-channels however, some spans happen synchronously and some asynchronously in the same logical unit of work. 
> This usually happens through the @database_sync_to_async wrapper that Channels provides to move between the two worlds.
> To get traces to continue over the async/sync boundary (which is actually a thread boundary in the Channels implementation), the currently active tracing context must be passed across that boundary. Python 3.7 added support for ContextVars, which do exactly that as supported by Python itself. In combination with something like https://pypi.org/project/contextvars-executor/ , these ContextVars hold the same value in the code outside and inside of a new thread or a new asyncio.ThreadPool executor. 
> They're safer than normal thread locals, and the preferred pattern for implementing context in async code after Python 3.7. So, if you are using Python 3.7, and you want a simple way to pass ddtrace contexts between a main asyncio threadloop and inner ThreadPooled executors, use ContextVarContextProvider and contextvars-executor to keep your contexts intact across thread boundaries.

**Comment by orf** [comment]
I've also just noticed no tests are run on Python 3.7 :/

**Comment by brettlangdon** [comment]
That is correct, this is something we are actively working on. We want our test suite to run on 3.7.

#864

**Comment by orf** [comment]
Awesome. Well once that is merged we can really see if the tests pass :)

I will check back later.

**Comment by orf** [comment]
I've got an implementation of this that appears to pass all `asyncio` tests on Python 3.7. It turned out to be a bit more difficult than the original PR stated. I'm just brain dumping what I found during this for posperity here.

So `contextvar` objects are a drop in replacement for ThreadLocals, which is awesome. And we can then basically remove the custom `AsyncioContextProvider` on Python 3.7 and just use the default one. As a bonus, we can remove the need to patch anything at all for asyncio applications 🎉 🎉 🎉 

The hard and interesting bit is really keeping the compatibility between the older, hacky `patch()` based provier and the new one. Here are where the problems start:

1. Currently associating the context of a given task is done after creating it (in the `utils.py` file). When using a contextvar based approach it's impossible to modify another tasks context like that, especially if we want to remove the need for patching.

2. We can work around this by cloning the context object when we activate a new context (that is, the previous context's async task or thread has changed). Since we have a reference to the old context we can do this safely, and we form a chain of contexts.

3. OpenTracer uses `ThreadLocalScopeManager`, I'm not sure how to make this work.

4. Some tests in `tracer` now fail.

All in all it seems like it's possible, but pretty hard, to get this to work as expected. This PR is definitely not ready for anything, and pretty hacky/messy. But hopefully it can aide anyone in the future who looks at this.

**Comment by majorgreys** [comment]
Thank @orf for sharing this work. We recently released `ContextVar`-based context manager which is now the default for Python 3.7. Please take a look at #990 and do file any issues you find with it.

**Pull request closed without merging**
