### PR TITLE
Add agent endpoint to log messages

### PR DESCRIPTION
**Pull request by majorgreys**
## Commit Message
{{title}}

Add the api endpoint to the log messages where we are reporting the agent url.

## Checklist
- [ ] Added to the correct milestone.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Library documentation is updated.
- [ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).

### CODE REVIEW

**Review by Kyle-Verhoog — DISMISSED** [review]
great!

**Review by Kyle-Verhoog — DISMISSED** [review]

**Review by brettlangdon — DISMISSED** [review]
Beat me to it!

**Comment by Kyle-Verhoog** [comment]
Looks like there are additional test cases that need to be updated still

**Comment by brettlangdon** [comment]
@Mergifyio backport 0.56

**Review by brettlangdon — DISMISSED** [review]

**Review by brettlangdon — DISMISSED** [review]

**Review by brettlangdon — APPROVED** [review]

**Review by Kyle-Verhoog — APPROVED** [review]

**Pull request merged**
