### PR TITLE
fix(profiler): support for latest protobuf versions

### PR DESCRIPTION
**Pull request by P403n1x87**
Version 4.21 of the Python protobuf package introduced the [upb C backend](https://github.com/protocolbuffers/protobuf/tree/main/python#implementation-backends). The protobuf sources where generated by the 3.19 version of the compiler, so there are good chances that the latest protobuf releases are not well-supported by the profiler. In this change we re-compile the pprof protobuf spec with the latest 21 protoc compiler.

## Testing strategy

No issues have been reported by CI that can be related to a lack of support for latest versions of protobuf. Therefore it is unclear how to test for possible incompatibility issues.

## Risk

Support for different protobuf versions remain too coarse and prone to potential future incompatibilities. This problem will be resolved by the introduction of libdatadog which will delegate pprof generation to a native layer that allows us to drop the dependency on the Python protobuf package.

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines) are followed.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] PR description includes explicit acknowledgement/acceptance of the performance implications of this PR as reported in the benchmarks PR comment.

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.

### CODE REVIEW

**Review by majorgreys — APPROVED** [review]

**Comment by thiagocaiubi** [comment]
Hello @P403n1x87.

I still face issues with dd-trace-py 1.12.x and protobuf when enabling the profiler. Everything works with the profiler disabled. 
The Kubernetes pods keep crashing, leading to `CrashLoopBackOff`. 

Screenshot 2023-05-03 at 10 58 07

Screenshot 2023-05-03 at 11 00 06

What other info should I collect to help debug the issue?

cc @gustahrodrigues

**Comment by P403n1x87** [comment]
Hi @thiagocaiubi .

Thanks for reporting this. Would you be able to give us the full traceback and the output of `pip freeze`? 🙏

**Comment by thiagocaiubi** [comment]
Hi @P403n1x87, thanks for the quick response. 
I've attached the request info to the ticket number: 1190394. Do you have access to it?

**Comment by P403n1x87** [comment]
Yes, thank you @thiagocaiubi. I think we have a reproducer now, which gives us more confidence in the fix that we are preparing. Thanks again for the report, we hope to have the fix out ASAP.

**Pull request merged**
