### PR TITLE
feat: Support w3 traceparent headers

### LINKED ISSUE #3872: Feature request: Support traceparent header
This is similar to this feature request made on the JS library: https://github.com/DataDog/dd-trace-js/issues/1789

https://www.w3.org/TR/trace-context/#examples-of-http-traceparent-headers

We're using a self-hosted 3rd party service that uses OpenTelemetry for tracing and sending it to an OpenTelemetry ingest endpoint on Datadog agents. The service uses `traceparent` headers for outgoing HTTP requests to support distributed tracing, but I don't think the Python library supports this (at least, the term doesn't show up from a source search).

As referenced in the JS library issue, here's the spec on `traceparent`: https://www.w3.org/TR/trace-context/#traceparent-header

### PR DESCRIPTION
**Pull request by goodspark**
Fixes #3872

## Description

Supports distributed tracing for services that want to use the W3 trace propagation headers. https://www.w3.org/TR/trace-context

## Checklist
- [x] Title must conform to [conventional commit](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).
- [ ] Add additional sections for `feat` and `fix` pull requests.
- [ ] Ensure tests are passing for affected code.
- [ ] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] PR cannot be broken up into smaller PRs.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.
- [ ] Add to milestone.

### CODE REVIEW

**Comment by brettlangdon** [comment]
Hey @goodspark thanks for opening this PR!

We have been discussing lately about adding support for w3c context propagation headers. We are going to be discussing this internally over the next 1-2 weeks to solidify some of the details on how we want to support it (how to enable, what are the settings called, etc).

This is an awesome start to that work, but I want to wait until we have a more clearly defined specification for how we want this implemented across all languages so we don't have to come back to it later.

**Comment by goodspark** [comment]
Thanks for the update, Brett. Should we just close this for now then?

**Comment by brettlangdon** [comment]
> Thanks for the update, Brett. Should we just close this for now then?

We can keep it open! I think the changes here are a great start so even if we take over the PR a good place to get started.

**Comment by felipeagger** [comment]
This is perfect, @brettlangdon any news ?

**Comment by leandrorebelo** [comment]
I'm waiting for this

**Comment by OrlandoBitencourt** [comment]
I'm looking forward to this feature

**Comment by Kyle-Verhoog** [comment]
This work was added in #4170, thanks @goodspark for kicking this off!

**Pull request closed without merging**
