### PR TITLE
ci: automatically add release milestone to each PR

### PR DESCRIPTION
**Pull request by brettlangdon**
When a PR is closed with a merge we:

- Determine the target release/milestone based on the target branch name
- If the base branch is `[0-9].x` (dev branch)
  - Set the milestone as the next minor release for that release line.
- If the base branch is `[0-9].[0-9]+` (release branch)
  - Set the milestone as the next patch release for that version.
- If the branch does not match one of those patterns
  - Do not set a milestone.

### CODE REVIEW

**Comment by brettlangdon** [comment]
A few open questions:

Right now I have it ignoring prereleases, meaning if you target 1.x, even though the 1.0 branch exists, and v1.0.0rc1 tag exists, it will set the milestone to `v1.0.0`. It seems like maybe it should be `v1.1.0`... should it?


Do we want to also create a workflow to close a milestone when a release is published + update the milestone of any open PRs in that milestone? I am worried about when a PR is opened against `1.x` it will get the `v1.1.0` milestone, but then if it doesn't get merged in time, then we need to update it to `v1.2.0`, etc. The Java team gets around this by running the milestone tagging at PR close/merge not at open, so maybe that is the better approach?

**Comment by brettlangdon** [comment]
> I'd have added a few embedded unit tests just to be safe, in the script :)

yeah, I can probably add some doctests and figure out how to run in `riot`. happy to leave that as a blocker

**Comment by brettlangdon** [comment]
Done, added doctests to the script.

**Comment by brettlangdon** [comment]
I updated the script and my previous comment about open questions/PR description

I changed this to now run after a PR is merged. While we won't be able to use milestones to track in-process work, we will at least have an accurate accounting of each merge that should exist on that version.

We can still manually mark a PR with a milestone if it is meant to be a blocker for releasing that version.

**Review by P403n1x87 — DISMISSED** [review]

**Review by mabdinur — DISMISSED** [review]

**Comment by majorgreys** [comment]
@brettlangdon changed the pr title as it relates specific to ci

**Pull request merged**
