### PR TITLE
revert(tracing/internal): disable Datadog internal tag propagation

### PR DESCRIPTION
**Pull request by brettlangdon**

### CODE REVIEW

**Comment by brettlangdon** [comment]
@Mergifyio backport 0.x

**Comment by brettlangdon** [comment]
@Mergifyio backport 0.59

**Review by Kyle-Verhoog — COMMENTED** [review]
this seems like a revert rather than disabling?

**Review by majorgreys — DISMISSED** [review]

**Review by majorgreys — APPROVED** [review]

**Review by Kyle-Verhoog — APPROVED** [review]

**Comment by brettlangdon** [comment]
@Mergifyio backport 1.0

**Pull request merged**
