### PR TITLE
chore(internal): resolve incorrect import resolution from Cython

### PR DESCRIPTION
**Pull request by brettlangdon**
## Description
This change is a follow-up to #4085 to provide a more long term solution to the problem and reverting the pinning of `setuptools` versions.

`setuptools==64.0.0` changed the way editable modules are linked to in
`site-packages` (from `.egg-link` to `.pth` + a loader). This exposed
and issue with the import of `ddtrace.constants` from within a Cython module.

Cython was loading the `ddtrace.internal.constants` module instead.

See #4085 and https://github.com/brettlangdon/shadow-import-issue for more details.

## Checklist
- [x] Title must conform to [conventional commit](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).
- [x] Add additional sections for `feat` and `fix` pull requests.
- [x] Ensure tests are passing for affected code.
- [x] [Library documentation](https://github.com/DataDog/dd-trace-py/tree/1.x/docs) and/or [Datadog's documentation site](https://github.com/DataDog/documentation/) is updated. Link to doc PR in description.

## Reviewer Checklist
- [ ] Title is accurate.
- [ ] Description motivates each change.
- [ ] No unnecessary changes were introduced in this PR.
- [ ] PR cannot be broken up into smaller PRs.
- [ ] Avoid breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [ ] Tests provided or description of manual testing performed is included in the code or PR.
- [ ] Release note has been added for fixes and features, or else `changelog/no-changelog` label added.
- [ ] All relevant GitHub issues are correctly linked.
- [ ] Backports are identified and tagged with Mergifyio.
- [ ] Add to milestone.

### CODE REVIEW

**Review by Kyle-Verhoog — COMMENTED** [review]
Have we reported the issue to Cython?

**Review by Kyle-Verhoog — APPROVED** [review]

**Comment by brettlangdon** [comment]
> Have we reported the issue to Cython?

Not yet.

**Comment by brettlangdon** [comment]
This PR also isn't urgent to resolve/merge. Current state is "fixed", but would be nice to not pin setuptools if we can.

**Review by mabdinur — APPROVED** [review]

**Comment by mabdinur** [comment]
Failing test: https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/20575/workflows/955af50f-552f-4f55-b27d-2dda42d724c4/jobs/1395021/tests

We need to make [from ddtrace.profiling import bootstrap](https://github.com/DataDog/dd-trace-py/blob/1.x/tests/commands/ddtrace_run_profiling.py#L1) a relative import.

**Pull request merged**
