### PR TITLE
ci: use Debian Buster image to run tests

### PR DESCRIPTION
**Pull request by jd**
This is needed to deploy Python 3.10 which requires newer libssl version.

### CODE REVIEW

**Review by brettlangdon — DISMISSED** [review]

**Comment by jd** [comment]
/me looks at this very optimistic @brettlangdon

**Review by Kyle-Verhoog — COMMENTED** [review]
LGTM but I think it'd be worth adding more context to the PR to explain why we are actually making this change 🙂

**Comment by jd** [comment]
Done!

**Review by brettlangdon — COMMENTED** [review]
changes look fine, but should we separate removing mysqldb/version support changes into their own PR?

**Comment by jd** [comment]
Split into https://github.com/DataDog/dd-trace-py/pull/2509 and #2510

**Review by brettlangdon — APPROVED** [review]

**Review by majorgreys — APPROVED** [review]

**Pull request merged**
