### PR TITLE
Only call _store_request_headers/_store_response_headers if header tracing is enabled

### PR DESCRIPTION
**Pull request by brettlangdon**
This was found during the investigation of #2549,
we only need to convert the headers to a `dict`
if there are traced headers configured.

## Checklist
- [x] Added to the correct milestone.
- [x] Tests provided or description of manual testing performed is included in the code or PR.
- ~[ ] Library documentation is updated.~
- ~[ ] [Corp site](https://github.com/DataDog/documentation/) documentation is updated (link to the PR).~

### CODE REVIEW

**Review by P403n1x87 — APPROVED** [review]
👍  is it worth adding some test cases?

**Comment by brettlangdon** [comment]
> 👍 is it worth adding some test cases?

I am looking over them now, I think as long as we have tests that assert no headers are added if none are configured, functionally we are good?

Unless we care to codify "if none are configured, don't call this function"? which I am fine with adding as well.

**Comment by P403n1x87** [comment]
> > 👍 is it worth adding some test cases?
> 
> I am looking over them now, I think as long as we have tests that assert no headers are added if none are configured, functionally we are good?

Yes should be fine, maybe just a quick test case for the new property?

**Comment by brettlangdon** [comment]
> Yes should be fine, maybe just a quick test case for the new property?

Yup, very good point!

**Review by P403n1x87 — APPROVED** [review]
👍 👍

**Review by Kyle-Verhoog — APPROVED** [review]

**Pull request merged**
