### PR TITLE
Fix task context management for asyncio in Python <3.7

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
This PR introduces a fix for the following context management problem in asyncio in Python versions prior to 3.7.

(Note: this is not an issue in 3.7+ due to our handling of this issue when when ContextVars are available)

## Problem
When a new task is created we were copying the trace information (`trace_id`, `parent_id`, `sampling_priority`) from the context of the current task but were not copying the current span in the context. This is done under the hood in `context.clone()` which we were not using in the asyncio provider.

As pointed out by @thehesiod in #974, [the trace details are cleared from a context when finished](https://github.com/DataDog/dd-trace-py/blob/3129a400d1fee2c544408318f6819c5485ed39a8/ddtrace/context.py#L185-L187). So when a context is shared between two sequential coroutines (as done in the test case provided), the first will clear the context when finished and the second will be left with a null context, so it generates a new `trace_id` for the second coroutine.

## Solution
Less obtrusive than #974:

By using `context.clone()` we copy the current span into the context which is not cleared when the context finishes, so subsequent context users will have a current span and thus parenting/trace information will be propagated properly.

### Observations/Remarks/Questions

1. We currently generate new traces (sharing the same `trace_id`) for async tasks because we create new contexts. (This messes up metrics at the trace-agent?)

2. Does it make sense to clear the trace information from a context when it finishes? Why do we do this in the first place?

### CODE REVIEW

**Comment by thehesiod** [comment]
btw I don't think the use of ContextVars solves this 3.7+, because the spawned tasks are new tasks and the ContextVar is still per task to my understanding

**Comment by Kyle-Verhoog** [comment]
@thehesiod I think that you're right that ContextVars alone don't solve the issue; I should have been more precise with my wording.. I meant that in Python 3.7+ we're using ContextVars and we were using them differently than the asyncio context manager.

We `context.clone()` when using ContextVars.

https://github.com/DataDog/dd-trace-py/blob/3129a400d1fee2c544408318f6819c5485ed39a8/ddtrace/contrib/asyncio/patch.py#L19-L20

https://github.com/DataDog/dd-trace-py/blob/3129a400d1fee2c544408318f6819c5485ed39a8/ddtrace/contrib/asyncio/wrappers.py#L37-L51

**Comment by thehesiod** [comment]
Btw I tried switching to contextVars for our internal structures but found that if you're in function not decorated with async it won't find the context, this is really bad if you call a sync func from an async, so I had to go back to putting a prop on the task

**Comment by Kyle-Verhoog** [comment]
Hmm 😕. I'm going to see if I can get a test case for it. It might be worth doing a separate PR for that problem though.

**Comment by thehesiod** [comment]
let me know if this is not the case for you, if so I can revisit using context vars for our internal structures

**Pull request merged**
