### PR TITLE
chore(ci): disable macrobenchmark crash tracking to avoid signaling irrelevant crashes

### PR DESCRIPTION
**Pull request by igoragoli**
[APMSP-1452 Investigate increase in instability in python/macrobenchmarks after wsgi to gunicorn change](https://datadoghq.atlassian.net/browse/APMSP-1452)

Overview:
- Disable crash tracking to avoid signaling irrelevant crashes.

Motivation:
- `gunicorn` made macrobenchmarks unstable. We decided to switch back to `uwsgi`.
- `uwsgi` has a bug that causes crashes when shutting down workers. To avoid signaling irrelevant crashes, crash tracking should be disabled.
- Please see detailed notes here: https://docs.google.com/document/d/19dZru9rYzqWMyeHow5Krlw27UvGj_VaR_CmA-35HFaM/edit?tab=t.om7eivz03tmx

Testing:
- Ran smoke benchmarks after changes were made both in dd-trace-py and in benchmarking-platform. See [dashboard](https://ddstaging.datadoghq.com/dashboard/x79-z8u-xxh?fromUser=true&refresh_mode=paused&tpl_var_bp_branch%5B0%5D=igoragoli%2Fpython-macrobenchmarks-disable-crashtracking_test&tpl_var_bp_commit_sha%5B0%5D=f40a0571&tpl_var_ci_pipeline_id%5B0%5D=48422840&from_ts=1730965317666&to_ts=1730966313797&live=false).

## Checklist
- [x] PR author has checked that all the criteria below are met
- [x] The PR description includes an overview of the change
- [x] The PR description articulates the motivation for the change
- [x] The change includes tests OR the PR description describes a testing strategy
- [x] The PR description notes risks associated with the change, if any
- [x] Newly-added code is easy to change
- [x] The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- [x] The change includes or references documentation updates if necessary
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

**Review by gnufede — APPROVED** [review]

**Review by ddyurchenko — APPROVED** [review]

**Review by sanchda — CHANGES_REQUESTED** [review]
I have reservations about this.  Is the purpose of this PR only to squelch noisy crash logs in the UX?  Was a performance regression related to crashtracking discovered as part of the analysis?

If the UX is the issue, I propose adding a tag that can be filtered for.

**Review by emmettbutler — APPROVED** [review]

**Review by sanchda — APPROVED** [review]
Sounds like this may be the path of least harm, approving

**Comment by igoragoli** [comment]
Hi @sanchda, I didn't have the bandwidth to look into this until now.

Thank you for approving! That said, I agree filtering in the UX is a more sensible approach. 

The impact of disabling crash tracking is missing performance anomalies caused by crash tracking. We (APM Ecosystems Performance + @gnufede) discussed it internally, and it seems safe to do so for now. We can easily restore crash tracking if necessary.

**Pull request merged**
