### PR TITLE
fix(wsgi): handle django wsgi app being an iterator

### PR DESCRIPTION
**Pull request by emmettbutler**
This change fixes https://github.com/DataDog/dd-trace-py/issues/5325 by having the WSGI middleware handle cases when the wrapped iterable object is an iterator. This condition can arise when a Django app attempts to send its "request finished" signal, in which case it may cause connection leaks. Standard methods of distinguishing an iterable from its iterator, such as checking for the presence of __iter__ and __next__ methods, don't work in this case for unknown reasons. Instead of adding brittle special-case detection logic to the middleware, this new argument allows users to indicate when this is the case.

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included in the PR.
- [x] Risk is outlined (performance impact, potential for breakage, maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html) are followed. If no release note is required, add label `changelog/no-changelog`.
- [x] Documentation is included (in-code, generated user docs, [public corp docs](https://github.com/DataDog/documentation/)).
- [x] Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer has explicitly acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment.
- [x] Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)
- [x] If this PR touches code that signs or publishes builds or packages, or handles credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [x] This PR doesn't touch any of that.

### CODE REVIEW

**Comment by emmettbutler** [comment]
@petersalas let me know if this adjustment to your suggested fix makes sense to you.

**Comment by emmettbutler** [comment]
@petersalas let me know what you think of this addition to the change you proposed

**Comment by petersalas** [comment]
I added a repro of the original issue here: https://gist.github.com/petersalas/aa1ce634e2cd83fdf2dc22431c3a1b9b -- let me know if you're not able to reproduce it.

Re: the changes, I'm not sure I totally follow the behavior given the `wrapt.ObjectProxy` -- but if it fixes the Django repro above that's good enough for me. :)

**Comment by emmettbutler** [comment]
@petersalas thanks so much for the reproduction code. I adapted it into a test and changed this pull request such that it passes. The solution I've implemented here allows you to work around the issue by passing `app_is_iterator=True` to the `DDWSGIMiddleware` constructor.

**Comment by petersalas** [comment]
Glad to hear it! For my own understanding, what's the scenario where the new bool should _not_ be set to `True`?

**Comment by emmettbutler** [comment]
@petersalas [This test](https://github.com/DataDog/dd-trace-py/blob/6fd5712010c0ad614306c0dbfbe3691fccf052b8/tests/contrib/wsgi/test_wsgi.py#L194) was one of the many tests of the `DDWSGIMiddleware` that failed when the new logic was applied unconditionally. I suspect that the difference has to do with [this](https://docs.python.org/3/glossary.html#term-iterator) note from the Python documentation about subtle differences between different types of iterators:

> A container object (such as a [list](https://docs.python.org/3/library/stdtypes.html#list)) produces a fresh new iterator each time you pass it to the [iter()](https://docs.python.org/3/library/functions.html#iter) function or use it in a [for](https://docs.python.org/3/reference/compound_stmts.html#for) loop. Attempting this with an iterator will just return the same exhausted iterator object used in the previous iteration pass, making it appear like an empty container.

That test ends up giving the `TracedIterable` a generator object, whereas the test this pull request adds gives it a Django `HttpResponse` object. I suspect that these two types differ in the behavior described here, though I haven't been able to prove it yet.

I looked for a long time for a particular attribute or attributes that could be used to differentiate between objects that could handle this new logic and objects that still needed the old style. `__next__`, `__iter__`, and `__getitem__`, the ones that by specification differentiate iterables from iterators, followed the same set/unset pattern in both of these test cases, making them not a useful differentiator. The same was true of `__len__` in most cases. Because I couldn't find an intuitive way of having `TracedIterable` make this decision internally, I decided to push that responsibility to the integration code, where it makes sense to pass off this behavior as "Django does something weird here".

**Comment by petersalas** [comment]
@emmettbutler, thanks for clarifying! It looks like the issue you're describing is a side-effect of using `wrapt.ObjectProxy` -- when I [removed that bit](https://github.com/petersalas/dd-trace-py/commit/629f7261a8f9428a723d73f9d45a415f3203da0a) all the `wsgi` tests passed. That said, I'm not sure whether there are other reasons to use `wrapt.ObjectProxy` beyond (the now explicit) `__next__` delegation, so I'll leave it to you to decide what to do with that information :)

**Comment by emmettbutler** [comment]
@petersalas I think that because `TracedIterable` instances are returned to application code via a WSGI app's `__call__` function, they must inherit from `ObjectProxy` to avoid changing the contract between application code and the WSGI spec (one of the core objectives of dd-trace-py). Adding tests that validate this could be helpful in a future change.

Thanks again for the contributions!

**Review by mabdinur — APPROVED** [review]

**Pull request merged**
